### ISSUE TITLE
Share Shadowsocks works will, but can't share OpenVPN

### ISSUE THREAD

**Issue by l5h5t7** [Mygod/VPNHotspot#10]
### Environment

* Android Version: 6.0.1 (CyanogenMod)
* OpenVPN Package: https://f-droid.org/en/packages/de.blinkt.openvpn/

### What did you do?

Connect OpenVPN, open VPNHotspot and toggle the switch in "Repeater" on.

### What did you expect to see?

My device which installed OpenVPN can access Internet through VPN, and other devices can connect to the Hotspot to access Internet through VPN.

### What did you see instead?

My device which installed OpenVPN can access Internet through VPN, other devices can connect to the Hotspot, but no Internet is available.
Same issue is exist in "Tethering"(System built).

**Comment by Mygod** [comment]
I just tested Repeater with OpenVPN and it seems to be working. However it seems like it's also producing a lot of crashes for this app for some reason.
