### ISSUE TITLE
On Pixel 2 XL, Wi-Fi hotspot with SSR don't work

### ISSUE THREAD

**Issue by yingshaoxo** [Mygod/VPNHotspot#100]
Android 9 pie

Magisk Manager Rooting

SSR

___

I can connect to my hotspot, but can't pass by the GFW.
___

[vpnhotspot-1743180811612732424.log](https://github.com/Mygod/VPNHotspot/files/3162546/vpnhotspot-1743180811612732424.log)

**Comment by Mygod** [comment]
Turn on service before exporting debug info.

**Comment by yingshaoxo** [comment]
OK

By the way, I can't visit the normal Internet either after connected to my hotspot.

But If I use the `Repeater` function, everything is fine.


[vpnhotspot-2221571592856486473.log](https://github.com/Mygod/VPNHotspot/files/3163219/vpnhotspot-2221571592856486473.log)

**Comment by Mygod** [comment]
Disable hardware tethering accel.

**Comment by yingshaoxo** [comment]
Thank you sir.
