### ISSUE TITLE
Error installing from fdroid - Error -15

### ISSUE THREAD

**Issue by godfuture** [Mygod/VPNHotspot#103]
I wanted to install the update 2.4.0 over 2.3.0 in fdroid app store. But the installation quits due to "Error -15: the new package failed because it has specified that it is a test-only package and the caller has not supplied the `{@link #INSTALL_ALLOW_TEST}` flag.

What to do?

**Comment by Mygod** [comment]
This is called by the fact that I tagged the wrong commit for release v2.4.0. Other releases should work fine once F-droid manages to build them.

**Comment by Mygod** [comment]
Try v2.4.4.
