### ISSUE TITLE
Laptop can't detect Repeater but all my other devices can

### ISSUE THREAD

**Issue by chevyfollowtooclose** [Mygod/VPNHotspot#106]
I have a Win10 laptop that can't detect the repeater network.  I have tried resetting network adapter and fresh Win10 install.  All phones and printers can detect the repeater network.  

I use two vpns and have tried both.  Would any info help with this?

**Comment by Mygod** [comment]
Set repeater to 2.4GHz channel.

**Comment by chevyfollowtooclose** [comment]
Thanks I'll send you a 5* review on the app store.
