### ISSUE TITLE
Add support for systemless root mode

### ISSUE THREAD

**Issue by gagabs** [Mygod/VPNHotspot#112]
Given https://github.com/Mygod/VPNHotspot/issues/8#issuecomment-448529512, the app now breaks the OTA update feature of systemless root solutions like [Magisk](https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445).

I've tested this myself, and the app does write to system partition even without using the repeater feature. The file written is related to the repeater feature in the above issue.

So this issue is a feature request to create a option that enforce a systemless operation of the app and disable features that do not are possible without it.

**Comment by Mygod** [comment]
> [...‘systemless root’ was used and named as such because it doesn’t modify the files in the /system partition.](https://appuals.com/root-android-systemless-mode/)

This app is (still) not responsible for breaking your systemless root.

**Comment by Mygod** [comment]
Updated https://github.com/Mygod/VPNHotspot/issues/8#issuecomment-448529512 to clear up confusion.
