### ISSUE TITLE
VPN kill switch feature

### ISSUE THREAD

**Issue by jegidawun** [Mygod/VPNHotspot#119]
A VPN Kill-Switch is a critical piece of a VPN security solution.
We need this feature to make sure that our true IP address is never exposed online in the event of a dropped VPN connection.
Must be an option to disable internet connection in case of vpn connection is disconnected or upstream is changed.

Tags:
VPN Kill-Switch, Internet Kill Switch

**Comment by Mygod** [comment]
Okay dropped VPN connection makes sense. Expect `fallback upstream interface` to come back in v2.5.

Meanwhile use v2.1.4 for now.

**Comment by M86xKC** [comment]
What do I need to set the fallback upstream network to disable internet access (in the client) when VPN is not working ?

**Comment by Mygod** [comment]
@M86xKC See latest README.

**Comment by Mygod** [comment]
Please try [v2.5.0-beta](https://github.com/Mygod/VPNHotspot/releases/tag/v2.5.0).

**Comment by M86xKC** [comment]
Oh nice!
Can you please update the README to include build instructions ?

**Comment by Mygod** [comment]
> https://github.com/Mygod/VPNHotspot/issues/119#issuecomment-511693111
> Oh nice!
> Can you please update the README to include build instructions ?

Build with Android Studio.

**Comment by M86xKC** [comment]
I tried the latest version 2.5.1.
I tried setting the fallback upstream network to none, but still I had connection to the non-vpn network after turning vpn off

**Comment by Mygod** [comment]
@M86xKC While it is not working, export debug information and I will take a look.

**Comment by M86xKC** [comment]
Can you please be more specific, while what is not working, vpn ?

**Comment by Mygod** [comment]
Right after you reproduce this issue would be fine.

**Comment by M86xKC** [comment]
Nvm, it seems that I did not restart the app after choosing none or something like that! It is working perfectly fine.

**Comment by Mygod** [comment]
Yeah you need to tap "reapply" for your changes to apply.
