### ISSUE TITLE
Clients info updates re-draw on every second

### ISSUE THREAD

**Issue by M86xKC** [Mygod/VPNHotspot#120]
After updating from an old version (2.1.4) to 2.4.6. I get a strange bug, where the client's screen re-draws every second to change the speeds and the connection status. So it becomes tricky to select a device to view stats or block by

https://imgur.com/a/qdSq1fb

**Comment by Mygod** [comment]
I cannot reproduce this. Which network status monitor mode are you using?

**Comment by M86xKC** [comment]
Default (poll)

**Comment by Mygod** [comment]
Please export debug information after this happens.

Also you can try if netlink monitor works for you.

**Comment by M86xKC** [comment]
I tried netlink monitor and it is perfect fine!

**Comment by Mygod** [comment]
Okay. I can seem to reproduce this now.

**Comment by M86xKC** [comment]
Maybe consider making netlink the default option, it works perfectly fine for me! Also for battery saving benefits

**Comment by Mygod** [comment]
@M86xKC Default options are designed to maximize compatibility since most people won't bother to figure out what's wrong. You should always read manual to figure out your best settings.
