### ISSUE TITLE
no internet when distributing vpn

### ISSUE THREAD

**Issue by whakru** [Mygod/VPNHotspot#121]
if I turn on vpn distribution, the client after connecting does not have access to the Internet.
Pocophone f1. miui 10.3.5
noticed that the IP address is different with the subnet.  But even if you manually set the ip and dns settings in the client, there is still no Internet.
P.s. I use a translator, sorry if the translation is not correct.

**Comment by Mygod** [comment]
Export debug information while the service is active.

**Comment by whakru** [comment]
it is very strange today why the distribution point changed the name to wlan1 and the Internet works!  wow ... (it used to be wlan0 and it didn't work.)

**Comment by whakru** [comment]
https://drive.google.com/file/d/1wOUlAGfmcI2lmDaFXxSw0fqfDoGGCJSp/view?usp=drivesdk

**Comment by whakru** [comment]
> Export debug information while the service is active.
I hope you did not see the message that I deleted.  there I accidentally created a wifi repeater (because of this, it was called wlan1) ... how the wifi repeater works with vpn.  but through the mobile network is not.
logs mobile network I added above.

**Comment by Mygod** [comment]
Disable hardware tethering acceleration.
