### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by FuzzyNutz** [Mygod/VPNHotspot#123]
Sorry to ask this here can’t find support anywhere else, this may be a really dumb question but I can’t find where to change / what is the password to connect in repeater mode.

**Comment by FuzzyNutz** [comment]
Cool thanx man! Lol I was just about to delete my question kuz I just saw it. Thanx again man! Can close this 😀

**Comment by FuzzyNutz** [comment]
@Mygod one more question the repeater can share WiFi to hotspot right? But when I connect I get ‘no internet connection’ [like this](https://imgur.com/a/WUfBpu4``)

**Comment by Mygod** [comment]
Root required.

**Comment by FuzzyNutz** [comment]
Yea it’s rooted, galaxy s5

**Comment by Mygod** [comment]
Export debug information.

**Comment by Mygod** [comment]
Export while service is active.

**Comment by FuzzyNutz** [comment]
@Mygod 
[internet active]([vpnhotspot-2071462094.log](https://github.com/Mygod/VPNHotspot/files/3494552/vpnhotspot-2071462094.log))
