### ISSUE TITLE
[Documentation] Shell commands used onConnect and onDisconnect

### ISSUE THREAD

**Issue by dmccue** [Mygod/VPNHotspot#124]
I've been digging through the source code trying to extract the root shell commands used to setup and destroy the iptables rules and i'm stumped with the onConnect.  Is there any way to view all commands run via, for example, logging?
(reason why is that i'd like to setup a tasker run command as root task after VPN has connected)

*onConnect:*
https://github.com/Mygod/VPNHotspot/blob/ee52b58c46e2462896ebfaa9733e7b8c67661b35/mobile/src/main/java/be/mygod/vpnhotspot/net/Routing.kt#L68
```
echo 1 >/proc/sys/net/ipv6/conf/wlan1/disable_ipv6
[TODO]
```

*onDisconnect:*
https://github.com/Mygod/VPNHotspot/blob/ee52b58c46e2462896ebfaa9733e7b8c67661b35/mobile/src/main/java/be/mygod/vpnhotspot/net/Routing.kt#L50
```
echo 0 >/proc/sys/net/ipv6/conf/wlan1/disable_ipv6
iptables -w 1 -t nat -F PREROUTING
while iptables -w 1 -D FORWARD -j vpnhotspot_fwd; do done
iptables -w 1 -F vpnhotspot_fwd
iptables -w 1 -X vpnhotspot_fwd
iptables -w 1 -F vpnhotspot_acl
iptables -w 1 -X vpnhotspot_acl
while iptables -w 1 -t nat -D POSTROUTING -j vpnhotspot_masquerade; do done
iptables -w 1 -t nat -F vpnhotspot_masquerade
iptables -w 1 -t nat -X vpnhotspot_masquerade
while ip rule del priority 17700; do done
while ip rule del priority 17800; do done
while ip rule del priority 17900; do done
```

**Comment by Mygod** [comment]
This app extensively integrates with Android API. You should use this app instead.
