### ISSUE TITLE
Cannot connect to devices though app says "reachable"

### ISSUE THREAD

**Issue by jlamoure** [Mygod/VPNHotspot#125]
Android 7.1.2
Moto G Play
OpenVPN for Android.

I tried this app because not only was I not able to access internet on attached devices when both VPN and hotspot are turned on, but more importantly to me, I cannot make a local connection from phone to device, be it HTTP, SSH, or syncthing.

In wlan0 mode, internet does not connect on the attached device and I cannot connect locally either, though it is connected and is labelled "reachable."

**Comment by Mygod** [comment]
Sounds like a system bug. Report to your ROM developer instead.
