### ISSUE TITLE
startLocalOnlyHotspot closed by system

### ISSUE THREAD

**Issue by iadeelzafar** [Mygod/VPNHotspot#126]
I'm using [startLocalOnlyHotspot](https://developer.android.com/reference/android/net/wifi/WifiManager#startLocalOnlyHotspot(android.net.wifi.WifiManager.LocalOnlyHotspotCallback,%20android.os.Handler)) in a project of mine that is similar to this project.

Hotspot is turned off by the system after a few minutes and I see this in the Logs.

```2019-09-05 11:12:42.087 759-3392/? I/WifiService: stopLocalOnlyHotspot uid=10184 pid=16049```

Digging more, here's what this method that is being called by the system itself does.

```
 /**
     *  Method used to inform WifiService that the LocalOnlyHotspot is no longer needed.  This
     *  method is used by WifiManager to release LocalOnlyHotspotReservations held by calling
     *  applications and removes the internal tracking for the hotspot request.  When all requesting
     *  applications are finished using the hotspot, it will be stopped and WiFi will return to the
     *  previous operational mode.
     *
     *  This method should not be called by applications.  Instead, they should call the close()
     *  method on their LocalOnlyHotspotReservation.
     */
    private void stopLocalOnlyHotspot() {
```

**So, my question is how the system decides that LocalOnlyHotspot is no longer needed? My other devices are connected to the local hotspot and a server is hosted on it. But it still gets turned off.** 

Please enlighten me.

Thanks!

**Comment by Mygod** [comment]
Notes that `LocalOnlyHotspotReservation implements AutoCloseable`. If you left the instance hanging, your hotspot will be closed when the LOHReservation instance get GC-ed.

Meanwhile, I might check out `WifiManager.cancelLocalOnlyHotspotRequest` sometime to fix some ANRs.

**Comment by iadeelzafar** [comment]
@Mygod 
I use `hotspotReservation.close()` everytime after the hotspot is stopped. If that's what you meant.  
[For reference](https://github.com/iadeelzafar/kiwix-android/blob/011bb57018be7f80dcd78617e5f204e567dc1d0e/app/src/main/java/org/kiwix/kiwixmobile/wifi_hotspot/WifiHotspotManager.java#L67). 
Correct me if I'm wrong.

**Comment by macgills** [comment]
Hi, I'm a contributor on the project iadeelzafar is contributing to, the reference should not be getting GC-ed it is on a Service that is definitely still running

**Comment by Mygod** [comment]
Did you turn off `Turn off hotspot automatically` in system settings? I just ran a hotspot with that setting off for half an hour with no problem.
