### ISSUE TITLE
When the current connected device > 8, it is impossible to join the new device.

### ISSUE THREAD

**Issue by qwe7002** [Mygod/VPNHotspot#127]
When the current connected device is equal to 8, it is impossible to join the new device.

I searched for the answer in stackoverflow. Some people said that 20 Android devices using WIFI P2P function to connect should be no problem.

https://stackoverflow.com/questions/36820448/how-many-devices-can-i-connect-with-wi-fi-p2p

**Comment by qwe7002** [comment]
The system I am currently using is Lineageos16 and the current device is Oneplus 3T.

**Comment by Mygod** [comment]
It depends on your Wi-Fi driver I believe. I have not tried that many devices but you might try different ROMs.

**Comment by qwe7002** [comment]
After discussion, we believe that the problem should be limited by Qualcomm's baseband.  It doesn't seem to be solved by changing the ROM.  Thank you for your answer.

On Sep 16, 2019, at 03:36, Mygod <notifications@github.com<mailto:notifications@github.com>> wrote:


It depends on your Wi-Fi driver I believe. I have not tried that many devices but you might try different ROMs.

**Comment by Mygod** [comment]
Any source of this? I am curious because I don't think the wireless hardware has builtin limitations regarding the maximum number of clients.

**Comment by qwe7002** [comment]
sorry, no, just an embedded engineer saying so. I have not searched for any discussion or documentation about this.Also, I asked a friend who works at a device manufacturer, and he said that there is no such restriction.

On 17 Sep 2019, at 00:07, Mygod <notifications@github.com<mailto:notifications@github.com>> wrote:


Any source of this? I am curious because I don't think the wireless hardware has builtin limitations regarding the maximum number of clients.

**Comment by Mygod** [comment]
On Windows, I did find similar restriction by running `netsh wlan show wirelesscapabilities`:

```
    P2P Max Mobile AP Clients                   : 10
```

I would be surprised if this restriction is something baked into the hardware.

**Comment by Mygod** [comment]
You should be able to see max supported clients (e.g. 32) using app v2.10.4+ on Android 11+ for Wi-Fi hotspot now (#168). No similar functionalities for Wi-Fi direct, however. Closing this issue as vendor-specific.
