### ISSUE TITLE
[Feature] Add custom filtering of dns requests

### ISSUE THREAD

**Issue by wizard1989** [Mygod/VPNHotspot#129]
I have Dnscrypt proxy installed on my phone. With Afwall+ I added rules to forward all requests destined to port 53 to any ip except 9.9.9.9 to local 127.0.0.1:5354:

When starting Afwall+:
iptables -t nat -A OUTPUT -p tcp ! -d 9.9.9.9 --dport 53 -j DNAT --to-destination 127.0.0.1:5354
iptables -t nat -A OUTPUT -p udp ! -d 9.9.9.9 --dport 53 -j DNAT --to-destination 127.0.0.1:5354

When stopping Afwall+:
iptables -t nat -D OUTPUT -p tcp ! -d 9.9.9.9 --dport 53 -j DNAT --to-destination 127.0.0.1:5354
iptables -t nat -D OUTPUT -p udp ! -d 9.9.9.9 --dport 53 -j DNAT --to-destination 127.0.0.1:5354

VPNHotspot app routes all traffic to the OpenVPN tunnel.

It would be great to add function to route dns requests to the dnscrypt proxy at 127.0.0.1.

**Comment by Mygod** [comment]
I think this feature should be reported to OpenVPN instead but feel free to fork and tweak this app.
