### ISSUE TITLE
无法上网

### ISSUE THREAD

**Issue by wode2016501** [Mygod/VPNHotspot#134]
连接上 无法上网 root也无法解决

**Comment by Mygod** [comment]
Debug information.

**Comment by wode2016501** [comment]
路由器是 192.168.1.1
热点是可以开启的 
p2p0: 192.168.49.1  
wlan0: 192.168.1.125都开启

用另外一个手机连接ip 是192.168.49.35
问题是 192.168.49.35无法上网 ping 192.168.1.1也不通

**Comment by wode2016501** [comment]
路由器是 192.168.1.1
热点是可以开启的 
p2p0: 192.168.49.1  
wlan0: 192.168.1.125都开启

用另外一个手机连接ip 是192.168.49.35
问题是 192.168.49.35无法上网 ping 192.168.1.1也不通
