### ISSUE TITLE
Troubles connecting devices to the wifi repeater

### ISSUE THREAD

**Issue by quesyal** [Mygod/VPNHotspot#141]
Hi, i tried changing every kind of settings in app also changed VPN and tried without it, but nothing clients hardly get the IP address from the hotspost and the rare times they get connected internet is not working, I'm on android 10, any suggestion?
[vpnhotspot-5018270676646644104.log](https://github.com/Mygod/VPNHotspot/files/4097478/vpnhotspot-5018270676646644104.log)

**Comment by Mygod** [comment]
Please export debug information while the service is still active.

**Comment by quesyal** [comment]
Service active, VPN connected, internet available but client can't connect
[vpnhotspot-4581161269709827069.log](https://github.com/Mygod/VPNHotspot/files/4098761/vpnhotspot-4581161269709827069.log)

**Comment by Mygod** [comment]
In your log I found `E dnsmasq : failed to bind DHCP server socket: Address already in use`. Please ensure your tethering is working correctly with VPN without using this app.

**Comment by quesyal** [comment]
System tethering is working with vpn, just tried, but I can't get this WiFi repeater working on the app

**Comment by Mygod** [comment]
It seems like a bug of your ROM. Please report to your ROM developer (dnsmasq fails to start up for p2p).

**Comment by quesyal** [comment]
OK thanks
