### ISSUE TITLE
Since ver 2.5 the wifi hotspot devices can not access to RNDIS usb LAN devices.

### ISSUE THREAD

**Issue by fordiy** [Mygod/VPNHotspot#142]
The usb RNDIS devices in the 192.168.42.x can not been accessed by ap0 wifi hotsport devices from 192.168.43.x

This was no issues 2.4.6, But later version were all failed. Two sub-lans should be routed and can be accessable.

**Comment by Mygod** [comment]
Please try 1507050eeabd9e9e48c6f47c978fa3cf32c0201b.

**Comment by Mygod** [comment]
Try [this apk](https://mygod.be/resources/userscloud/tr62j43lp6cj).

**Comment by Mygod** [comment]
Hi, I will be releasing a new release soon. Let me know if this apk does not work for you.

**Comment by Yubyf** [comment]
@Mygod Hi, I have the same bug in 2.9.1, and it's resovlered in https://github.com/Mygod/VPNHotspot/issues/142#issuecomment-578595999. Please merge it to the release app.

**Comment by Yubyf** [comment]
> @Yubyf 2.9.1 is working fine for me.

There's no traffic on my OnePlus 5 in OxygenOS 10 open beta 35 while using 2.9.1. But it's resolved on this version, I will try to export logs few hours later.

**Comment by Yubyf** [comment]
@Mygod This is the log of my OnePlus5. 
[vpnhotspot-2397427993206566242.log](https://github.com/Mygod/VPNHotspot/files/4769042/vpnhotspot-2397427993206566242.log)

**Comment by Mygod** [comment]
There is no routing related change from the build above (v2.8.0) until v2.9.1. Also you only have a single downstream interface in your log.

**Comment by Yubyf** [comment]
> There is no routing related change from the build above (v2.8.0) until v2.9.1. Also you only have a single downstream interface in your log.

Okay, Maybe it’s just not compatible with my phone.
