### ISSUE TITLE
what is pin of "一键加密"

### ISSUE THREAD

**Issue by Generalize** [Mygod/VPNHotspot#143]
i use wifi hotspot and usb tethering dns both broken, so i try repeater i can't set pin i click "一键加密" do not know pin my win10 pc can't connected i want to get pin of auto generated
![Screenshot_2020-01-26-18-11-48-137_be mygod vpnhotspot](https://user-images.githubusercontent.com/26076140/73133726-9db64a00-4067-11ea-80e5-0a48952af745.png)

**Comment by Generalize** [comment]
my phone is android 7.1.1

**Comment by Mygod** [comment]
You should specify it yourself.

**Comment by Mygod** [comment]
For PBC mode, no pin code is required.
