### ISSUE TITLE
Enable DHCP workaround not working

### ISSUE THREAD

**Issue by onk2onk** [Mygod/VPNHotspot#144]
Client wasn't able to obtain an IP address, I tried using "Enable DHCP workaround", but that didn't help. I looked at the log file (attached here):

`01-29 16:15:26.885  5942  5942 D su      : su invoked.  `
`01-29 16:15:26.886  5942  5942 D su      : starting daemon client 10080 10080  `
`01-29 16:15:26.886  5942  5942 E su      : connect failed with 2: No such file or directory  `
`01-29 16:15:26.904  2024  2042 W DhcpWorkaround$enable:  com.topjohnwu.superuser.NoShellException: Unable to create a shell!`

I have su file in the following places:

`/system/bin/su`
`/system/xbin/su`

Phone: Galaxy Nexus (GT-I9250/Maguro)
OS: LineageOS 13.0 (Android 6.0.1)

I would appreciate any help.
[vpnhotspot--1364071184.log](https://github.com/Mygod/VPNHotspot/files/4144315/vpnhotspot--1364071184.log)

**Comment by Mygod** [comment]
`su      : connect failed with 2: No such file or directory`

Your su is broken.

**Comment by ppvan** [comment]
@Mygod i got the same issue on android 6.0 (Le_X626). Client still can not get the IP. Is android 6.0.0 still supported?

If i connect to wifi first than turn on VPN then it seems to works (But doing so with every client is a pain).
I would appreciate any help.

[vpnhotspot-1756354619.log](https://github.com/Mygod/VPNHotspot/files/12386186/vpnhotspot-1756354619.log)
