### ISSUE TITLE
Mtu problem

### ISSUE THREAD

**Issue by quesyal** [Mygod/VPNHotspot#146]
I use this app to connect my console to a vpn, but i dont know why sometimes it doesnt work, it says " There is a problem with MTU", idk why usually is working really good then again this problem, is there anything i can do about that?
[vpnhotspot-8861473291881943106.log](https://github.com/Mygod/VPNHotspot/files/4195249/vpnhotspot-8861473291881943106.log)

**Comment by Mygod** [comment]
I don't think so.
