### ISSUE TITLE
Unable to build freedom 221

### ISSUE THREAD

**Issue by licaon-kter** [Mygod/VPNHotspot#149]
...after removing all non-FOSS entries in build.gradle (GMS/Firebase/Crashlytics/OSS-license)

```
Found 6.1.1 via distributionUrl
Running /home/strech/versions/6.1.1/bin/gradle assembleFreedom

> Configure project :mobile
WARNING: The option setting 'android.enableR8.fullMode=true' is experimental.
The current default is 'false'.

> Task :mobile:processFreedomDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mobile:processFreedomDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/strech/fdroiddata/build/be.mygod.vpnhotspot/mobile/src/main/res/xml/pref_settings.xml:91: AAPT: error: resource string/preferences_license_summary (aka be.mygod.vpnhotspot:string/preferences_license_summary) not found.

     /home/strech/fdroiddata/build/be.mygod.vpnhotspot/mobile/src/main/res/xml/pref_settings.xml:91: AAPT: error: resource string/oss_license_title (aka be.mygod.vpnhotspot:string/oss_license_title) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
14 actionable tasks: 1 executed, 13 up-to-date
```

**Comment by licaon-kter** [comment]
That's...sad...

**Comment by Mygod** [comment]
Please instead report to Google that their Firebase/OSS-license is not free. I already see that they are making some efforts towards making these libraries free (see [firebase-android-sdk@GitHub](https://github.com/firebase/firebase-android-sdk), 3cee5a4782068b37b442254e7fc6cd243091680c) so there are no reasons that they would not push it further. On the other hand, I do not wish to maintain a second variant that I do not use.

**Comment by licaon-kter** [comment]
Not sure they forced you to use this, but thanks for the pointer. :))

**Comment by Mygod** [comment]
Not sure what you mean. I was not forced to use their open sourced crashlytics but I would say I was forced to maintain an F-droid variant after merging #42. The variant changed too many things and since I do not test it it has broken several times. In the end I decided that maintaining it is just not worth my time.

**Comment by licaon-kter** [comment]
Saw the commit message too and wondered, why do you think it's open-source when it depends on closed source Google Services and/or Firebase?

**Comment by fazlerabbi37** [comment]
> I was not forced to use their open sourced crashlytics but I would say I was forced to maintain an F-droid variant after merging #42.

IMO, you are not forced to do either. You are not force to maintain an F-droid variant but after using the app regularly for a bit more than a year, I can say this: It is a great FOSS app and like me many depends on F-Droid to get FOSS apps with auto update and have no way to use it via Google Play Store, so we would really appreciate if you consider keeping the app updated in the F-Droid repo as well.

At the same time you are not forced to use Firebase crashlytics as there are many FOSS variant that respects user privacy and consent. I believe F-Droid client usages [acra](https://github.com/ACRA/acra) (@licaon-kter can give better input here). Maybe you can use one of those FOSS crashlytics and let use the users keep using this app. :blush:

**Comment by licaon-kter** [comment]
Or Bugsnag

**Comment by Mygod** [comment]
If you cannot use Google play store, these are the alternative ways that I officially distribute the binary:

* Watch for release on GitHub;
* XDA: https://labs.xda-developers.com/store/app/be.mygod.vpnhotspot
* Firebase beta: https://appdistribution.firebase.dev/i/FUCPGdzm

If you are against all kinds of analytics or need utmost privacy, you should be thankful that I made the app open source, clone the repo and make the changes yourself. (you should also probably not use F-Droid because why would you trust them)

**Comment by Mygod** [comment]
If one more comment suggests any way that I can waste more time on this I am going to lock the topic. Thanks.
