### ISSUE TITLE
Support for user-defined/custom interface (WireGuard)

### ISSUE THREAD

**Issue by ViRb3** [Mygod/VPNHotspot#15]
Do you think this would be possible? As far as I understood the code, you forward traffic via iptables, so simply using the interface defined by WireGuard should do the trick. Currently, the official Android app creates an interface based on the profile file name you supply. Thanks!

**Comment by Mygod** [comment]
As long as it's the VPN interface used by Android system, this app will pick it up and use it.

**Comment by ViRb3** [comment]
Unfortunately, it is not the VPN interface, but rather a separate one. As I mentioned, its name depends on the profile file name, and therefore would be impossible to detect. I assume user-defined interface name would solve this issue ideally.

**Comment by Mygod** [comment]
Huh. [Somebody here told me that this app actually works with wireguard for him](https://labs.xda-developers.com/store/app/be.mygod.vpnhotspot). I have never used wireguard but are you sure this is necessary?

**Comment by ViRb3** [comment]
I believe that it worked for them because they used the user-mode implementation (Android VPN mode). I am using the original, kernel implementation, which for obvious reasons doesn't follow Android's VPN mechanisms. WireGuard is meant to be used in kernel mode to deliver all of its performance goodies and it'll be great if we can see support for that.

**Comment by Mygod** [comment]
Okay. This isn't going to be a trivial amount of work as it may sound like because routing has to be resetup every time the interface go up/down. But I'll consider implementing it before next release.

P.S. You said "we", is your organization or something using this app? :smile:

**Comment by ViRb3** [comment]
I am willing to work with you on this, since I can provide testing and I know Kotlin. If there is any place I can IM you so we coordinate better, please let me know. I have sent you an e-mail in the meanwhile.

**Comment by ViRb3** [comment]
Also I meant "we" as in all the people that use this app :)

**Comment by ViRb3** [comment]
It turns out that just yesterday an update for WireGuard was released that utilizes Android's VPN interface. I can confirm that VPNHotspot works now!

**Comment by Mygod** [comment]
Ok cool. Less stuff to do for me. 😄

**Comment by ViRb3** [comment]
My bad, I switched my phone's kernel and since the new one had no WireGuard kernel support, it defaulted to usermode, thus using Android's VPN interface. I can confirm that VPNHotspot does not work with WireGuard's kernel mode.

**Comment by darkii321** [comment]
Folder C:\Users\work\Desktop\VPNHotspot\mobile\build\generated\source\kaptKotlin\debug

Folder C:\Users\work\Desktop\VPNHotspot\mobile\build\generated\source\kaptKotlin\release

3rd-party Gradle plug-ins may be the cause

**Comment by Mygod** [comment]
Please give [1.3.1-alpha](https://github.com/Mygod/VPNHotspot/releases/tag/1.3.1) a go and see how that goes.
