### ISSUE TITLE
Some devices cannot use hotspot VPN

### ISSUE THREAD

**Issue by Falld0wn18** [Mygod/VPNHotspot#152]
[Same problem](https://github.com/Mygod/VPNHotspot/issues/78), but when I try to connect other devices (iPhone) to the hotspot, VPN works fine. What I see from the connected devices is that 3ds only uploads but not downloads. Is there a way to solve the problem that Nintendo 2 / 3ds cannot connect to the network?

[vpnhotspot-3342923755842659906.log](https://github.com/Mygod/VPNHotspot/files/4311946/vpnhotspot-3342923755842659906.log)
I have modified some MAC addresses to:33:33:33:33:33:33 and aa:aa:aa:aa:aa:aa. 33:33:33:33:33:33 is my Nintendo 2ds, aa:aa:aa:aa:aa:aa is my mobilePhone.

Hope to reply~ 😀

**Comment by Mygod** [comment]
```
iptables -nvx -L vpnhotspot_acl
Chain vpnhotspot_acl (2 references)
    pkts      bytes target     prot opt in     out     source               destination         
      16     3583 ACCEPT     all  --  *      wlan0   0.0.0.0/0            192.168.43.135      
      77     7593 ACCEPT     all  --  wlan0  *       192.168.43.135       0.0.0.0/0           
```

It seems like there is traffic in both directions. Try connecting some other devices and see if it works.

**Comment by Falld0wn18** [comment]
Hello, other devices (like iPhone or Macbook) can be used normally. I have tried resetting the settings and regenerating the logs and screen recordings of the phone, and I can send them to your email if needed.😊

**Comment by Falld0wn18** [comment]
Hello, I just tried to use Nintendo 2ds browser to access the website. I found that I can also use VPN hotspots, so the problem now is that in some 2ds games (like Monster Hunter), I ca n’t use VPN hotspots to connect with my teammates. . Is there a way to debug this problem?

**Comment by Mygod** [comment]
Good. In that case, try disabling VPN (use this app but do not enable VPN). If this works, try other VPNs.

**Comment by Falld0wn18** [comment]
I tried several usage scenarios:

|Scenes|Browser on 2ds|Download DLC in game on 2ds|Online in game on 2ds|Browser on other devices|
|----|----|----|----|----|
|Hotspot **on**, VPNHotspot **off**(wlan0 **off**),VPN1 **off**|√|√|√(High latency)|√|
|Hotspot **on**, VPNHotspot **on**(wlan0 **on**),VPN1 **off**|√|√|√(High latency)|√|
|Hotspot **on**, VPNHotspot **on**(wlan0 **on**),VPN1 **on**|√|√|×|√|
|Hotspot **on**, VPNHotspot **on**(wlan0 **on**),VPN2 **on**|√|√|√(No long test)|√|

**Mark:**
VPN1: Shadowsocks, ShadowsocksR, Clash etc(These app need to add server nodes by yourself).
VPN2: Randomly downloaded app on Google Play Store(Application comes with server nodes).

Looks like there is a problem with the VPN1? 😓

**Comment by Mygod** [comment]
Make sure your VPN1 has UDP support.

**Comment by Falld0wn18** [comment]
Hello, maybe because these clients have "UDP forwarding" turned off by default. I found the "UDP forwarding" switch in the settings of VPN1 (Shadowsocks / ShadowsocksR). After opening, I found that I can connect normally. The problem is probably resolved. . Glad to hear from you and appreciate your help.👍
