### ISSUE TITLE
internal error for short custom SSID repeater after Android 10 March 2020 security patch

### ISSUE THREAD

**Issue by Mygod** [Mygod/VPNHotspot#153]
Shit.

**Comment by SykkNyzz** [comment]
Only thing I can offer is that creating a password works in PDAnet (Android 10) Idunno if that helps you towards your goal.

**Comment by Mygod** [comment]
It's only going to work if your SSID starts with `DIRECT-xy`, no?

**Comment by SykkNyzz** [comment]
![Screenshot_20200315-174214_1](https://user-images.githubusercontent.com/33635415/76712270-125f4980-66e5-11ea-882e-e89df75b013a.jpg)
Apparently that seems to be the case.

**Comment by SykkNyzz** [comment]
![Screenshot_20200315-175038](https://user-images.githubusercontent.com/33635415/76712314-8dc0fb00-66e5-11ea-8ec4-bba085d327bb.jpg)
Well, that's good to know.

**Comment by Mygod** [comment]
It seems like actually SSID has to be at least 9 characters long instead of having to conform to "DIRECT-xy". This is the commit that broke it: https://android.googlesource.com/platform/frameworks/opt/net/wifi/+/221cd9e93b94def60aa4a5adbdd3bfa91502bdc8%5E%21/

**Comment by Mygod** [comment]
A patch reverting the change has been submitted: https://android-review.googlesource.com/c/platform/frameworks/opt/net/wifi/+/1261161

Y'all are welcome to go there and +1.

**Comment by Mygod** [comment]
Please also go star this issue at Google: https://issuetracker.google.com/issues/152250230

The best way to fix this is to get Google to revert their changes.

**Comment by Mygod** [comment]
If you are using Android 10 March 2020 security patch or newer, in the next update, you will see an option to turn off "Repeater safe mode", this will enable the "legacy behavior" that you would get on Android 9- but short SSIDs work according to my test.

Turning it off means all the caveats from the legacy behavior; see also: https://github.com/Mygod/VPNHotspot/issues/8#issuecomment-448529512, #31.
