### ISSUE TITLE
App freezes on S5 Mini

### ISSUE THREAD

**Issue by eogut** [Mygod/VPNHotspot#154]
Hi, I'm running an S5 Mini on LineageOS 16 (Android 9) with Magisk root and microG. Sadly, when starting the repeater, the app freezes. Sometimes it says P2P failed, WiFi Direct is disabled. Pressing "enable" is of no help.

Thank you for your work. I'd like to get my old S5 Mini running as a WiFi repeater.

**Comment by Mygod** [comment]
Root required.

**Comment by eogut** [comment]
My phone is rooted.

Am 30. März 2020 15:59:53 schrieb Mygod <notifications@github.com>:
