### ISSUE TITLE
How to use it on my MI phone?

### ISSUE THREAD

**Issue by DarthMikuH** [Mygod/VPNHotspot#155]
![Screenshot_2020-04-07-23-26-31-285_com android settings](https://user-images.githubusercontent.com/62818311/78687951-48c86700-7927-11ea-9abe-d573e9109a14.png)
I can't use it

**Comment by bluehomewu** [comment]
You need root.
And don't used Chinese in Github

**Comment by DarthMikuH** [comment]
I've allowed it to change my system settings!
Can the app connect VPN to.my phone?



---Original---

**Comment by DarthMikuH** [comment]
> You need root.
> And don't used Chinese in Github

Thanks
