### ISSUE TITLE
[Feature] iptables TTL change

### ISSUE THREAD

**Issue by Raslin777** [Mygod/VPNHotspot#156]
Is it possible to set the TTL of all outbound packets to be 24 using TTL --ttl-set xxx

The reason for this is that some service providers look at the TTL to monitor for hotspot traffic. Android is set for TTL 24 by default. If traffic is any other number then it is counted as hotspot traffic. If we cannot change the TTL via iptables then we need to change all connecting devices TTL to 25. 

Please let me know if this is possible and close this if not possible. Thank you.

**Comment by Mygod** [comment]
Why not use a second app? It should work with this.

**Comment by Raslin777** [comment]
I think it needs to be done while routing the traffic or you have to set the TTL on each device connected to the VPN Hotspot

**Comment by Mygod** [comment]
I think you are wrong.

**Comment by Mygod** [comment]
Just for future reference, please see #139 for the recommended way to bypass tethering without using a full VPN. TTL tweaking is hacky and might not always work.

**Comment by Raslin777** [comment]
What I was referring to was from this post. 
https://www.reddit.com/r/hacking/comments/54a7dd/bypassing_tmobiles_tethering_data_capthrottling/
Without it:
Most phones have a TTL of 64. This means we need our tethered device's TTL to be 65, so that when it is decremented by passing through the phone it has the identical value of 64 and cannot be differentiated.
From what I tested to bypass tether detection I need, vpn(obfuscate data/headers...), ipv4 apn, and all devices ttl to 65.
If not it will see it as tether data. 

I guess what I am asking is vpn hotspot making sure all packets outbound are TTL 64? Or do I need to find another way?

**Comment by Raslin777** [comment]
I think this won't be possible on most phones as they do not support ttl-set in the kernel for iptables. 

net/netfilter/xt_HL.ko
https://m.habr.com/en/post/238625/

**Comment by xDragonZ** [comment]
Can we compile the xt_HL.ko and load into the kernel using root?

**Comment by Mygod** [comment]
https://github.com/Mygod/VPNHotspot/issues/156#issuecomment-618542754
