### ISSUE TITLE
please run without the 'playstore tail'

### ISSUE THREAD

**Issue by magixtruct** [Mygod/VPNHotspot#161]
there's some really big issue for me, samsung device, android 8.1.0:
everytime when I run vpnhotspot, the playstore in-app service lets the playstore app run together with it & it can't be stopped by greenify like when I'm inside other apps.
I have to go outside vpnhotspot + stop playstore min 3 times. only then it closes.
when I go into vpnhotspot app again, playstore starts again + no way to stop it.
I don't experience this in other apps, so I thought it must be a bug. I'd be very happy, if you'd fix it, cause it doesn't feel very private like this & I need the memory which playstore sucks up this way, for vpn tethering.
additionally, vpnhotspot seems to be so woven with the playstore service, that vpnhotspot app closes, nearly everytime the playstore updates its support libraries.
I will try to disable analytics & co for vpnhotspot. maybe I can get around my problem.
don't know if I'm the only one struggling with this. but it'd be better if fixed, I think.
from the closed issues I've gathered, that you don't plan to push vpnhotspot app as foss on fdroid, which I personally find very sad, cause that could be the solution to such problems.
on the other hand, I understand that you use firebase analytics, cause in this manner you can monitor your app on different devices & ensure its functionaltity. and it never really bothered me, exepting the above mentioned issues.

**Comment by magixtruct** [comment]
oh, that's sad. maybe I didn't make myself clear.
I don't want to force you to put vpnhotspot app on fdroid.
I just ask if I can use it without being disrupted by playstore libraries.
can you just consider this in the next update?

**Comment by Mygod** [comment]
No.
