### ISSUE TITLE
disruption-free vpn tethering

### ISSUE THREAD

**Issue by magixtruct** [Mygod/VPNHotspot#162]
I'm using native android wifi hotspot with wlan0 to share my vpn connection on android with other devices. samsung device, android 8.1.0.
unfortunately there are often disruptions where wlan0 is suddenly stopped. even with ipv6 tethering disabled + keep wifi alive in high performance mode.
vpnhotspot is whitelisted everywhere possible + I also made the process persistent.
still disruptions appear too often.
now I kindly ask you if it would be possible to make the connection/s more stable.

**Comment by Mygod** [comment]
#160
