### ISSUE TITLE
Fallback upstream and wlan0 interface do not work.

### ISSUE THREAD

**Issue by chen-assert** [Mygod/VPNHotspot#165]
In some cases, I only want to use this application as a pure wifi repeater without attaching a VPN.

When I close my VPN, I see this application seems successful fallback and find my wlan0 network interface, but in this case, all my connected device can not access any website. (It also do not work even though I set the upstream network interface to wlan0)

![E00496526E437081E0763BD2FCD1171B](https://user-images.githubusercontent.com/24267374/84847323-7f3b0480-b083-11ea-9eb3-75c977be476b.jpg)
Set upstream to wlan0, connected device can not access any website.
![3D242C9A200B518FD028841DD0DB4E82](https://user-images.githubusercontent.com/24267374/84847365-9a0d7900-b083-11ea-8e31-ae55da3e6f4d.jpg)
Set upstream to tun0, connected device can access website through vpn.

**Comment by chen-assert** [comment]
In fact, I have try to use other wifi tethering application(without shareing VPN), but all of them do not work, I totally do not know what happened. 
I have try to use a vpn but with bypass all ip to implemented the same function.

**Comment by Mygod** [comment]
Uninstall all other VPN tethering applications, reboot, and try again.

**Comment by chen-assert** [comment]
Of course I had a try to reboot my phone, but things to not change.

**Comment by Mygod** [comment]
Disable hardware tethering acceleration.

**Comment by chen-assert** [comment]
I disable hardware tethering acceleration and have a try, but...still, it do not work.

**Comment by Mygod** [comment]
debug information
