### ISSUE TITLE
[Feature] Use fixed configuration for temporary hotspot (Android 11+)

### ISSUE THREAD

**Issue by Mygod** [Mygod/VPNHotspot#166]

**Comment by scrampker** [comment]
This would be wonderful, since I could use Tasker to trigger the temporary hotspot, which automatically turns on the wlan1 toggle. Either this, or make an option to trigger wlan1 with native hotspot. The app is clearly aware of the system's native hotspot state.

**Comment by Mygod** [comment]
@scrampker Good point. I can add an option to make the quick setting tile turn on hotspot and VPN tethering in one tap.

**Comment by Mygod** [comment]
Actually you can already do this with monitor functionality. Never mind.

**Comment by scrampker** [comment]
If we could have the monitor option persistent after reboots, I think this
would solve nearly all of the submitted requests. Just my $0.02. I know
that would make this an end-to-end hotspot solution for me.

**Comment by Mygod** [comment]
#96 No plan to implement this yet but contributions are welcome.

**Comment by Mygod** [comment]
It turns out this is not possible since [Android `WifiServiceImpl`](https://android.googlesource.com/platform/frameworks/opt/net/wifi/+/android-11.0.0_r1/service/java/com/android/server/wifi/WifiServiceImpl.java#1771) requires `startLocalOnlyHotspot` caller to be in foreground (root process cannot satisfy this), and a signature permission is required (app process cannot satisfy this).

**Comment by Mygod** [comment]
Nice! This is supported again! https://cs.android.com/android/_/android/platform/packages/modules/Wifi/+/8ac46fb79766abafba6660d14389d3ba75245494
