### ISSUE TITLE
Speed Issues

### ISSUE THREAD

**Issue by sheckandar** [Mygod/VPNHotspot#169]
First of all, this was like God sent for me on a recent trip while staying at a hotel. I used it to stream to my Chromecast while using VPN to access US Netflix.

Thank you. There isn't an app that can compare.

Now to the problem.

I'm using Pixel 3A with Pie and Magisk. The app works great overall, however, there is a great discreptancy in speeds I get when using Repeater mode vs Hotspot with HotSpot being 4 to 5 times faster. Is there a setting I missed, is it a bug or a hardware limitation? 

Reapeater: 10-15 Mbps down, 1-10 Mbps up.
HotSpot: 40-50 Mbps down, 18-30 Mbps up.

Let me know if you need logs or other infomation

**Comment by Mygod** [comment]
It is likely that your hardware is more optimized for AP mode than WIFI-P2P mode. Nothing I can do about it.

**Comment by Mygod** [comment]
With that said, you can try tweaking "Keep Wi-Fi alive" setting and see how it goes. Feel free to share the results here!
