### ISSUE TITLE
I can not set my own wifi password, say something went wrong, please...

### ISSUE THREAD

**Issue by leowood2000** [Mygod/VPNHotspot#17]
I really appreciate the great app and donated, it worked very well but I failed to set my own password for wifi repeater, it show something went wrong, please... 
could you look into it? thank a lot!
[vpnhotspot-867616125.log](https://github.com/Mygod/VPNHotspot/files/1958291/vpnhotspot-867616125.log)

**Comment by Mygod** [comment]
Hmmm... Looks like I need to look into this for older Android versions... Meanwhile does other functionality work for you for now?

**Comment by leowood2000** [comment]
Yes other functionality works great.

**Comment by Mygod** [comment]
Hi again, could you try [this apk](https://mygod.be/resources/userscloud/1pp9kqd3k7n4) and see if it works?

**Comment by leowood2000** [comment]
您好

非常感谢这个beta版，我试装了一下，输入自己的密码后，界面的network name  提示文本 service inactive， 然后repeater那开关无法再启动，而且无线无法连接，需要wifi关闭重新开启，这个新的app 无法上传debug 信息，提示找不到文件。

王雷

**Comment by leowood2000** [comment]
toggle the Repeater on,  click the edit, in "configure Wi-Fi repeater" menual,  input the Network name and password, click "save", the Network name  show "service inactive", and the repeater toggole automaticly back to "off"
[vpnhotspot-121484008.log](https://github.com/Mygod/VPNHotspot/files/1966945/vpnhotspot-121484008.log)

**Comment by Mygod** [comment]
It's expected that your Wi-Fi will shut off after applying new settings.
This is required to flush cache in system driver. However,

1. Does Wi-Fi turn back on automatically within a minute?
2. Is the password you supplied used after you restarted Wi-Fi?

**Comment by leowood2000** [comment]
1. Does Wi-Fi turn back on automatically within a minute?
A: No.  it won't swtich back automatically.  even I can't switch on the repeated again, meanwhile the wifi connection is dead although the wifi icon show connected,  I have to manually switch off-on the wifi to get wifi worked again. (when I reactive the wifi, then APP pop up message say "something wrong....

2. Is the password you supplied used after you restarted Wi-Fi?
A: No. when I check the PW I input by click the "edit", it pop up "valid config not found, Please start the repeater first"

**Comment by Mygod** [comment]
1. Gotcha. Thanks.
2. Could you try starting repeater and see if the new password you set is being used?

**Comment by leowood2000** [comment]
Could you try starting repeater and see if the new password you set is being used?
A: No, I have no chance to restarting the repeater untill I toggle the cellphone system wifi off&on, but the PW changed again as well as the  "Network name" or SSID changed.

**Comment by Mygod** [comment]
Does your device generate a new SSID and password every time you start the repeater? If that's the case, I'm afraid for now I don't have a solution for changing SSID and password on your device.

**Comment by leowood2000** [comment]
yes, replace the default SSID @ PW with my own result the malfunction, and restart the wifi & repeater lead to generate new SSID and new PW , 

the changeable PW just a enhanced function for me, without this I still can experience the great VPN repeater, thank you survey it!

**Comment by Mygod** [comment]
Just to make sure, does your device generate a new SSID-password every time you start the repeater, even if you didn't change the SSID/password via this app?

**Comment by leowood2000** [comment]
Exactly! I just confirm the APP automatically generate a new SSID & password very time when I toggle the repeater.

**Comment by Mygod** [comment]
Great. Closing this for now.

**Comment by ouahab98** [comment]
Hi Sir ;
could you tell me about : # where do i find the conf file that is made the auto "ssid" and "pass"
i'd like to fix it :)
knowing that the app is working fine
