### ISSUE TITLE
Can't use on Oneplus 7Pro(From H2OS 9.5.9 to H2OS 10.0.6)

### ISSUE THREAD

**Issue by tongcheung0218** [Mygod/VPNHotspot#171]
I have a SIM card that can surf the internet with Unlimited Carrier Data, 
however it must use "OpenVPN" for Data.
if I don't use it , I only have 2G per month.
so I tried to use Wi-Fi Sharing with vpn on "VPNHotspot"  for my computer and other devices.
but it always useless.
and if I exit VPNHotspot it can be useful, but it's my data without vpn.
so what can I do? dear developer.

**Comment by Mygod** [comment]
What do you mean by useless?

**Comment by tongcheung0218** [comment]
it means that my computer can connect the Wi-Fi from mobile, but it's no response in any apps.(No Datas occur)

**Comment by Mygod** [comment]
Okay export debug information.

**Comment by tongcheung0218** [comment]
[vpnhotspot-2068601877829051182.log](https://github.com/Mygod/VPNHotspot/files/4894640/vpnhotspot-2068601877829051182.log)
thanks.

**Comment by Mygod** [comment]
Turn off hardware tethering offload.

**Comment by tongcheung0218** [comment]
wow! thanks.it's working!
