### ISSUE TITLE
[Request] Tethering Hardware Acceleration

### ISSUE THREAD

**Issue by knuxyl** [Mygod/VPNHotspot#172]
I have 2 phones
Moto X4 running stock
Moto Z2 play running custom

When using tethering hardware acceleration on the stock Moto X4, I can only access youtube.com and google.com. It's weird. I installed a magisk module to change my DNS to Cloudflare and also changed my VPN apps DNS to Cloudflare but it did not fix it.

When using tethering hardware acceleration on the custom firmware Moto Z2 Play everything works fine.

The problem is the Z2 Play battery imploded and I don't want the same to happen to the X4 due to the massive increase in battery drain because of the lack of hardware acceleration.

Are there any plans on a workaround for tethering hardware acceleration for unsupported devices? I talked to Moto on Github and got them to release the source code for the latest kernel that I am running, maybe there is something in there that would give a clue as to why this isn't working.
`https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPWS29.69-40-3-1`

Also if you could let me know what logs I could share that would hlep I would. 

Thanks!!

**Comment by Mygod** [comment]
Ask your device vendor/ROM developer.

**Comment by worstperson** [comment]
Battery failures usually occur for us when the device is allowed to get too hot or kept fully charged. Just keep it away from heat sources(like windows) and use something like Battery Charge Limit or Advanced Charging Controller to limit charging for devices that remain plugged in.
