### ISSUE TITLE
在一段时间后会关闭我的代理软件

### ISSUE THREAD

**Issue by 1608637229** [Mygod/VPNHotspot#174]
我使用vpnhotspot转发我的代理软件，我是用tinyProxy代理，然后使用vpnhotspot转发。
但是只要经过一段时间，tinyProxy这个软件会自动关闭。当我不用vpnhotspot时，代理软件
则不会被关闭。这两个软件我都取消了电池优化和加了后台白名单.

我的手机型号是k20 pro. 系统是miui10，安卓版本是9.0，

**Comment by Mygod** [comment]
This app does not impact other apps on the system.
