### ISSUE TITLE
cp: invalid option - -n Android 5.1 Note 4 N910C

### ISSUE THREAD

**Issue by lordgzar** [Mygod/VPNHotspot#176]
![Screenshot_2020-07-23-02-28-09](https://user-images.githubusercontent.com/20982225/88243195-dc803200-cc8f-11ea-90ed-821302ab6aa3.png)
I installed your amazing tool two days ago and it was working then after restart it just fails to start wlan0 and by referring to SuperSu logs i found that it tries to use -n which does not exist on my cp version

**Comment by Mygod** [comment]
Thanks for the report. Are you using Busybox?

**Comment by lordgzar** [comment]
Yes BusyBox Pro version 1.32

**Comment by Mygod** [comment]
Hi please try this apk and see if it works: https://mygod.be/resources/userscloud/037nc8gap5z6

**Comment by lordgzar** [comment]
Working now also it's faster, thanks for the great work much appreciated.

**Comment by Mygod** [comment]
Oh glad to hear that it is faster. This fix will be included in v2.10.10 and later.
