### ISSUE TITLE
Wireless repeater will auto close

### ISSUE THREAD

**Issue by Kaneki-x** [Mygod/VPNHotspot#178]
Hello, I use vpnhostspot on Nexus 6p (Android 8.1.0), when my computer connect for a while may 10-20 mis, the Wireless repeater will auto close. I put the vpnhostspot always on top, and already put  the apk into /system/pri-app/, how to solve this problem

**Comment by Mygod** [comment]
Sounds like a vendor specific issue. Disable battery saving features, enable wifi lock in app settings, etc and good luck.
