### ISSUE TITLE
No Internet connection when using Repeater with "Netlink monitor" mode.

### ISSUE THREAD

**Issue by j-moriarti** [Mygod/VPNHotspot#179]
Android version: LOS 7.1.2 Arm-v7a
App version: 2.10.11
Network status monitor mode: "Netlink monitor" and "Netlink monitor with root"

more info:
It was working great in version 2.9.1. but after upgrading to latest version, there is no internet on end devices when connected to my device (also didn't work with 2.10.10). No errors get displayed in the app.

there is no issue when selecting "Poll" or "Poll with root" modes (but devices sometimes struggle to get internet at first try).

**Comment by Mygod** [comment]
Thanks! Could you export debug information when using netlink monitor?

**Comment by j-moriarti** [comment]
Oh I forgot that step. Here you are:
[vpnhotspot-1086791853.zip](https://github.com/Mygod/VPNHotspot/files/5009867/vpnhotspot-1086791853.zip)

**Comment by j-moriarti** [comment]
I somehow found a way to temporary fix this issue by doing the following:
 - open the app and start repeater mode.
 - connect my device to the repeater. (still no internet)
 - go to "Clients" tab and "Block" my device from there, then "Unblock" it again.
 - my end device will get connected to internet!!!

**Comment by Mygod** [comment]
Are you sure it only happens with monitor mode? Your log seems to be pointing to a different issue.

**Comment by j-moriarti** [comment]
> 
> 
> Are you sure it only happens with monitor mode? Your log seems to be pointing to a different issue.

Maybe you are right! but I only observed this issue when the "Netlink monitor" mode was selected. (maybe I'm wrong)

also I noticed that after using the temporary fix I mentioned above,if I press on "**Clean/reapply routing rules**", then the internet connection of end device will break again! and the mentioned fix will not work until I restart repeater mode!

**Comment by Mygod** [comment]
For now I cannot tell what exactly is causing the issue. Disable xposed and try again.

**Comment by j-moriarti** [comment]
> 
> 
> For now I cannot tell what exactly is causing the issue. Disable xposed and export another debug information.

Here you are:

[vpnhotspot-960789355.zip](https://github.com/Mygod/VPNHotspot/files/5018201/vpnhotspot-960789355.zip)

I tried with xposed disabled, the issue was still present, but only in one test, my device got internet access. then it tried restarting repeater, and again got to the problem.

**Comment by Mygod** [comment]
I do not think your error is related to v2.10. Please install [v2.9.1](https://github.com/Mygod/VPNHotspot/releases/tag/v2.9.1) and export again.

**Comment by j-moriarti** [comment]
> 
> 
> I do not think your error is related to v2.10. Please install [v2.9.1](https://github.com/Mygod/VPNHotspot/releases/tag/v2.9.1) and export again.

Here you are:

[vpnhotspot-2049013577.zip](https://github.com/Mygod/VPNHotspot/files/5020528/vpnhotspot-2049013577.zip)

app version: 2.9.1
xposed state: disabled

tested repeater 2 times, and my device got working internet immediately after connecting to repeater.

**Comment by Mygod** [comment]
Please try [v2.10.12](https://github.com/Mygod/VPNHotspot/releases/tag/v2.10.12) again and see if it works. What device model are you using by the way?

**Comment by j-moriarti** [comment]
> 
> 
> Please try [v2.10.12](https://github.com/Mygod/VPNHotspot/releases/tag/v2.10.12) again and see if it works. What device model are you using by the way?

Thanks for your hard work! it got a little bit better, but unfortunately there is still a problem here:

- when devices connect to the repeater (**for the first time after starting repeater mode**), they still have no internet connection (also no ip) and the "Clients" tab of the app doesn't update the status for the connected device and I should manually refresh that tab to update info and after that the device gets internet connection!

- if I press on "**Clean/reapply routing rules**", then the internet connection of end device will break again! It won't get fixed until I stop repeater and exit and re-open the app and restart repeater mode! (and also I should repeat the above step).

- I have tested while xposed was disabled.

- By the way, my phone model is an old Sony Xperia L which I use it to share my net to my other device.

**Comment by j-moriarti** [comment]
Currently I'm using v2.9.1 and I'm ok with it, so I think it's better to wait to see if any other person have this issue. Thank you for taking the time to resolve this issue! Great app BTW :wink:

**Comment by Mygod** [comment]
Does "poll" mode work for you? If so, keep using that.

**Comment by j-moriarti** [comment]
> 
> 
> Does "poll" mode work for you? If so, keep using that.

Yes, Poll mode works and devices get internet connection, But still the "Clean/reapply routing rules" button has issues in that mode, too. I'm somehow addicted to that button :laughing: it's like refresh button in Windows :joy: 
also, poll mode normally has higher power usage, but it's ok.
Feel free to close this issue anytime!

**Comment by Mygod** [comment]
Yeah I can't be bothered to fix this to be honest so closing for now.

**Comment by chromer030** [comment]
Hi , On my phone also internet connection when using repeater with "Netlink monitor"  is broken , but on poll mode is OK.
Model : Lenovo K3 Note
Android version: ViperOS 7.1.2 ARM-v8a
App version: 2.10.11 , 2.10.12 , 2.10.13

[vpnhotspot-792545786.log](https://github.com/Mygod/VPNHotspot/files/5044564/vpnhotspot-792545786.log)
