### ISSUE TITLE
DNS Leak and iptables rules

### ISSUE THREAD

**Issue by a10245657** [Mygod/VPNHotspot#183]
All DNS requests are sent outside the VPN tunnel. The network is not secure. In addition, all iptables rules (FORWARD Chain rules) don't work due to the "ACCEPT" rule(s) in vpnhotspot chain(s) .

**Comment by Mygod** [comment]
Explain how you tested and export debug information.

**Comment by a10245657** [comment]
![1](https://user-images.githubusercontent.com/69576557/90140337-3023fe00-ddac-11ea-81b9-39df1494ed66.png)
![2](https://user-images.githubusercontent.com/69576557/90140353-35814880-ddac-11ea-8cdf-af8c6b3249bb.png)

**Comment by a10245657** [comment]
![3](https://user-images.githubusercontent.com/69576557/90141959-5cd91500-ddae-11ea-852b-abeed9ca586d.png)
![4](https://user-images.githubusercontent.com/69576557/90141973-63678c80-ddae-11ea-8ad4-bde000da1712.png)

**Comment by a10245657** [comment]
I guess "iptables -I FORWARD -j vpnhotspot_fwd" is used instead of "iptables -A FORWARD -j vpnhotspot_fwd" . 
The FORWARD chain rules don't work due to "ACCEPT" is used above these rules.

**Comment by a10245657** [comment]
![5](https://user-images.githubusercontent.com/69576557/90143375-22707780-ddb0-11ea-948c-643204807ad7.png)

**Comment by Mygod** [comment]
This happens because your VPN app either does not advertise the DNS correctly, or does not provide a DNS.
