### ISSUE TITLE
Issues with Android 10 and Oxygen OS (Oneplus)

### ISSUE THREAD

**Issue by 1nikolas** [Mygod/VPNHotspot#184]
When tethering wifi and usb (the normal way) and activating the vpn tether, it does nothing. The tethered device has the normal internet, not vpn. Tried older and newer versions + betas, nothing works. I could send logs if nessesary. Also, a friend of mine has the same problem since updating to Oxygen OS 10.
Thanks

**Comment by Mygod** [comment]
Disable hardware tethering acceleration.

**Comment by 1nikolas** [comment]
It was that simple? Thanks its working
