### ISSUE TITLE
S9+ usb tethering not working android 10!

### ISSUE THREAD

**Issue by tsiofaniss** [Mygod/VPNHotspot#185]
WiFi tether works fine,
tethering through USB does not work, tried disabling hardware acceleration still does not work tried older apk versions still no luck,
I am running official Samsung ROM, android 10 .
everything was working when i had android 9.

**Comment by Mygod** [comment]
Thanks. Could you export debug information on the latest version?

**Comment by tsiofaniss** [comment]
[vpnhotspot-2266478864016888827.log](https://github.com/Mygod/VPNHotspot/files/5138879/vpnhotspot-2266478864016888827.log)
im in the proccess of rolling back my phone to android 9 cause i need it to work with usb tether so not sure if the log is on latest apk version, thats the debug i had before hitting the flash button...

**Comment by tsiofaniss** [comment]
If it helps any further the phone gets recognized as a tethering device but is unable to give internet access (unable to obtain ip).

**Comment by tsiofaniss** [comment]
here you go and sorry for the many replies, log on the latest version hope it helps!
[vpnhotspot-7836684527124930850.log](https://github.com/Mygod/VPNHotspot/files/5138941/vpnhotspot-7836684527124930850.log)

**Comment by Mygod** [comment]
Sorry for the late reply. Please export debug information when service is active.
