### ISSUE TITLE
WireGuard VPN Protocol support

### ISSUE THREAD

**Issue by MOVZX** [Mygod/VPNHotspot#19]
Please kindly add support for WireGuard VPN Protocol.

**Comment by Mygod** [comment]
What makes you think this app doesn't support it? #15

**Comment by MOVZX** [comment]
I'm using WireGuard with Kernel implementation. But when I tried USB Tethering, my PC still showing the IP Address of my Mobile Network Operator, not the WireGuard server.

**Comment by Mygod** [comment]
As mentioned in #15, kernel implementation isn't really supported by this app. Are you sure you have to use kernel implementation?

**Comment by ViRb3** [comment]
I have re-opened #15, kernel mode still doesn't work.

**Comment by Mygod** [comment]
Okay so this sounds like a duplicate for #15. Closing this for now. Let me know if you think this is a different issue.

**Comment by Mygod** [comment]
Please give [1.3.1-alpha](https://github.com/Mygod/VPNHotspot/releases/tag/1.3.1) a go and see how that goes.

**Comment by ViRb3** [comment]
Working perfectly fine! Thanks :)
