### ISSUE TITLE
The WIFI Repeater can not work on my Sony F8132

### ISSUE THREAD

**Issue by Wtrwx** [Mygod/VPNHotspot#196]
Here is my log file.
[vpnhotspot-7192373862784362561.txt](https://github.com/Mygod/VPNHotspot/files/5579636/vpnhotspot-7192373862784362561.txt)

**Comment by Wtrwx** [comment]
When I try to turn on the Repeater switch, the switch immediately turns off.

**Comment by Mygod** [comment]
```
11-22 21:59:28.162 22656 22656 E wpa_supplicant: Could not read interface p2p0 flags: No such device
```

It looks like your device does not support this functionality. Report to your device vendor instead.
