### ISSUE TITLE
Repeater password

### ISSUE THREAD

**Issue by leoson95** [Mygod/VPNHotspot#197]
We can not set a fixed ID and password for repeater at all.
When we save, the Wi-Fi restarts and a new ID and password are set by reconnecting the repeater.
Each time I turn on the repeater, generate a new password and ssid.
I use it for TV and it should be fixed.
Is this a problem or do I not know?
Is there a solution?

**Comment by Mygod** [comment]
Update to Android 11.

**Comment by leoson95** [comment]
My phone is android 8 and there is no upgrade .
No way fix ?

**Comment by h0wXD** [comment]
I had the same problem, also on android 8, and found a way to solve this by reverse engineering the /system/vendor/bin/hw/wpa_supplicant file and patching some instructions. 

This method can be found in the android source code at external\wpa_supplicant_8\src\p2p\p2p_utils.c
```c
/**
 * p2p_random - Generate random string for SSID and passphrase
 * @buf: Buffer for returning the result
 * @len: Number of octets to write to the buffer
 * Returns: 0 on success, -1 on failure
 *
 * This function generates a random string using the following character set:
 * 'A'-'Z', 'a'-'z', '0'-'9'.
 */
int p2p_random(char *buf, size_t len)
{
	u8 val;
	size_t i;
	u8 letters = 'Z' - 'A' + 1;
	u8 numbers = 10;

	if (os_get_random((unsigned char *) buf, len))
		return -1;
	/* Character set: 'A'-'Z', 'a'-'z', '0'-'9' */
	for (i = 0; i < len; i++) {
		val = buf[i];
		val %= 2 * letters + numbers;
		if (val < letters)
			buf[i] = 'A' + val;
		else if (val < 2 * letters)
			buf[i] = 'a' + (val - letters);
		else
			buf[i] = '0' + (val - 2 * letters);
	}

	return 0;
}
```

We will be looking for the assembly of this method in the wpa_supplicant file. 
I've used https://cutter.re/ to analyze the binary and find the arm instructions which generate the random ssid / passcode.
You will need to copy this file from your android device to your computer.

1. Search for string `Try to optimize channel selection with peer information received; previously selected op_class %u channel %u`
2. Show x-refs, there should only be one, double click it and switch to the decompiler tab, I also switched to Ghidra.
![image](https://user-images.githubusercontent.com/10574115/114505786-7abf8800-9c63-11eb-8321-124144a70583.png)
3. We've found our p2p_random method, double click the highlighted func
![image](https://user-images.githubusercontent.com/10574115/114506105-e86bb400-9c63-11eb-9a49-79551d4aa32d.png)
4. You should now have the decompiled method in front of you, we're interested in patching the randomness of the method, for each `patch instruction of this` we want to place our cursor there and switch to the disassembly view.
```
undefined8 fcn.00071980(int64_t arg1, int64_t arg2)
{
    char cVar1;
    uint32_t uVar2;
    uint32_t uVar3;
    int32_t iVar4;
    uint64_t uVar5;
    uint8_t *puVar6;
    char cVar7;
    char cVar8;
    uint64_t uVar9;
    
    iVar4 = fcn.00034ebc((char *)arg1, arg2);
    if (iVar4 != 0) {
        return 0xffffffff;
    }
    if (arg2 != 0) {
        if (arg2 == 1) {
            uVar5 = 0;
        } else {
            uVar5 = arg2 & 0xfffffffffffffffe;
            if (uVar5 != 0) {
                puVar6 = (uint8_t *)(arg1 + 1);
                uVar9 = uVar5;
                do {
                    uVar9 = uVar9 - 2;
                    uVar3 = (uint32_t)puVar6[-1] + ((puVar6[-1] >> 1) / 0x1f) * -0x3e;
                    uVar2 = (uint32_t)*puVar6 + ((*puVar6 >> 1) / 0x1f) * -0x3e;
                    cVar7 = 'G';
                    cVar8 = cVar7;
                    if (0x33 < uVar3) {
                        cVar8 = -4;
                    }
                    if (0x33 < uVar2) {
                        cVar7 = -4;
                    }
                    cVar1 = 'A';
                    if (0x19 < uVar3) {
                        cVar1 = cVar8;
                    }
                    cVar8 = 'A';
                    if (0x19 < uVar2) {
                        cVar8 = cVar7;
                    }
                    puVar6[-1] = cVar1 + (char)uVar3; // patch instruction of this (1)
                    *puVar6 = cVar8 + (char)uVar2; // patch instruction of this (2)
                    puVar6 = puVar6 + 2;
                } while (uVar9 != 0);
                if (uVar5 == arg2) {
                    return 0;
                }
            }
        }
        arg2 = arg2 - uVar5;
        puVar6 = (uint8_t *)(arg1 + uVar5);
        do {
            arg2 = arg2 + -1;
            uVar3 = (uint32_t)*puVar6 + ((*puVar6 >> 1) / 0x1f) * -0x3e;
            cVar8 = 'G';
            if (0x33 < uVar3) {
                cVar8 = -4;
            }
            cVar7 = 'A';
            if (0x19 < uVar3) {
                cVar7 = cVar8;
            }
            *puVar6 = cVar7 + (char)uVar3; // patch instruction of this (3)
            puVar6 = puVar6 + 1;
        } while (arg2 != 0);
    }
    return 0;
}
```
5. Find the corresponding arm instruction and patch it to a register value that doesn't change
```
we see instructions assigning values to a register, placing a cursor on w13 or w14, we see it is never modified, perfect, let's use these
0x000719d4      movz w13, 0x47     ; 'G'
0x000719d8      movz w14, 0x41     ; 'A'
....
0x00071a34      sturb w16, [x9, -1] ; this equals => patch instruction of this (1)
0x00071a38      strb w17, [x9], 2 ; this equals => patch instruction of this (2)

this means we can change the instruction to:
0x00071a34      sturb w13, [x9, -1]  ; this equals => puVar6[-1] = 'G'
0x00071a38      strb w13, [x9], 2     ; this equals => *puVar6 = 'G'

we do the same thing for patch no 3, which is located right above the ret of the method
again we see instructions assigning values to a register, placing a cursor on w13 or w14, we see it is never modified, perfect, let's use these
0x00071a60      movz w13, 0x47     ; 'G'
0x00071a64      movz w14, 0x41     ; 'A'
...
0x00071a94      strb w15, [x9], 1 ; this equals => // patch instruction of this (3)

this means we can change the instruction to:
0x00071a94      strb w13, [x9], 1     ; this equals => *puVar6 = 'G'
```
6. Save the changes and next we need to create a magisk module, create module from template https://github.com/Zackptg5/MMT-Extended, and modify files as seen in commit https://github.com/h0wXD/wpa_stuff/commit/99648c7a60ce7e7c98ca1e390eff38a02bf4a882 , replace the wpa_supplicant placeholder with yours.
7. zip the folder and install it as magisk module, reboot your phone, and try VPN hotspot, the SSID / passphrase now stay the same.

Please do this at your own risk.
I have successfully run VPN Hotspot and received a static ssid and password after doing above steps.

**Comment by Mygod** [comment]
Well props to you for figuring out this complicated solution. Let me just link #31 to this issue as it is supposed to be the main tracking issue.
