### ISSUE TITLE
Repeater not starting

### ISSUE THREAD

**Issue by liskamic** [Mygod/VPNHotspot#198]
I just flashed the latest LineageOS 17.1 on my Samsung Galaxy S5 and I cannot start the reperater in VPN Hotspot.

When toggling the _Repeater_ button, it greys out, cannot be turned off, tapping _WPS_ option does nothing and trying to access the _Repeater_ options from the menu yields the following system message: _Valid config not found. Please, start repeater first._
The _VPN tethering active_ notification is shown but the repeater is not working.

VPN Hotspot is installed as a system app and has root access. Tethering HW acceleration is turned off as is the _Repeater safe mode_ (tried both on and off). Version 2.11.2, attaching log:
[vpnhotspot-319083819094623334.log](https://github.com/Mygod/VPNHotspot/files/5685635/vpnhotspot-319083819094623334.log)

**Comment by Mygod** [comment]
Looks like a vendor bug. Report to your ROM developer instead.

**Comment by liskamic** [comment]
Hi, thanks, can you help point me out the relevant parts in the log so I
can pursue the issue further, please?
Thanks again!
ML

**Comment by Mygod** [comment]
Your ROM does not seem to support Wi-Fi p2p.
