### ISSUE TITLE
以前可以开启wifi中继现在却不行了

### ISSUE THREAD

**Issue by theFreeWall** [Mygod/VPNHotspot#200]
创建p2p群组失败(原因:内部异常)

用了一年多了没问题,上次使用应该是12月12号 今天就不行了

log中提示
I/ServiceManager(  416): Waiting for service AtCmdFwd...
E/wpa_supplicant( 4773): Failed to create interface p2p-p2p0-0: -34 (Math result not representable)
E/wpa_supplicant( 4773): P2P: Failed to create new group interface
E/wpa_supplicant( 4773): P2P: Failed to add group interface

**Comment by theFreeWall** [comment]
网络环境未改变

**Comment by Mygod** [comment]
Did you update system?

**Comment by theFreeWall** [comment]
从那之后未改变系统文件
(因为这个手机只作为热点机),从上次使用结束后就一直关机状态下未使用

在重置/misc/wifi下文件后解决,应该是程序退出时产生的bug或者未退出程序以及关闭热点状态下直接关机所导致data分区中wifi文件夹里的文件配置错误

**Comment by Mygod** [comment]
Hmmm I can try to add a reset p2p option to the app.

**Comment by theFreeWall** [comment]
thanks :-)

**Comment by tharryz** [comment]
Same problem and I have deleted all things of misc/wifi, but it still doesn't work.
