### ISSUE TITLE
All Clients always disconnect after about 10 minutes. 

### ISSUE THREAD

**Issue by franklin373** [Mygod/VPNHotspot#205]
I use a vpn app work with Vpn Hotspot app, Android rooted, vpn connect to normal wifi router, Vpn Hotspot open wireless tethering, so it create a DIRECT-EB-Android_???? hotspot, some clients connect to DIRECT-EB-Android_???? hotspot would using VPN to internet.

After turn on VPN Hotspot Repeater button, Clients connect to DIRECT-EB-Android_???? hotspot, I could find clients display in "Clients" tab page. After about 10 minutes, All Clients would disapear at same time in "Clients" tab page, but if I browser in mobile phone, VPN still work. If turn off and turn on Repeater button again, it would begin another 10 minutes connection available again. I try several VPN servers, same result, Always first time try a new VPN server, it could work for  several hours no problem, later only last about 10 minutes.

"Export debug information" log file attached, About 14:45 turn on repeat, About 14:55 all clients disappear.
[vpnhotspot-752823067189892662.log](https://github.com/Mygod/VPNHotspot/files/5901583/vpnhotspot-752823067189892662.log)

**Comment by Mygod** [comment]
This seems like a vendor issue. Try a different VPN, or report to your device vendor.

**Comment by franklin373** [comment]
I use VPN Hotspot in another way, as this web page suggest:
https://www.sainnhe.dev/post/v2ray-hotspot/
Now, it work stable. @Mygod
