### ISSUE TITLE
Repeater not working on Android 11

### ISSUE THREAD

**Issue by cbs525** [Mygod/VPNHotspot#211]
Repeater function is greyed out after turning on
![Screenshot_20210417-104601_VPN_Hotspot](https://user-images.githubusercontent.com/82694948/115102956-d93e7c00-9f6b-11eb-9838-494cdef47a0f.png)

Here are the logs. 
[vpnhotspot-1040802893789439225.log](https://github.com/Mygod/VPNHotspot/files/6328667/vpnhotspot-1040802893789439225.log)

**Comment by Mygod** [comment]
Thanks! Could you try turning Wi-Fi off and on again?
