### ISSUE TITLE
Root occasionally freezes

### ISSUE THREAD

**Issue by nekohasekai** [Mygod/VPNHotspot#215]
![Screenshot_20210423-082951830](https://user-images.githubusercontent.com/56506714/115801347-19d84280-a40f-11eb-821d-b1dd5f30e840.jpg)
![Screenshot_20210423-083000248](https://user-images.githubusercontent.com/56506714/115801352-1cd33300-a40f-11eb-9a67-c401f8f0dcc2.jpg)

None of these two items responded to me. When I checked logcat, there was only "CPU cluster # mismatch: Power Profile # 2 actual # 3"

--------------------
Version: 2.11.4 (play store)
Device: Redmi K30 5G
System: rr_picasso-userdebug 10 QQ3A.200905.001

**Comment by nekohasekai** [comment]
When I rebooted for the second time, it returned to normal :(

**Comment by Mygod** [comment]
This is a bug that happens very rarely. Killing the app should resolve the issue. We are looking into it.

**Comment by Mygod** [comment]
Hi please try [v2.12.0-alpha](https://github.com/Mygod/VPNHotspot/releases/tag/v2.12.0). There are some radical changes that hopefully would resolve this issue. :)

**Comment by Mygod** [comment]
Closing for now. Let me know if anyone reproduces this on v2.12+.
