### ISSUE TITLE
Repeater not working 

### ISSUE THREAD

**Issue by C00LDroid** [Mygod/VPNHotspot#22]
Using VPNHotspot as System app on Oero 8.0, Actually i use my wifi for storage purpose and recently find out that repeater doesn't work for wifi connections with no Internet Connection, i can't even reach to my router settings (192.168.1.1) from my 2nd Device,
Please look into it 
here is my logs, 
[vpnhotspot-8475376107761821038.log](https://github.com/Mygod/VPNHotspot/files/2063437/vpnhotspot-8475376107761821038.log)

**Comment by Mygod** [comment]
Repeater should work with connections without Internet Connection (at least on my side). Can you reach your router settings from your 1st device? Do you use a VPN? Does your 1st device have other working connections beside Wi-Fi like a cellular connection?

**Comment by C00LDroid** [comment]
No not used any vpn and i can access router settings in my first device, tested using wifi connection only no any other connection at that time

**Comment by C00LDroid** [comment]
Find out a weird thing, repeater works correctly on same device for the connection with internet access, so there is something related to no internet access which is causing this problem

**Comment by Mygod** [comment]
> Does your 1st device have other working connections beside Wi-Fi like a cellular connection?

**Comment by C00LDroid** [comment]
No

**Comment by Mygod** [comment]
I have the exact same settings here and I can't reproduce it. Could you try 1.3.1-alpha?

**Comment by C00LDroid** [comment]
Yes I can try, please provide link

**Comment by Mygod** [comment]
https://github.com/Mygod/VPNHotspot/releases

**Comment by C00LDroid** [comment]
Tested alpha version getting same results, checked on 3rd device which not even able to connect stuck at obtaining ip address.....,
Then i clear saved wifi on 2nd device just to check now 2nd device also stuck at obtaining ip address....

**Comment by Mygod** [comment]
Try a reboot. Also please export debug information.

**Comment by C00LDroid** [comment]
After reboot
[vpnhotspot-4404390129347946126.log](https://github.com/Mygod/VPNHotspot/files/2064582/vpnhotspot-4404390129347946126.log)

**Comment by Mygod** [comment]
Hmm could you try turn on airplane mode and then turn on Wi-Fi and then try again?

**Comment by C00LDroid** [comment]
Same result for wifi while airplane mode was on here is logs
[vpnhotspot-7113076143518380540.log](https://github.com/Mygod/VPNHotspot/files/2064593/vpnhotspot-7113076143518380540.log)

**Comment by Mygod** [comment]
Hmm then I'm afraid it might be a vendor bug. I don't think I can help with this for now.

**Comment by C00LDroid** [comment]
got something limited internet connection was causing issue now working fine 👍

**Comment by Mygod** [comment]
Hello again. Could you explain what exactly you did to solve this issue? Also could you try 1.3.7 with DHCP workaround enabled to see if it also resolves your issue?

**Comment by C00LDroid** [comment]
Actually i was able to get connected on other devices but it didn't solved problem fully I did these steps:-
turn on repeater and connect secondary device before connecting actual wifi which has limited internet access but still result was same

**Comment by Mygod** [comment]
DHCP workaround should be able to solve the issue of clients not having IP addresses.
