### ISSUE TITLE
Inconsistent routing on clients when VPN enabled

### ISSUE THREAD

**Issue by Reinitialized** [Mygod/VPNHotspot#250]
When using Wireguard with VPN Hotspot, connected clients are able to ping LAN devices without issues. However, accessing internal LAN sites (such as opnSense/PiHole/Proxmox) work inconsistently, and attempting to use Wireguard on the client doesn't work half the time. This affects my ability to remotely work on my infrastructure as I'm unable to access LAN devices half of the time. I've tried resetting the routes and rebooting both devices to no avail. Will gladly submit information, just don't know what I need to collect up front.

**Comment by Mygod** [comment]
Could you start by maybe sharing the IP addresses of the clients and your hotspot subnet?

**Comment by Reinitialized** [comment]
IP my laptop has on VPN Hotspot is 192.168.43.120
IP I'm attempting to access is 10.200.101.208
All IPs on my network are within the 10.0.0.0/8 subnet range.

**Comment by Mygod** [comment]
Could you start the service and then export debug information from the app?

**Comment by Reinitialized** [comment]
[vpnhotspot-547645603288998074.log](https://github.com/Mygod/VPNHotspot/files/6858088/vpnhotspot-547645603288998074.log)

**Comment by Mygod** [comment]
Turn off hardware tethering acceleration.
