### ISSUE TITLE
Is there a "VPNHotspot.art" into /system/priv-app/VPNHotspot/oat/arm64/ ?

### ISSUE THREAD

**Issue by 1457384613gh** [Mygod/VPNHotspot#252]
How about `VPNHotspot.art` ?
I want to copy `VPNHotspot` into  `/system/priv-app/` ，and I wonder how to deal with `VPNHotspot.art`. 
There is no` XXX.art` into `/system/priv-app/XXX/oat/arm64/`, so should I delete or keep `VPNHotspot.art` ?
![Screenshot_2021-07-28-12-27-37-561_com estrongs android pop](https://user-images.githubusercontent.com/69227436/127265288-8ac44c31-49ed-4992-9691-e869397f6efd.jpg)
![Screenshot_2021-07-28-12-27-49-280_com estrongs android pop](https://user-images.githubusercontent.com/69227436/127265317-1586edb4-a30b-44e0-ba7f-d5e784295af8.jpg)

**Comment by Mygod** [comment]
This app does not contain native code.

**Comment by 1457384613gh** [comment]
So，just an apk. It is no problem if there is only an apk even without the folder `oat` ?
So, could I delete the `folder` oat ?
