### ISSUE TITLE
Tasker integration

### ISSUE THREAD

**Issue by Mygod** [Mygod/VPNHotspot#26]
@sea3pea0: https://github.com/Mygod/VPNHotspot/issues/9#issuecomment-401563308

>How about the ability to control this app via intents so that we could use tasker to initiate actions in this app? I have an android head unit in my car that is connected to an android phone acting as a hotspot and running this app. 
>
>The only way I've found to reliably avoid having my hotspot being throttled by t-mobile is to share the hotspot through a vpn connection. 
>
>Right now, when my car is turned on or the android phone boots up, tasker turns my hotspot on and when the car turns off the hotspot is turned off by tasker. With tasker I sense whether the car is on or off by the charging cable for the phone. If its charging, the car is on and if not its off.
>
>It would be great if I could also have an action to turn vpn hotspot on for my wlan as one of the actions. This way the process would be automated.
>
>As of now, if the hotspot is turned off and then back on, I have to go manually into the vpn hotspot app and re-toggle the wlan switch to route the hotspot traffic back through the vpn.
>
>Thanks in adavnce for your help and/or consideration for this feature request. Obviously if it was possible for this app to remember the last setting and just ensure that either after boot or if the hotspot is turned off and back on that traffic would be routed through the vpn, this would work for me too. If its easier to make this possible through the use of tasker automations perhaps this would help others too.

And maybe MacroDroid as well?

**Comment by Mygod** [comment]
Meanwhile, I think a good workaround would be a monitoring mode for system VPN tethering. I will implement it in 2.3.0.

**Comment by Kerrnel** [comment]
Bump on implementing intent interface. I can not find an app as reliable in turning on & off tethering - just by itself, w/o VPN involvement. I'd love to use it with Llama to automate getting into the car and having tethering for my car radio / off when out. (On a side note... gets me thinking AppleScript for Android should be a thing with object & class interface definition part of every app.)

**Comment by the-mentor** [comment]
Why not use the tasker plugin system?
https://tasker.joaoapps.com/plugins-intro.html

Awesome app btw!
-DM

**Comment by GluTbl** [comment]
it will be a very lentgthy addition to enable tasker integration.

if you want to add with short code, just add some a Broadcastreceiver  to receive intent... and trigget hr e action in the source code... Now from the Tasker send the Intent directly.

if you make a tasker plugin... you need to read whole documentation of tasker plugin making.

If i have free time i might add this tasker facility

**Comment by sollermun** [comment]
Has anyone figured out a good way to automatically toggle the rndis0 tunnel? I'm using a phone to act as a usb modem for a router. I've managed to automate turning on the usb hotspot and VPN. The missing piece would be to automatically turn on rndis0 whenever the VPN connection is reset.

**Comment by cocoands** [comment]
+1 for Tasker integration. I also think making the app compatible with the [AutoInput accessibility service](https://joaoapps.com/autoinput/faq/) would be another good place to start. It should be simpler than writing a new plugin. AutoInput currently can not interact with the VPN Hotspot UI, but if it could, manually toggling the switches as @sea3pea0 and @sollermun describe wouldn't be an issue.

**Comment by Swap-File** [comment]
I recently noticed that VPN Hotspot was able to toggle Bluetooth Tethering off and on without being systemized on android 13.  

This interested me greatly, since all the other tools I used to use to toggle BT Tethering off and on refused to work on Android 13, even when systemized.

I've never done Android development before, but I sat down with Android Studio and copy & pasted the Tile Handler into a Broadcast Handler which can receive intents from MacroDroid or Tasker.

Here is what the changes look like if anyone wants to build a copy for themselves (or add more intents to support more automation):
https://github.com/Swap-File/VPNHotspot/commit/a4024d2a2306aa3d3842d29ec513b8d9358179dc

Here's what the intent looks like inside of Macrodroid:
![image](https://user-images.githubusercontent.com/3854710/217565323-86a436ec-eeda-45f4-8362-cecbdac5e5a5.png)

**Comment by xangma** [comment]
> 



> I recently noticed that VPN Hotspot was able to toggle Bluetooth Tethering off and on without being systemized on android 13.
> 
> This interested me greatly, since all the other tools I used to use to toggle BT Tethering off and on refused to work on Android 13, even when systemized.
> 
> I've never done Android development before, but I sat down with Android Studio and copy & pasted the Tile Handler into a Broadcast Handler which can receive intents from MacroDroid or Tasker.
> 
> Here is what the changes look like if anyone wants to build a copy for themselves (or add more intents to support more automation): [Swap-File@a4024d2](https://github.com/Swap-File/VPNHotspot/commit/a4024d2a2306aa3d3842d29ec513b8d9358179dc)
> 
> I'm not sure if there is a limit to how many intents you can add to the manifest, but two work fine for me.
> 
> Here's what the intent looks like inside of Macrodroid: ![image](https://user-images.githubusercontent.com/3854710/217565323-86a436ec-eeda-45f4-8362-cecbdac5e5a5.png)

Hello! Thanks so much for this information. With your (and an LLM's help) I was able to build and test this in a couple of hours, and it works great. And obviously thanks to the original app developer/s too! :-D

**Comment by hansonxyz** [comment]
Hi there,

I was really interested in this thread, as my goal was to automate bringing up a wireguard vpn interface and programmatically starting the hotspot via tasker.  To do this, I needed to both add the broadcastreceiver to receive the intent to start tethering, as described above, and also have the program automatically monitor all new interfaces that were added.  I made these modifications and published them in a modified source code here:

https://github.com/hansonxyz/vpnhotspotmod

The key extra changes to the code Swap-File added was changing the TetheringService from START_NOT_STICKY to START_STICKY, and adding the following code around line 565 on TetheringManager.kt:
```

                            method.matches1<java.util.List<*>>("onTetheredInterfacesChanged") -> {
                                @Suppress("UNCHECKED_CAST")
                                val tetheredInterfaces = args!![0] as List<String?>
                                callback?.onTetheredInterfacesChanged(tetheredInterfaces)

                                // hansonxyz
                                tetheredInterfaces?.let {
                                    for (iface in it) {
                                        App.app.startForegroundService(
                                            Intent(App.app, TetheringService::class.java)
                                                .putExtra(
                                                    TetheringService.EXTRA_ADD_INTERFACES,
                                                    arrayOf(iface)
                                                )
                                        )
                                    }
                                }
                            }
```

**Comment by ibnusaja** [comment]
> Hi there,
> 
> I was really interested in this thread, as my goal was to automate bringing up a wireguard vpn interface and programmatically starting the hotspot via tasker. To do this, I needed to both add the broadcastreceiver to receive the intent to start tethering, as described above, and also have the program automatically monitor all new interfaces that were added. I made these modifications and published them in a modified source code here:
> 
> https://github.com/hansonxyz/vpnhotspotmod
> 
> The key extra changes to the code Swap-File added was changing the TetheringService from START_NOT_STICKY to START_STICKY, and adding the following code around line 565 on TetheringManager.kt:
> 
> ```
> 
>                             method.matches1<java.util.List<*>>("onTetheredInterfacesChanged") -> {
>                                 @Suppress("UNCHECKED_CAST")
>                                 val tetheredInterfaces = args!![0] as List<String?>
>                                 callback?.onTetheredInterfacesChanged(tetheredInterfaces)
> 
>                                 // hansonxyz
>                                 tetheredInterfaces?.let {
>                                     for (iface in it) {
>                                         App.app.startForegroundService(
>                                             Intent(App.app, TetheringService::class.java)
>                                                 .putExtra(
>                                                     TetheringService.EXTRA_ADD_INTERFACES,
>                                                     arrayOf(iface)
>                                                 )
>                                         )
>                                     }
>                                 }
>                             }
> ```

for adb shell am ? can you hel me for the command line ? thanks before

**Comment by hachazo** [comment]
@Mygod Hello, I wanted to ask you a question, since I am trying to compile the application. I already managed to get the vpn and hotspot to start automatically, but I want it to be activated automatically when I start the wlan0 application. Can you help me, I don't know very well what files to modify.

**Comment by Mygod** [comment]
Fixed via #591.

**Comment by pansen** [comment]
Howdy, 

thank you a lot for this wonderful app. I'm really happy about it. 

I followed the same goal as this issue describes and wanted to share my solution. In my case I want to enable Wifi tethering with Wireguard VPN exposure when Android starts (Motorola Edge 50 Fusion, rooted, Android 15, Android Security Update 2025-11-01, Google Play system update 2026-02-01). 

The Wireguard VPN connects automatically on boot, there is nothing to worry about. 

I'm doing two steps in my Tasker Profile: 

- Enable Wifi tethering via [Delta](https://delta.shadoe.dev/quick-start-guide/) (this [release](https://github.com/supershadoe/delta/releases/tag/2025.08%2B0) in my case). Delta allows to enable Tasker integration via intends to toggle Wifi tethering. 
- After this is up and a bit of safety pause, I'm running

  ```
  am start-foreground-service -n be.mygod.vpnhotspot_foss/be.mygod.vpnhotspot.TetheringService --esa "interface.add" "wlan0"
  ```

  in a Tasker Shell (with root permission)

That's it :) 

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/bbfd47fb-d327-4289-9a97-9919ceee3f3a" />

**Comment by pansen** [comment]
**Edit** 

An even nicer solution seems to be this: 

1) One Tasker Profile attaches to _Device Boot_ and uses Delta to enable the hotspot (if that is desired). In contrast to my previous comment, it will only do that. 

2) Another Tasker Profile attaches to _Event -> Intend Received_.

- Action: `android.net.conn.TETHER_STATE_CHANGED`
- Task: Here we have a _Run Shell_ (with root permission), that contains `am start-foreground-service -n be.mygod.vpnhotspot_foss/be.mygod.vpnhotspot.TetheringService --es "interface.add.monitor" "wlan0"`

This way, we can enable / disable the tethering automatically or manually at any time and the VPN exposure remains active.
