### ISSUE TITLE
Device can not keep regular WiFi and activated hotspot through VPN Hotspot

### ISSUE THREAD

**Issue by Iceboy-6** [Mygod/VPNHotspot#262]
Redmi 5 Plus
AOSP Extended 7.0 Official
Magisk 23.0
VPN Hotspot 2.12.6
Root privileges? Yes
Systemize? Yes, in /system/priv-app
upstream tun1/ fallback wlan0
Disable IPv6 tethering: activated
Tethering hardware acceleration: disabled
DHCP workaround: disabled

![Custom rom](https://user-images.githubusercontent.com/78272358/130484260-03c7798c-4128-4084-bf9e-fc4e8e930d69.jpeg)

Hi! I tried to use VPN Hotspot to share my regular WiFi connection + VPN to my devices that are not compatible with VPN or Proxy (i.e. samsung Smart tv). However, I was not able to activate Wi-fi hotspot or Temporary Wi-fi Hotspot and keep my regular WiFi connection at same time. 

log here: 
https://ghostbin.com/paste/MKf8c/vpn
I activated my WiFi, then my vpn. After that, I tried to use Wi-Fi hotspot, but I was not able to keep regular WiFi simultaneously. I also tried to use temporary hotspot, but same error occurred.

Repeater mode works fine.

Did anyone face a similar problem? Thank you in advance.

**Comment by Mygod** [comment]
That means your device/ROM does not support this concurrency. Use repeater.
