### ISSUE TITLE
错误：未找到下游接口

### ISSUE THREAD

**Issue by JPGC123** [Mygod/VPNHotspot#276]
之前都还好好的，突然就这样了！现在只能打开便携式热点
![Screenshot_20210919-182902](https://user-images.githubusercontent.com/49173433/133924169-9737191d-8b7b-4849-a49c-d89f6f03be5c.jpg)
[vpnhotspot-809440289976664767.log](https://github.com/Mygod/VPNHotspot/files/7191761/vpnhotspot-809440289976664767.log)

**Comment by Mygod** [comment]
#273
