### ISSUE TITLE
[Feature] Bridge Hotspot and USB thethering

### ISSUE THREAD

**Issue by NULL0B** [Mygod/VPNHotspot#296]
Would be nice to bridge hotspot and usb tethering so a PC whitout network can be connected for example.

**Comment by NULL0B** [comment]
Yes, also the app shows two different ip subnets
Im suggesting that usb thethering and wifi hotspot act as one, bridged. There are many people interested in this feature and I found your app with good profile to have it.

**Comment by Mygod** [comment]
No plan for this.
