### ISSUE TITLE
Can't configure 'Repeater' settings (name, pass, etc...)

### ISSUE THREAD

**Issue by w4po** [Mygod/VPNHotspot#306]
Hello,
I can't configure the Repeater settings,
Every time I turn it on I gets a new name & password, which is hard to enter every time to connect.
At first, there was a 'save' option, but it disappears and even when it was there it didn't work.

SM-G611F with root access, Android 9 stock ROM.

Thank you very much for the awesome tool <3

**Comment by Mygod** [comment]
Update to Android 10 or try a different ROM.
