### ISSUE TITLE
Magisk 24.1 Zygisk Root missing.

### ISSUE THREAD

**Issue by yanygm** [Mygod/VPNHotspot#338]
[magisk_log_2022-02-22T13_13_21.log](https://github.com/Mygod/VPNHotspot/files/8113876/magisk_log_2022-02-22T13_13_21.log)
![Magisk1](https://user-images.githubusercontent.com/17066245/155068811-93898fa4-494f-446b-8752-8f2a51a119c5.jpg)
![Magisk2](https://user-images.githubusercontent.com/17066245/155068814-9917b22e-3c6a-491f-8fc4-7206bccc6222.jpg)

**Comment by Mygod** [comment]
Did you allow this app to use root?

> `su: request rejected`

**Comment by yanygm** [comment]
This application does not exist in the application list.

**Comment by yanygm** [comment]
The problem has been solved, it was me hiding the app.
