### ISSUE TITLE
Samsung mobile phone cannot modify network name

### ISSUE THREAD

**Issue by 836391639** [Mygod/VPNHotspot#34]
[vpnhotspot-314901294.log](https://github.com/Mygod/VPNHotspot/files/2327163/vpnhotspot-314901294.log)

**Comment by Mygod** [comment]
Thanks for your report. I believe this dups #31. If you can compile your ROM, try the workaround mentioned at https://github.com/Mygod/VPNHotspot/issues/31#issuecomment-414594088.
