### ISSUE TITLE
Only Temporary Hotspot Works

### ISSUE THREAD

**Issue by knuxyl** [Mygod/VPNHotspot#35]
**ZTE Axon 7 (A2017U)
AOSP Extended (AEX) 5.7 Official (Android 8.1.0)
Magisk 17.1
BusyBox 1.29.2
Xposed Framework 90.2 beta 3 (but no modules installed)**
![screenshot_settings_20180911-225856](https://user-images.githubusercontent.com/19507326/45401496-7a2b6480-b616-11e8-8706-2e4d69571df5.png)

The hotspot does not route through my VPN. When I use Temporary Hotspot, it does. I have whiped and installed a fresh Android and it still will not work.

These are my settings

Upstream Network Interface  = Auto detect system VPN
IP Masquerade = On
Strict Mode = On
Disable IPv6 tethering = On
Fallback DNS server[:port] = 8.8.8.8
Enable DHCP workaround = Off

These settings will work with Temporary Hotspot.

When I use my regular hotspot and toggle VPN switch above "+ Manage System Tethering..." on first tab, it disables IPv6, but does not route through VPN and only allows the connected device to go to Youtube.com and Google.com. Google shows my IPv4 address from my ISP, not the VPN. My ISP address on Google will be a IPv6 address normally, so the Disable IPv6 Tethering is working.

The logs attached below are from after I did the following.

1) Force closed app
2) Deleted app data and cache
3) Opened app and changed settings to ones above
4) Started Temporary Hotspot and connected a device
5) Turned off Temporary Hotspot

The rest I did 3 times

6) Turned on Wifi Hotspot
7) Enable VPN Tethering on toggle switch above "+ Manage System Tethering..." on first tab
8) Tried the internet and got my IPv4 ISP address and only could go to Youtube.com and Google.com.

https://www.dropbox.com/s/mjsk61zd0lll93m/vpnhotspot-6416338702922597112.log?dl=0

**Comment by Mygod** [comment]
Thanks for your detailed information. However, according to your log, you have enabled hardware tethering offload enabled, which would interfere with this app's normal functionalities. Please turn it off in developer options.

Also I noticed that you're using 1.4.2, I'm wondering if you can read a small text below "Manage system tethering..." that asks you to disable hardware tethering offload. If not, this should be a bug and we should investigate further. :)

**Comment by Mygod** [comment]
Cool. Feel free to comment down/open another issue if you have further questions related/not related to this one.
