### ISSUE TITLE
[FeatureRequest] Add proxy-server mode

### ISSUE THREAD

**Issue by cuamckuu** [Mygod/VPNHotspot#355]
Hi, I was trying to create WiFi hotspot from [gnirehtet VPN](https://github.com/Genymobile/gnirehtet), but I don't have root access on my phone

Finally, I managed to find [workaround](https://www.technadu.com/how-to-share-a-vpn-connection-on-android-without-root/258827/) with [Every Proxy](https://play.google.com/store/apps/details?id=com.gorillasoftware.everyproxy&hl=en&gl=US). Every proxy starts http proxy server and routes all traffic from connected device with configured proxy directly to VPN. The problem is that Every Proxy closed souced

It will be cool if you implement http proxy server in [VPNHotspot](https://github.com/Mygod/VPNHotspot) as it will be very helpful for users without root access on their phones

**Comment by Mygod** [comment]
Why ask me if another app already does it?

**Comment by cuamckuu** [comment]
As I said, existing app is closed source. And implementing proxy-server function will allow non rooted users to create vpn hotspot with your app
