### ISSUE TITLE
Hi, there, missing databinding folder when I open it at Android Studio

### ISSUE THREAD

**Issue by yingshaoxo** [Mygod/VPNHotspot#36]
1. I must say, you are so amazing to create such an app that certainly useful 

2. I want to learn the inner logic and design patterns from you, so I cloned this project, and opened it at Android Studio

3. But I got something wrong with `import be.mygod.vpnhotspot.databinding.ActivityMainBinding`, it says `Unresolved reference: databinding`. And yes, indeed there no such a folder.

Can you point out where I'm wrong? Thanks a lot.

**Comment by yingshaoxo** [comment]
Thanks a lot.

After I restarted my computer and reopened this project, I finally make it work at my android device.

**Comment by GluTbl** [comment]
> Compile the project.

I dont get it what you mean.... i could not find "be.mygod.vpnhotspot.databinding" in the project.. i got the same error
