### ISSUE TITLE
Create dnsmasq service using custom dns server (eg. 127.0.0.1:53 / local dnsserver) rather than 8.8.8.8

### ISSUE THREAD

**Issue by zievfik** [Mygod/VPNHotspot#387]
Hi dev!
It woold be great if you add an option so user can change the dnsmasq dns server upstream to custom address(es) rather than force to 8.8.8.8.

For example, I am running local dns server (unbound) to get bypass of content blocking from my internet provider.
And I want to create P2P connection and all client that connected to my P2P will use my local dns server (unbound) instead of 8.8.8.8.

Thanks.

**Comment by Mygod** [comment]
This app does respect your local DNS server instead of forcing 8.8.8.8. (At least on latest versions.)
