### ISSUE TITLE
bug   Temporary hotspot flashback

### ISSUE THREAD

**Issue by shshjh** [Mygod/VPNHotspot#388]
bug 
https://paste.crdroid.net/qXjykc

**Comment by Mygod** [comment]
What flashback?

**Comment by Mygod** [comment]
Looks like it was caused by this: https://cs.android.com/android/_/android/platform/packages/modules/Wifi/+/1c83bc7c656da808f5b9fbee214e8d15905605c4

**Comment by renataforis123-stack** [comment]
PUBG Hack
