### ISSUE TITLE
等价的adb shell命令

### ISSUE THREAD

**Issue by burg1ar** [Mygod/VPNHotspot#390]
请教一下，手机已经root，连接vpn并打开热点，如何通过adb shell命令使得可以通过热点访问vpn网络？
例如：
手机系统是Android 12，手机目前的网络接口有wlan0，ap0（热点网络接口），tun0（vpn网络接口）
wlan0 ip地址：192.168.31.232
ap0 ip地址：192.168.190.246
tun0 ip地址：172.19.0.1

研究了一下，VPNHotspot应用应该也是通过配置路由表和iptables规则来实现的，相关的命令在mobile/src/main/java/be/mygod/vpnhotspot/net/Routing.kt 中找到了一些线索，但不是很清楚具体执行了哪些命令
应该是通过ip rule、ip route和iptables命令去完成的配置，请问如果是上面的例子，具体的命令是哪些呢
感谢！！！

**Comment by Mygod** [comment]
Use this app instead.

**Comment by burg1ar** [comment]
你好，主要是想学习和研究一下路由和iptables配置，可以给一些提示或是思路吗？我在google上搜了很多，也试了很多配置，没有一个成功的，感谢
