### ISSUE TITLE
failed to create P2P group

### ISSUE THREAD

**Issue by offferu** [Mygod/VPNHotspot#4]
cannot open, force close

see below photos
![screenshot_20180202-224653](https://user-images.githubusercontent.com/34037165/35742308-04338842-0875-11e8-9e2e-a9e1601075b5.png)
![screenshot_20180202-232209](https://user-images.githubusercontent.com/34037165/35742310-0472c53e-0875-11e8-855b-375fe3356141.png)
![screenshot_20180202-230838](https://user-images.githubusercontent.com/34037165/35742311-04b0c2d0-0875-11e8-9f15-12016c2dc85b.png)

**Comment by offferu** [comment]
tether works fine, but wifi repeater fails. Used 2.4G

**Comment by Mygod** [comment]
There are no kernel requirements but that error means that it's probably a bug in your custom ROM. This app requires Wi-Fi direct feature. I'd suggest you report this bug to your ROM developer and/or try different ROMs.

**Comment by Mygod** [comment]
Logcat?

**Comment by Mygod** [comment]
By the way, I could try to debug this issue if you could grab a system-wide logcat (meaning not using that button in the app) after reproducing this issue. But I highly suspect that it's a bug in your system and there's nothing I can do about it.

**Comment by offferu** [comment]
--------- beginning of main
02-03 07:45:17.519 26685 26685 W System  : ClassLoader referenced unknown path: /data/app/be.mygod.vpnhotspot-1/lib/arm
02-03 07:45:17.592 26685 26685 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-03 07:45:17.876 26685 26685 D android.widget.GridLayout: horizontal constraints: x3-x0>=1327, x3-x2<=342, x2-x1<=28, x1-x0<=363 are inconsistent; permanently removing: x3-x2<=342. 
02-03 07:45:17.894 26685 26707 I Adreno  : QUALCOMM build                   : a5b4970, If5818605d9
02-03 07:45:17.894 26685 26707 I Adreno  : Build Date                       : 10/12/16
02-03 07:45:17.894 26685 26707 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
02-03 07:45:17.894 26685 26707 I Adreno  : Local Branch                     : N24D
02-03 07:45:17.894 26685 26707 I Adreno  : Remote Branch                    : 
02-03 07:45:17.894 26685 26707 I Adreno  : Remote Branch                    : 
02-03 07:45:17.894 26685 26707 I Adreno  : Reconstruct Branch               : 
02-03 07:45:17.900 26685 26707 I OpenGLRenderer: Initialized EGL, version 1.4
02-03 07:45:17.900 26685 26707 D OpenGLRenderer: Swap behavior 1
02-03 07:45:22.057 26685 26690 I art     : Do partial code cache collection, code=19KB, data=30KB
02-03 07:45:22.057 26685 26690 I art     : After code cache collection, code=19KB, data=30KB
02-03 07:45:22.057 26685 26690 I art     : Increasing code cache capacity to 128KB
02-03 07:45:22.316 26685 26707 D OpenGLRenderer: endAllActiveAnimators on 0x96760000 (RippleDrawable) with handle 0x96746c50
02-03 07:47:50.320 26685 26685 D android.widget.GridLayout: horizontal constraints: x3-x0>=1328, x3-x2<=342, x2-x1<=28, x1-x0<=363 are inconsistent; permanently removing: x3-x2<=342. 
02-03 07:47:52.106 26685 26690 I art     : Do partial code cache collection, code=41KB, data=60KB
02-03 07:47:52.106 26685 26690 I art     : After code cache collection, code=41KB, data=59KB
02-03 07:47:52.108 26685 26690 I art     : Increasing code cache capacity to 256KB

BTW, For the custom ROM, I /data /cache in F2FS. /system is ext4.

**Comment by Mygod** [comment]
Please read again the instructions. FS has nothing to do with this.
