### ISSUE TITLE
不使用vpn无法进行无线中继

### ISSUE THREAD

**Issue by tianyankai** [Mygod/VPNHotspot#40]
不使用vpn进行无线中继会使连接中继的另外的手机无法联网

**Comment by Mygod** [comment]
Disable strict mode.

**Comment by tianyankai** [comment]
已禁用，但是并没有变化

**Comment by tianyankai** [comment]
请问我该怎么做？

**Comment by Mygod** [comment]
Assuming the log `6801308388329663582` belongs to you, please reboot your device or use clean/reapply routings in settings.

**Comment by Mygod** [comment]
We have also confirmed that this issue exist on Android 9.0. A fix is in progress.

**Comment by Mygod** [comment]
Please try 2.0.x.
