### ISSUE TITLE
Failed to launch root daemon Android 13 beta 4

### ISSUE THREAD

**Issue by undermark5** [Mygod/VPNHotspot#402]
Updated my Pixel 5a to the latest Android 13 beta, app fails to launch root daemon when trying to enable.

[vpnhotspot-5206572349298222530.log](https://github.com/Mygod/VPNHotspot/files/9244021/vpnhotspot-5206572349298222530.log)

**Comment by JetSetDoritos** [comment]
I'm sure this was expected, but this is also failing on Android 13 stable that released today.  Pixel 6

[vpnhotspot-7603266174956257743.log](https://github.com/Mygod/VPNHotspot/files/9347598/vpnhotspot-7603266174956257743.log)

**Comment by Mygod** [comment]
Yes people. Android 13 is only supported by v2.14+. F-droid releases are unofficial and unsupported.
