### ISSUE TITLE
Host device loses data connection after sharing (Android 12)

### ISSUE THREAD

**Issue by worksbytk** [Mygod/VPNHotspot#414]
I'm running into an odd problem - after I activate the WiFi Hotspot via the app, activate the wlan0 option that comes up (for carrier circumvention), and a client connects, the host phone loses its data connection and the status bar LTE/data icon along with it, while the client is able to access the internet just fine. Only until I cycle airplane mode is the host phone able to access the internet again. Calls, and presumably SMS, still go through though. 

Any idea what's breaking? I'm running Android 12 with carrier restrictions on tethering functionality.

**Comment by worksbytk** [comment]
https://github.com/nermur/no-tethering-restrictions

Data issue fixed by going through [this set of instructions](https://github.com/nermur/no-tethering-restrictions), though TTLs still need tweaking. Whether my cell provider detects hotspot usage remains to be seen.

**Comment by Mygod** [comment]
Try repeater/temporary hotspot instead.
