### ISSUE TITLE
[Feature request] Support using interface created by android's ndc as upstream

### ISSUE THREAD

**Issue by huyz-git** [Mygod/VPNHotspot#415]
On rooted devices, besides using android's VPNService, one can also create VPN by using android's `ndc` toolkit. An example is `wg-quick` cli which uses kernel wireguard module and `ndc` to create wireguard interface.
Currently `VPNHotspot` cannot detect these interfaces. 

A example reproduce procedure:
- Download tun2socks from here https://github.com/xjasonlyu/tun2socks/releases/tag/v2.4.1
- run these in root shell
```
./tun2socks-linux-arm64 -device tun2socks -interface wlan0 -proxy direct:// 
ip addr add 10.0.0.1/24 dev tun2socks
ip link set dev tun2socks up
ndc network create 11111 vpn 1
ndc network interface add 11111 tun2socks
ndc network route add 11111 tun2socks 0.0.0.0/0
ndc network route add 11111 tun2socks ::/0 unreachable
ndc network users add 11111 0-99999
```
Now all traffic will go through `tun2socks` interface. Here `tun2socks` just redirect `tun`'s traffic to `wlan0`, the device can access internet as usual.
However, `upstream` option in `VPNHotspot` cannot see `tun2socks`.
If type `tun2socks` manually into `VPNHotspot`'s upstream, then the client cannot access internet.

**Comment by Mygod** [comment]
How do you specify DNS with this approach?

**Comment by huyz-git** [comment]
> How do you specify DNS with this approach?

On android 9 or below, you can use `ndc resolver setnetdns` to set dns.
On android 10 or above, you have to write binder script to set dns.
Reference: https://github.com/WireGuard/wireguard-tools/blob/71799a8f6d1450b63071a21cad6ed434b348d3d5/src/wg-quick/android.c#L837

**Comment by Mygod** [comment]
I don't see why you need to complicate it this much when you can use Android's VpnService API.
