### ISSUE TITLE
Support for Android 4.1(API 16)?

### ISSUE THREAD

**Issue by skygate2012** [Mygod/VPNHotspot#43]
I have an old tablet running Android 4.1 which I want to share its mobile data with VPN to other devices. But when I'm trying to install the app it says error parsing package. Is it a bug or is that the app does not support older Android versions? If it's the latter issue, can you add support for older Android systems? My tablet has no adequate ROMs for newer Android versions.

**Comment by Mygod** [comment]
Various things (mainly routing rules) changed drastically in Android 5.0 and I don't have a rooted Android 4 device to test my app on and I don't plan to get one. And Wi-Fi direct features were introduced in various releases during Android 4.x cycles so features might be missing. Therefore, I'm not currently looking into making my app compatible with Android 4.x. If anyone wants to make a tested pull request, I'd happy to merge it.

**Comment by eliasildi** [comment]
![img_20181224_081300](https://user-images.githubusercontent.com/5501171/50394199-e9573f80-0753-11e9-93dc-f796ec3fe675.jpg)
![img_20181224_081335](https://user-images.githubusercontent.com/5501171/50394203-eeb48a00-0753-11e9-9137-9c0cd00bea46.jpg)

**Comment by eliasildi** [comment]
Mayby fdroid fail installs...

**Comment by blackzafiqz** [comment]
@skygate2012 install custom rom on your tablet.

**Comment by cdnstream** [comment]
Install a Custom ROM, it should do the trick.

**Comment by Mygod** [comment]
Coming into 2020, with the rest of the world moving on, there are fewer reasons than ever to support Android 4.

Looking forward, dropping support for Android 6.0 would be very useful due to its bugs.
