### ISSUE TITLE
Tethered Chromecast cannot be found in VPN

### ISSUE THREAD

**Issue by Massimo-B** [Mygod/VPNHotspot#449]
Chromecast cannot be found anymore when connected to VPN.

I'm managing VPN such as IPsec with [VpnCilla](https://play.google.com/store/apps/details?id=com.gmail.mjm4456.vpncilla). 
Now adding VPNHotspot it works great to share the VPN with all tethered devices. However when inside the VPN, the Android device cannot connect to the Chromecast anymore, eventhough all devices in the tethering Wifi are using the VPN.

[off-topic]: After Lineageos has it's own option to share VPN with tethered devices, I was looking for a way for non-Lineageos roms such as Xiaomi MIUI, finally found VPNHotspot which works great.

**Comment by Mygod** [comment]
#405
