### ISSUE TITLE
Per device VPN sharing 

### ISSUE THREAD

**Issue by 2dashing** [Mygod/VPNHotspot#463]
Dear developer, your app is unique and I appreciate it very much. Please is there a way you can make the VPN connection sharing per device basis? Some devices might need to maintain original default IP while others use the VPN connection same time the app is running. Thank you!

**Comment by worstperson** [comment]
I've looked in to this a little. If a setup a regular Android tether and run these commands (changing addresses and interfaces as necessary, names are Android 9+)
```
# Add an early policy rule to route traffic from 192.168.184.128-192.168.184.255 through tun0
ip rule add from 192.168.184.128/25 lookup tun0

# Insert a nat MASQUERADE rule for clients 192.168.184.128-192.168.184.255 going through tun0
# "iptables -t nat -A tetherctrl_nat_POSTROUTING -j MASQUERADE" would probably be fine too
iptables -t nat -I tetherctrl_nat_POSTROUTING -s 192.168.184.128/25 -o tun0 -j MASQUERADE

# Insert and append appropriate filter rules to pass traffic
iptables -t filter -I tetherctrl_FORWARD -i rndis0 -o tun0 -g tetherctrl_counters
iptables -t filter -I tetherctrl_FORWARD -i rndis0 -o tun0 -m state --state INVALID -j DROP
iptables -t filter -I tetherctrl_FORWARD -i tun0 -o rndis0 -m state --state RELATED,ESTABLISHED -g tetherctrl_counters
iptables -t filter -A tetherctrl_counters -i rndis0 -o tun0 -j RETURN
iptables -t filter -A tetherctrl_counters -i tun0 -o rndis0 -j RETURN
```
Traffic from 192.168.184.1-192.168.184.127 takes the standard route and 192.168.184.128-192.168.184.255 goes through tun0, but it's broken in some weird ways. Even though the traffic on rndis0 still has the standard 0x63 mark, packets to dnsmasq just drop for whatever reason. Setting an outside dns server works around this, but then there is an issue loading some pages, notably google.com.

Fairly sure I'm just overlooking something simple though.

**Comment by Mygod** [comment]
Good catch. Closing.
