### ISSUE TITLE
TETHER_ERROR_INTERNAL_ERROR

### ISSUE THREAD

**Issue by zjzbl** [Mygod/VPNHotspot#464]
![Screenshot_20230222-220947_VPN 热点](https://user-images.githubusercontent.com/34407927/220648421-2a31ca06-f2b9-45b5-80fd-9b4254eb7d39.png)

I have try reboot my device but doesn't work.

[Here's my log file](https://drive.google.com/file/d/155aLwHa3SQktLavbzAl3dWyj4PebuBg6/view?usp=drivesdk)

**Comment by Mygod** [comment]
Turn on tethering from your system settings instead.
