### ISSUE TITLE
Wi-Fi Hotspot and USB tethering immediately gets disabled when trying to share VPN

### ISSUE THREAD

**Issue by towlie** [Mygod/VPNHotspot#469]
Device Mi9TPro Android 11 on rooted device with stock MIUI 12 ROM

Steps to reproduce:
- Enable VPN within the MIUI VPN settings
- Try to enable Wi-Fi Hotspot or USB tethering 

<img src="https://user-images.githubusercontent.com/6986141/222979894-9e100af1-d62f-4c4d-8cb4-2bd5987f2351.jpg" width=40% height=40%>

Settings:
<img src="https://user-images.githubusercontent.com/6986141/222980061-6e636720-3e13-4b09-9118-588ec2f17c85.jpg" width=40% height=40%>

Log when trying to host Wi-Fi Hotspot:
[vpnhotspot-3478683802612503366.zip](https://github.com/Mygod/VPNHotspot/files/10892673/vpnhotspot-3478683802612503366.zip)

And when trying to use USB tether:
[vpnhotspot-5702397109616960764.zip](https://github.com/Mygod/VPNHotspot/files/10892674/vpnhotspot-5702397109616960764.zip)

**Comment by towlie** [comment]
Because I am not really sure how to use this app for sharing VPN connections I tried this one:
In this case I am using it without an active VPN connection (from system settings) on the phone but the IP address on the PC tells me that no VPN is being used. (Everything was done inside the app)

<img src="https://user-images.githubusercontent.com/6986141/222980922-166bbef1-30bd-4a7a-8fbf-98ace78b4b3e.jpg" width=40% height=40%>


<img src="https://user-images.githubusercontent.com/6986141/222980963-6e78be6f-dacf-4bbf-a12a-a97c2e161212.jpg" width=40% height=40%>


[vpnhotspot-3067126999163395446.zip](https://github.com/Mygod/VPNHotspot/files/10892730/vpnhotspot-3067126999163395446.zip)

**Comment by Mygod** [comment]
Turn on hotspot from system settings instead.
