### ISSUE TITLE
Can I set this option to automatically open when opening the app? 

### ISSUE THREAD

**Issue by zzduci** [Mygod/VPNHotspot#486]
Can I set this option to automatically open when opening the app? Every time I open the app, I need to manually open the option, otherwise VPN sharing will not take effect

![JKWWH)PXH{_)5WZWJ(NQ26](https://github.com/Mygod/VPNHotspot/assets/122016328/953f4962-72e3-4f2c-ac11-b029d4cd8202)

**Comment by Mygod** [comment]
Top right
