### ISSUE TITLE
Is the work principal of Temporary WIFI hotspot the same as a system WIFI hotspot(in VPN Hotspot app)

### ISSUE THREAD

**Issue by FebruaryVey** [Mygod/VPNHotspot#49]
When i create the pre-configured system WIFI hotspot in VPN Hotspot,it will show a interface that “Modify the prompt”([like this picture](https://ws3.sinaimg.cn/large/005BYqpggy1fxn26qddmmj30u01qg3zm.jpg), answer your last question，turning on system hotspots via system's UI dosent show this interface，maybe the system has allowed this in default).I allowed this and choosed the wlan0,the connected computer showed internet available but it cant load anything. While i create the Temporary hotspot,it won't show anything and work well.So i think they maybe worked via different ways.

my device is xiaomi 8，rom is miui10 based android pie，maybe the reason will exist in some particular device.If it is very trouble to solve it，can you add a new option that users can set custom hotspot password.

Finally, thanks the author for your hard work and making such a good work.

**Comment by Mygod** [comment]
Make sure you have disabled hardware tethering offload. Otherwise export debug information.

**Comment by FebruaryVey** [comment]
The software I use is v2ray, and it seems to have disappeared after the recent MIUI10 system update, so I think it may be a problem with my individual system instead of the software itself. Now it works fine, thanks for your help.
