### ISSUE TITLE
Request to add 2 direct sub-activities 

### ISSUE THREAD

**Issue by atsrxL** [Mygod/VPNHotspot#509]
Hi @Mygod 

I'm using this app on my old phone with borken touchscreen  to provide great-wall less network , its useful but on my phones "auto restart service" is not working , I'm not sure its only my problem or not. 

Currently I'm using tasker to auto open and tap the button to make it useable after reboot.
So can you please add two simple activities that can turn on "wlan hotspot" and turn on that allow grant vpn services on "ap" , it would be helpful to select wthin takser.

Thank you.

**Comment by Mygod** [comment]
No plan for this. Starting any activity from the app should also auto start services.
