### ISSUE TITLE
Automatically enable vpn hotspot for system hotspot via in-app control or quick settings tile

### ISSUE THREAD

**Issue by hjkcai** [Mygod/VPNHotspot#513]
When I wanted to open my hotspot with vpn enabled, I have to turn on two toggles: one for the hotspot itself, one for the vpn upstream. How can I enable vpn upstream right after hotspot is enabled without extra interaction? It will be awesome if this can be done via quick settings tile. Thanks!

![image](https://github.com/Mygod/VPNHotspot/assets/731326/1ae63c17-affa-45fd-af2f-c7626676b5a7)

**Comment by Mygod** [comment]
top right

**Comment by hjkcai** [comment]
Sorry and thanks. I didn't expect the "eye" icon to be a "monitor" feature. I never tried to click that (Facepalm.gif)
