### ISSUE TITLE
"system/bin/ip rule add iif" bug

### ISSUE THREAD

**Issue by Biftor** [Mygod/VPNHotspot#515]
Hi,
I have been using your amazing working, since long time ago
recently i have just updated the app and i am getting issues
`system/bin/ip rule add iif swlan0 unreachable priority 17980 exited with...`
it's good to mention version [2.16.6](https://github.com/Mygod/VPNHotspot/releases/tag/v2.16.6) is working, i've just downgraded to it.
Have restarted phone, uninstall re install and also i dont have other vpn hotspot apps
nothing worked, just downgraded to 2.16.6.
My phone is Android 9, samsung
If you need further informations, such as logcat ask me, i have attached error screen shot.

![IMAGE 2023-10-17 03:20:37](https://github.com/Mygod/VPNHotspot/assets/7228469/68714d35-a6d1-49d0-ae21-d54cf066a51b)

Regards,
Armin

**Comment by Mygod** [comment]
Export debug information for starters. I am really surprised that downgrading solved the issue since there were no routing related changes since v2.16.6. https://github.com/Mygod/VPNHotspot/compare/v2.16.6...v2.16.9

**Comment by Biftor** [comment]
Yes i have tested again, 2.16.6 is working
but higher version not working

it seems it has permission problems.

logs from lates GP version
[vpnhotspot-3980746801774074243.log](https://github.com/Mygod/VPNHotspot/files/12922924/vpnhotspot-3980746801774074243.log)

**Comment by Mygod** [comment]
How about 2.16.7/8?

**Comment by Biftor** [comment]
> How about 2.16.7/8?

they are not working
any versions after 2.16.6, are not working and have same issues

**Comment by Mygod** [comment]
Okay then this is most likely caused by the fix for #504. Will give you an apk to test later.

**Comment by Mygod** [comment]
Can you try this apk and see what you get? https://github.com/Mygod/librootkotlinx/releases/download/v1.1.0/app-release.apk

**Comment by Biftor** [comment]
Here you are
LaunchException
failed to launch root daemon
my phone is rooted and permission granted to the app

@Mygod 

![IMAGE 2023-10-19 04:14:52](https://github.com/Mygod/VPNHotspot/assets/7228469/0ec456f5-95aa-4997-94ee-2f481bf2aa88)

**Comment by Mygod** [comment]
Hmm that's the entire thing? It doesn't scroll?

**Comment by Mygod** [comment]
I guess not. Stupid me.

**Comment by Mygod** [comment]
Try this? https://github.com/Mygod/librootkotlinx/releases/download/v1.1.0/app-release2.apk

**Comment by Biftor** [comment]
> Try this? https://github.com/Mygod/librootkotlinx/releases/download/v1.1.0/app-release2.apk

![IMAGE 2023-10-
![IMAGE 2023-10-19 04:58:48](https://github.com/Mygod/VPNHotspot/assets/7228469/8cd102ae-5743-4d3c-a578-c095568e1bcb)
19 04:58:39](https://github.com/Mygod/VPNHotspot/assets/7228469/26c2ac47-ec49-40f6-bef8-97c20fff9382)

**Comment by Biftor** [comment]
@Mygod 
![IMAGE 2023-10-19 05:00:24](https://github.com/Mygod/VPNHotspot/assets/7228469/a63c0a45-c553-4b2b-875d-c7573fc9398a)

2nd

![IMAGE 2023-10-19 05:00:41](https://github.com/Mygod/VPNHotspot/assets/7228469/6034a37d-ec1b-44ea-8d2c-581a9e9a13ad)

**Comment by Biftor** [comment]
If it is only my bug, feel free to skip it, i can use 2.16.6 it is working for me.
i know how annoying bug fixing specially such bug fixing is :-))

**Comment by Mygod** [comment]
I am really stupid. Try this: https://github.com/Mygod/librootkotlinx/releases/download/v1.1.0/app-release3.apk

**Comment by Biftor** [comment]
@Mygod 

![IMAGE 2023-10-19 06:18:31](https://github.com/Mygod/VPNHotspot/assets/7228469/6634939d-48cc-4880-b85c-87c42a105fff)

**Comment by Mygod** [comment]
Good so this should fix your issue then. Look forward to next release (v2.16.10 presumably).

**Comment by Mygod** [comment]
https://github.com/Mygod/VPNHotspot/releases/tag/v2.16.10 should fix it for you hopefully.

**Comment by Biftor** [comment]
Thank you for your attentions, [it fixed ](https://github.com/Mygod/VPNHotspot/releases/tag/v2.16.10) 👍
