### ISSUE TITLE
emui9.1 uses VPN hotspot, ipv4 and ipv6 dns addresses change randomly every time

### ISSUE THREAD

**Issue by yixuan-Q** [Mygod/VPNHotspot#528]
![Screenshot_20240102_191226](https://github.com/Mygod/VPNHotspot/assets/61373853/404f5ec8-55e9-4551-a2f0-4a320c0c99da)

![Screenshot_20240102_191240](https://github.com/Mygod/VPNHotspot/assets/61373853/7b839408-e847-49c3-9aec-bdf392c65cf3)
VPN hotspot version 2.16.10-g

**Comment by Mygod** [comment]
#193
