### ISSUE TITLE
Route all tethering to vpn by default

### ISSUE THREAD

**Issue by imShara** [Mygod/VPNHotspot#53]
Need possibility to apply routing rules when any tethering enables. Or QuickSettingsTile which enables wifi tethering and apply rules.

**Comment by Mygod** [comment]
Monitoring tethering changes require the app to be constantly running, which is undesirable. I would suggest use the "Repeater" tile of this app as a shortcut to this app's tethering management activity.

**Comment by imShara** [comment]
My phone doesn't support Repeater and this tile doesn't work. But anyway, it's unclear and requires too many taps. If you already have root privelegues, you can make alternative "WIFI Tethering" QSTile, which enables/disables tethering and vpnhotspot at same time

**Comment by Mygod** [comment]
That's certainly possible to do. I'm already doing them in this app. I guess I can add 3 more shortcuts.

**Comment by imShara** [comment]
Tried to investigate by myself. There is problem with legacy wifi tethering switch:

1. If tethering disabled in system - switch will enable it (and it's working), but not detects wlan interface even if app restarted. Switch still greyout.

2. If tethering enabled in system, app detects wlan interface, legacy switch is active. It can disable tethering and detects that tethering disabled. No more wlan in list, switch becomes grey. If you try to toggle switch now - look at #1

Android 7.1.2

**Comment by Mygod** [comment]
2.1.0 is released. Check out the new quick settings tiles and see if that works for you.

**Comment by tenwx** [comment]
能不能支持下桌面小工具？多谢了

**Comment by imShara** [comment]
Thanks! Will donate today or tomorrow.

> Check out the new quick settings tiles and see if that works for you.

Tiles exists but switching problems still here. I mean I shoud make tests, logs and create new issue

**Comment by Mygod** [comment]
Oh sorry I missed that comment about legacy switches. Does non-legacy version work for you? If so, just use that one instead.

**Comment by Mygod** [comment]
@imShara I just checked and indeed that switch would cause the issue you described for Android 7.x. The bug is related to Android system and there's nothing I can do about it. I'd suggest simply avoid using it.

**Comment by Mygod** [comment]
I will add another feature that enables you to monitor tethered interfaces and route its tethering to VPN automagically in 2.3.

**Comment by sollermun** [comment]
> I will add another feature that enables you to monitor tethered interfaces and route its tethering to VPN automagically in 2.3.

Mygod,  can you provide a quick tutorial on how to use this feature in the app? It sounds like the solution to a problem I have. I want the route usb tether to VPN at all times and to reroute if the connection is temporarily broken for whatever reason, e.g. the cable is unplugged and plugged back in or VPN disconnects and reconnects. Thanks for your hard work! Love your program and us it every day.

**Comment by Mygod** [comment]
@sollermun You can use the monitor feature. After USB tethering is on, click on the eye icon on the top right.
