### ISSUE TITLE
lateinit property transaction has not been initialized (on ap0 / swlan0)

### ISSUE THREAD

**Issue by binbard** [Mygod/VPNHotspot#534]
I have Samsung Galaxy series. It shows swlan0 instead of ap0.
While turning it on, it shows this snack message.

 
<img src="https://github.com/Mygod/VPNHotspot/assets/28684962/94521972-bbde-4d84-9de9-9d578eb065a1" height="600">

**Comment by Mygod** [comment]
Fixed in 4410817.
