### ISSUE TITLE
No puedo instalar?

### ISSUE THREAD

**Issue by eliasildi** [Mygod/VPNHotspot#54]
![screenshot_2018-12-24-06-53-51](https://user-images.githubusercontent.com/5501171/50392749-db4ff180-0748-11e9-9333-c34e9ab0e3f1.png)

Si exporto el APK desde otro teléfono si puedo, pero desde Fdroid en mi teléfono no me deja

**Comment by Mygod** [comment]
Hey you seem to be using Android 4, which is not supported (see #43). If I am mistaken, let me know.

**Comment by Mygod** [comment]
My apologies. This turns out to be related to #55. Thank you for your report. It will be fixed in the next release.
