### ISSUE TITLE
Move check update from bottom navigation bar to settings

### ISSUE THREAD

**Issue by BinTianqi** [Mygod/VPNHotspot#544]
![ResizedImage_2024-03-07_10-48-49_9117.png](https://github.com/Mygod/VPNHotspot/assets/146811279/ffb6a8c6-5c62-4622-86fd-83f5b0b71e1c)

I don't want to be disturbed by this icon checking for updates.

This icon should appear in the settings. If not, it should only check for stable release

**Comment by Mygod** [comment]
Install from Google Play and do not opt into beta channel instead.
