### ISSUE TITLE
Please restart your device for VPN tethering to work

### ISSUE THREAD

**Issue by soccerboys2008** [Mygod/VPNHotspot#549]
When trying to use the repeater on version 2.17.4-g I'm met with this error

tried restarting my device, 
clearing the app storage, 
and reinstalling the app 

nothing worked till I downgraded to 2.16.11 and everything was fine (then disabled auto update in play store, probably got auto updated from really old version)

![Screenshot_20240312-013359_Settings](https://github.com/Mygod/VPNHotspot/assets/29149297/e3171c72-3794-4c72-8832-6a5daf2f5f85)
![Screenshot_20240312-013331_VPN Hotspot](https://github.com/Mygod/VPNHotspot/assets/29149297/08ac4974-dc38-4250-bd36-a72cbd60d2e4)

Device info:
![Screenshot_20240312-015129_Settings](https://github.com/Mygod/VPNHotspot/assets/29149297/e7dfa087-bfd4-4ec0-9fe3-d2a76614cd5f)

**Comment by Mygod** [comment]
Hi what VPN are you using? Can you export debug information on v2.17 and send it to me?

**Comment by hellobbn** [comment]
Hi, I am having the same problem. Here is the debug log.

I toggled the Repeater switch on and off, and captured the log.
The VPN I have been using  is sing-box (https://play.google.com/store/apps/details?id=io.nekohasekai.sfa)

[vpnhotspot-2535350892380703906.log](https://github.com/Mygod/VPNHotspot/files/14574973/vpnhotspot-2535350892380703906.log)

**Comment by Mygod** [comment]
Hi @hellobbn does rebooting solve the issue?

**Comment by Mygod** [comment]
Make sure you are reporting after you see this prompt again after reboot. Do not uninstall the app.

**Comment by hellobbn** [comment]
Hi @Mygod , I can confirm that rebooting does not solve the issue.

**Comment by Mygod** [comment]
@hellobbn Does the following steps help?
1. Disable VPN.
2. Reboot the device.
3. Start VPN tethering.
4. Enable VPN.

**Comment by hellobbn** [comment]
Hi, if I start VPN tethering before enabling VPN, the error message no longer shows. However, it seems the traffic is not going through VPN, either.

**Comment by Mygod** [comment]
@hellobbn Okay, are you saying you did those steps without rebooting the device and the error no longer shows? Can you export debug information while VPN and tethering are all active?

**Comment by soccerboys2008** [comment]
i use pia, however pia is currently having a nationwide issue in us starting about 4 - 6 hours ago

however i can use the repeater without a vpn until they get there stuff figured out

i will upgrade the app quick and grab the debug info

**Comment by Mygod** [comment]
This warning should only pop up if you use a VPN along with tethering but you can try that and see how it goes too.

**Comment by soccerboys2008** [comment]
hmm, just noticed that verison works without the vpn (naked as i like to call it), but when connected to pia (even though it currently has network issues) the issue reappears

thats probably why reboot didn't work, cause every time you connect the vpn the error appears

exported debug (before reboot):
[vpnhotspot-7265846459898467798_021801.log.txt](https://github.com/Mygod/VPNHotspot/files/14577655/vpnhotspot-7265846459898467798_021801.log.txt)

just tried reboot and same issue, no error naked though

exported degug (after reboot, before running naked was included):
[vpnhotspot-5674043189770050290_023006.log.txt](https://github.com/Mygod/VPNHotspot/files/14577727/vpnhotspot-5674043189770050290_023006.log.txt)

exported degug (after reboot, after/during running naked was included):
[vpnhotspot-2945051092799165850_022935.log.txt](https://github.com/Mygod/VPNHotspot/files/14577742/vpnhotspot-2945051092799165850_022935.log.txt)

i'll need to downgrade again once pia gets there issues resolved (can connect but spotty connections / slow internet, not related to this app)

**Comment by soccerboys2008** [comment]
also the reason i had to downgrade last night (before these vpn issues), is i was getting no network access following the order i usually use. after the downgrade everything worked again

**Comment by Mygod** [comment]
@soccerboys2008 Thanks for the logs! It appears that in the last log you sent everything seems working fine. If you try my order now, does the error message reappear? (Disregard the connectivity issue since you said your VPN is not working.)

**Comment by soccerboys2008** [comment]
> @soccerboys2008 Thanks for the logs! It appears that in the last log you sent everything seems working fine. If you try my order now, does the error message reappear? (Disregard the connectivity issue since you said your VPN is not working.)
> 
> EDIT: What I mean is that 1. start VPN tethering 2. start VPN 3. turn off VPN tethering and on again 4. export debug information.


rebooted device and did that in that exact order (same issue), here log:
[vpnhotspot-2936274959345153651_025703.log.txt](https://github.com/Mygod/VPNHotspot/files/14578008/vpnhotspot-2936274959345153651_025703.log.txt)

**Comment by hellobbn** [comment]
I tried the following:

On new version:
Disable VPN -> Reboot -> Enable VPN Tethering -> Enable VPN: No warning, VPN not seem to work properly
Log(Please ignore the crashed vibrator thing in the logs)
[new.log](https://github.com/Mygod/VPNHotspot/files/14578009/new.log)


On Old version v2.16.11:
Disable VPN -> Reboot -> Enable VPN Tethering -> Enable VPN: Working properly
[old.log](https://github.com/Mygod/VPNHotspot/files/14578010/old.log)

Not sure if it is the same problem. If not, I can open a new issue.

**Comment by soccerboys2008** [comment]
when i said same issue, it appeared at step 3 "3. turn off VPN tethering and on again" (specifically when it was turned on again)

**Comment by soccerboys2008** [comment]
pia is back online, i restarted and grabbed one more log following these steps (jic you want it), before i downgrade again:

> @soccerboys2008 Thanks for the logs! It appears that in the last log you sent everything seems working fine. If you try my order now, does the error message reappear? (Disregard the connectivity issue since you said your VPN is not working.)
> 
> EDIT: What I mean is that 1. start VPN tethering 2. start VPN 3. turn off VPN tethering and on again 4. export debug information.

let me know if you want that one too

**Comment by Mygod** [comment]
```
      10198  HAPPY_BOX_MATCH RESTRICTED_MATCH IIF_MATCH tun0
```

Okay I feel like the issue here is that the `uids_allowed_on_restricted_networks` global setting is somehow not being used/respected by system, causing system to block DNS traffic from VPN Hotspot. 🤔 (Since v2.17, VPN Hotspot handles tethering DNS instead of offloading it to the primary DNS server.)

@hellobbn What is your device? I can see that you are running Android 14. Is it stock or custom ROM?

**Comment by soccerboys2008** [comment]
i have another oneplus 5 thats on lineageos 21 (android 14), with everything installed if it can help

(the oneplus 5 in the screenshots i've been too lazy to update, which is why its on lineage os 20 (android 13))

**Comment by Mygod** [comment]
Hi can you guys try [this apk](https://github.com/Mygod/pogoplusle/releases/download/debug/vpnhotspot-v2.17.5-debug.apk)? It should hopefully work on Android 13+.

**Comment by Mygod** [comment]
Fixed some bugs and should hopefully work on any Android version: https://github.com/Mygod/pogoplusle/releases/download/debug/vpnhotspot-v2.17.5-debug2.apk

**Comment by soccerboys2008** [comment]
new error appeared (no internet access, and no internet access from connected devices)
![Screenshot_20240312-213853_VPN Hotspot_094128](https://github.com/Mygod/VPNHotspot/assets/29149297/53cd5fa3-13ee-49b9-9d3f-f2d4bbce4d88)

here's the debug log:
[vpnhotspot-2389545170582576160_094038.log.txt](https://github.com/Mygod/VPNHotspot/files/14581214/vpnhotspot-2389545170582576160_094038.log.txt)

**Comment by Mygod** [comment]
Hmm I couldn't download the log...

**Comment by soccerboys2008** [comment]
ill try again then:

[vpnhotspot-2389545170582576160_094038.log.txt](https://github.com/Mygod/VPNHotspot/files/14581244/vpnhotspot-2389545170582576160_094038.log.txt)

**Comment by Mygod** [comment]
Did you download and install the debug2 version?

**Comment by soccerboys2008** [comment]
yes, im getting same error on the link i just sent imma upload a google drive link:

https://drive.google.com/file/d/1XgnTuTGpJJslxNGtf4NaRRJo0AFhB6a5/view?usp=sharing

**Comment by Mygod** [comment]
Thanks for the logs but I am pretty sure that's not debug2 version. Try this apk? https://github.com/Mygod/pogoplusle/releases/download/debug/vpnhotspot-v2.17.5-debug2.apk

(I will double check this apk meanwhile.)

**Comment by soccerboys2008** [comment]
ok it seems the first one i installed was only 3mb (probably an incomplete download leading to that error) anyway here is the log and screenshots (same as the original error):
[vpnhotspot-8812612977146599456_100343.log.txt](https://github.com/Mygod/VPNHotspot/files/14581411/vpnhotspot-8812612977146599456_100343.log.txt)

![Screenshot_20240312-220030_VPN Hotspot_100431](https://github.com/Mygod/VPNHotspot/assets/29149297/23188e77-ee59-4c7b-b96a-9987a0f1e380)
![Screenshot_20240312-220115_Settings_100425](https://github.com/Mygod/VPNHotspot/assets/29149297/a3be46d8-6c02-4e8d-94f9-4085172e4b0e)

p.s. i'm getting an issue with viewing the log with 404 not found using the preview if you have an error let me know and ill send a drive link

**Comment by Mygod** [comment]
Great please google drive the logs :)

**Comment by soccerboys2008** [comment]
https://drive.google.com/file/d/1XiTqTeG77vnROjzuXAq3LE3yym6DROJc/view?usp=sharing

**Comment by Mygod** [comment]
Hmm I think your ROM might be not fully upgraded to Android 13 and that could be causing the issue. Do you have the file `/apex/com.android.tethering/javalib/service-connectivity.jar` and if so, can you send it to me?

**Comment by Mygod** [comment]
Meanwhile this might fix the issue: https://github.com/Mygod/pogoplusle/releases/download/debug/vpnhotspot-v2.17.5-debug3.apk

**Comment by soccerboys2008** [comment]
just sending drive links now, not gonna try to send attachments

https://drive.google.com/file/d/1--mc25VqTd5W9DsNwT0YAF9RBo3kv0X7/view?usp=sharing

**Comment by soccerboys2008** [comment]
this made me remember that pia manages its own dns (may play a part (as in conflict of interest) or maybe not)

> ```
>       10198  HAPPY_BOX_MATCH RESTRICTED_MATCH IIF_MATCH tun0
> ```
> 
> Okay I feel like the issue here is that the `uids_allowed_on_restricted_networks` global setting is somehow not being used/respected by system, causing system to block DNS traffic from VPN Hotspot. 🤔 (Since v2.17, VPN Hotspot handles tethering DNS instead of offloading it to the primary DNS server.)
> 
> @hellobbn What is your device? I can see that you are running Android 14. Is it stock or custom ROM?

![Screenshot_20240312-221949_PIA VPN](https://github.com/Mygod/VPNHotspot/assets/29149297/66b259b9-2689-40b2-8721-3cae6aa9d914)

anyway imma test debug 3 now

**Comment by Mygod** [comment]
That doesn't matter. :)

**Comment by soccerboys2008** [comment]
![Screenshot_20240312-223509_VPN Hotspot](https://github.com/Mygod/VPNHotspot/assets/29149297/1ebcd826-7a50-48f2-bb77-b45cb35f7032)

https://drive.google.com/file/d/1-NsTCYZGTlNG6IrlWVLY_S8_H65uJNEh/view?usp=sharing

**Comment by soccerboys2008** [comment]
does my service-connectivity.jar file look ok

**Comment by Mygod** [comment]
Yeah this was my fault. I wrote a bug. debug4: https://github.com/Mygod/pogoplusle/releases/download/debug/vpnhotspot-v2.17.5-debug4.apk

**Comment by soccerboys2008** [comment]
fixed

**Comment by soccerboys2008** [comment]
works on android 14 too (different oneplus 5 with lineage 21)

**Comment by hellobbn** [comment]
Hi, I can confirm this works.

And I am also using Lineage OS, so I suspect this is something related to the OS, because it does introduced something like firewall in the connectivity apex.

If this problem is ROM's side, can you provide some more detailed information about the issue?

**Comment by Mygod** [comment]
Sure. Essentially I am trying to grant this app [restricted network permission](https://android.googlesource.com/platform/packages/modules/Connectivity/+/android-14.0.0_r1/service/src/com/android/server/connectivity/PermissionMonitor.java#525) which allows it to serve downstream DNS traffic bypassing Android VPN firewall. The way the app does this is essentially running `settings put global uids_allowed_on_restricted_networks <app uid>`.

Looking at your logs, it seems like the global settings was updated properly and looking at the system jar from @soccerboys2008, the system does look at this settings key. However, somehow the permission is still not granted to the app for some reason. 🤔

**Comment by Mygod** [comment]
Yeah that is definitely responsible. Why would they do this?

**Comment by soccerboys2008** [comment]
i run plain lineage os (lineageos.org), so its probably an upstream issue

**Comment by soccerboys2008** [comment]
its upstream: https://review.lineageos.org/c/LineageOS/android_packages_modules_Connectivity/+/369208

**Comment by hellobbn** [comment]
The firewall feature is "ported" from the CalyxOS to LineageOS. And here is the word from the developer which may answer @Mygod :
> hey, thanks for sharing this. i'm 90% sure it's a bug in the firewall implementation. that uids_allowed_on_restricted_networks list was previously used by the firewall implementation (too) to track whether or not to allow network access for an application. the new implementation uses a uid policy instead, POLICY_REJECT_ALL, for that. it's very likely there was an oversight on my part in the new implementation that causes it to not even pay attention to uids_allowed_on_restricted_networks at all anymore. i'll need to mess with it a bit, but i do think it's something that i want to get fixed 
> actually, not sure yet, but this commit might be responsible (on the calyxos side anyway): https://review.calyxos.org/c/CalyxOS/platform_packages_modules_Connectivity/+/21480/7
> it was created for a good reason in the previous implementation - to prevent apps from being given too much permission simply for being allowed to use the internet. but it may not be applicable with the new implementation. i'll have to check.

**Comment by Mygod** [comment]
@Uldiniad Please explain your commit? How does LineageOS/CalyxOS even pass [CTS tests](https://github.com/LineageOS/android_packages_modules_Connectivity/blob/250a7f26788c9cc2926269e8d0eaaf29653b82a1/tests/cts/net/src/android/net/cts/ConnectivityManagerTest.java#L3306C17-L3306C52) with this? Do you guys even run CTS tests? 🤔

**Comment by Uldiniad** [comment]
> @Uldiniad Please explain your commit? How does LineageOS/CalyxOS even pass [CTS tests](https://github.com/LineageOS/android_packages_modules_Connectivity/blob/250a7f26788c9cc2926269e8d0eaaf29653b82a1/tests/cts/net/src/android/net/cts/ConnectivityManagerTest.java#L3306C17-L3306C52) with this? Do you guys even run CTS tests? 🤔 

We don't test CTS and have no reason to

**Comment by t-m-w** [comment]
Hey, chiming in here since I apparently helped start a back-and-forth.

There is an issue open about this on the CalyxOS side, so it's on our radar. It's already been linked, but one more time in case anyone missed it: https://gitlab.com/CalyxOS/calyxos/-/issues/2192

To be fair, the particular setting we're talking about here isn't one that the majority of users will ever encounter at all, so it hasn't been a focus of manual testing, and this is the first time I've seen this issue come up. Please correct me if I'm wrong on this, but from my perspective, it's very niche.

Custom ROMs tend to have a number of added features and intentional behavior-altering framework changes that would require CTS tests to be modified in order to pass. This has been done in some cases, but it can be time-consuming and hasn't yet been done in all cases. With CalyxOS, in my experience at least, CTS tests are run for some things (e.g. WebView), and particularly they are run when modifying sensitive code, but it's done selectively, not yet run for absolutely everything.

Affected OSes don't ship releases with Google Mobile Services included, so it's not like there's a *requirement* to have all CTS tests pass, but of course it would be nice.

[LineageOS](https://review.lineageos.org) and [CalyxOS](https://review.calyxos.org) are open-source projects, so anyone can contribute code to solve issues like this, or can [report issues](https://gitlab.com/CalyxOS/calyxos/-/issues) and we'll do what we can.

Thanks!

**Comment by Mygod** [comment]
Thanks for the explanations! However, I'm unsure if changing CTS tests is the right thing to do since the whole point of CTS tests is to ensure compatibility. Also I guess you are probably legally not allowed to advertise your product with Android name if CTS tests do not pass: https://source.android.com/docs/compatibility/compatibility-faq#is-compatibility-mandatory

Anyway back to the topic, I don't think that commit is necessary since only system apps and shell can modify `uids_allowed_on_restricted_networks` as far as I'm concerned.
