### ISSUE TITLE
failed installing latest version from F-droid

### ISSUE THREAD

**Issue by pupyc** [Mygod/VPNHotspot#55]
Message: 

> Error installing VPN Hotspot
> Parsing apk file failed!Maybe minSdk of apk is lower than current Sdk?Look into logcat for more specific warning of Android's PackageParser

F-droid version: 1.5-alpha2
Android version: 9.0
old VPNHotspot version: 2.0.4
new VPNHotspot version: 2.0.7

**Comment by Mygod** [comment]
Can you look into logcat?
