### ISSUE TITLE
[Bug] TETHER_ERROR_INTERNAL_ERROR

### ISSUE THREAD

**Issue by ZhymabekRoman** [Mygod/VPNHotspot#551]
Hi there. Thanks for the project. I was using VPN Hotspot with MIUI Android 12 and there is like no errors (probably because I used old version). But after flashing CRDroid Android 13, this happens when trying to create WIFI hotspot:

![Screenshot_20240318-084316_VPN Hotspot](https://github.com/Mygod/VPNHotspot/assets/61125068/b313611e-6605-44fd-bb42-502e0a0f41f3)

After pressing toggle, it's actually creates WIFI hotspot, but without toggle changes, but after doing second toggle press, application just throws error.

Log:
[vpnhotspot-2780145061138802093.log](https://github.com/Mygod/VPNHotspot/files/14637754/vpnhotspot-2780145061138802093.log)

**Comment by Mygod** [comment]
Ignore that error and use system hotspot toggle instead.
