### ISSUE TITLE
Static Temporary HotSpot Name and Password

### ISSUE THREAD

**Issue by kingarawana** [Mygod/VPNHotspot#56]
Hey guys,

Is it possible to set a default temporary WIFI name and password?

Every time I enable the Temporary WIFI it changes the WIFI name and password. It's kind of a hassle to have to keep finding the new name and entering the password. 

For example my current WIFI name and password is AndroidShare_9953, pw: 1ee912c1330. If I use it again later, it changes to something else.

I know it'll probably take time to make the update, but can someone show me where in the code I could hack it so that I can enter a static WIFI name and password?

Thanks!

**Comment by Mygod** [comment]
https://github.com/Mygod/VPNHotspot/issues/20#issuecomment-388635123:
> Use system tethering instead. And yes I'm not sure how to specify credentials for temporary hotspot for now but I'd suggest if that's what you want, you might want to use system Wi-Fi hotspot instead.

**Comment by kingarawana** [comment]
Hey @Mygod ,

But when I use system WIFI, it doesn't route traffic from my tethered devices through my VPN. When I have my VPN active all my mobile traffic goes through my VPN, but when I tether, say my laptop, my laptop traffic goes through it's regular channel.

Is there a way to configure VPNHotspot to route all traffic through my VPN while using system hotspot?

Thanks @Mygod I really appreciate you responding!

Khon

**Comment by Mygod** [comment]
Have you disabled IPv6 tethering? Additionally, you can also put `none` in fallback interface.

**Comment by kingarawana** [comment]
Yeah, IPv6 is disabled and I've entered `none` under 'Fallback upstream interface'. I tested it by enabling the 'Wi-Fi hotspot' option under 'Manage system tethering..'.  but it still doen't work. Temporary wifi still works as before (though I noticed before that it does seem to disconnect every 30 minutes or so)

For more context I'm on the OnePlus 6+, Android 9, OxygenOS 9.0.7. I'm using OpenVPN connected to my own OpenVPN server on AWS.

**Comment by Mygod** [comment]
You need to enable Wi-Fi hotspot and enable `wlan0` (or whatever that pops up next) to use VPN tethering.

**Comment by kingarawana** [comment]
Hey @Mygod So I've been testing what you said to do the past few days. It seems to work sometimes, but doesn't work in other times. Do you have any guesses as to what might be happening? When I use Temporary WiFi hotspot, it works every time.

**Comment by Mygod** [comment]
Are you using OnePlus 6 or 6T? There is no 6+. Also what do you mean by "not working"? It might be helpful if you can grab a logcat while it's not working.

**Comment by kingarawana** [comment]
My apologies, I meant OnePlus 6T. My private VPN is in Oregon, so visit this website https://iplocation.com to check whether my WiFi hotspot is correctly routing me through my VPN or not.

When I use Temporary WiFi, it correctly shows that my request is coming from Oregon, when it's not, it shows that my request is coming from Los Angeles (my actual location).

When I try what you said with enabling WiFi through the app and enabling `wlan0` it sometimes correctly shows my IP coming from Oregon, and other times when I reenable my hotspot it shows LA.

To be clear, once it works, it my IP stays in Oregon, it doesn't switch back and forth. It only sometimes doesn't work if I stop the VPNHotspot then later enable it again.

Here's logcat. I captured this right after enabling hotspot and `wlan0` in the app.

`01-03 06:59:37.616  6505  6537 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
01-03 06:59:37.631  6505  6537 I chatty  : uid=10324(be.mygod.vpnhotspot) RenderThread identical 1 line
01-03 06:59:37.648  6505  6537 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
01-03 06:59:37.664  3077  3077 D NotificationListener: onNotificationPosted# hash: 48802421 sbn: StatusBarNotification(pkg=be.mygod.vpnhotspot user=UserHandle{0} id=1 tag=null key=0|be.mygod.vpnhotspot|1|null|10324: Notification(channel=tethering pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0xff4caf50 vis=PUBLIC))
01-03 06:59:37.665  6505  6537 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
01-03 06:59:37.672  3077  3077 D NotificationListener: onNotificationPosted# hash: 48802421 sbn: StatusBarNotification(pkg=be.mygod.vpnhotspot user=UserHandle{0} id=1 tag=null key=0|be.mygod.vpnhotspot|1|null|10324: Notification(channel=tethering pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0xff4caf50 vis=PUBLIC))
01-03 06:59:37.674  1774  1774 D NotificationEntryMgr: No peeking: unimportant notification: 0|be.mygod.vpnhotspot|1|null|10324
01-03 06:59:37.674  1774  1774 D NotificationEntryMgr: No peeking: unimportant notification: 0|be.mygod.vpnhotspot|1|null|10324
01-03 06:59:37.680  1774  1774 D StatusBar: updateMediaMetaData: lockWallpaper = null
01-03 06:59:37.680  1774  1774 D StatusBar: updateMediaMetaData: hasArtwork = false, mState:0, false, mDozing:false, delay:0, true, vis:8, alpha:0.002, false, meta:false, fading:false, 0, false
01-03 06:59:37.683  6505  6537 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
01-03 06:59:37.690  1774  1774 D NotificationEntryMgr: No peeking: unimportant notification: 0|be.mygod.vpnhotspot|1|null|10324
01-03 06:59:37.691  1774  1774 D NotificationEntryMgr: No peeking: unimportant notification: 0|be.mygod.vpnhotspot|1|null|10324
01-03 06:59:37.694  1774  1774 D StatusBar: updateMediaMetaData: lockWallpaper = null
01-03 06:59:37.694  1774  1774 D StatusBar: updateMediaMetaData: hasArtwork = false, mState:0, false, mDozing:false, delay:0, true, vis:8, alpha:0.002, false, meta:false, fading:false, 0, false
01-03 06:59:37.699  6505  6537 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
01-03 06:59:37.554   911  1470 I chatty  : uid=1000(system) ConnectivitySer identical 5 lines
01-03 06:59:37.554   911  1470 D ConnectivityService: getDefaultDataSubscriptionId, sub id = 1
01-03 06:59:37.732   911  1252 D AutomaticBrightnessController: setAmbientLux(3.1393304)
01-03 06:59:37.969  6505  6537 I chatty  : uid=10324(be.mygod.vpnhotspot) RenderThread identical 16 lines
01-03 06:59:37.986  6505  6537 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
01-03 06:59:38.159   730 22456 E sensors-hal: handle_sns_client_event:67, pickup_sample: ts = 5135798850076 ns; value = [0.000000, 2.000000, 0.000000]
01-03 06:59:38.556   730 22462 E sensors-hal: handle_sns_client_event:51, device_orient_event: ts=5136198303982, type=4
01-03 06:59:39.113   911 22562 D RouterAdvertisementDaemon: RA sendto ff02::1%wlan0
01-03 06:59:39.199  3566  4045 D NetworkRestrictService: isWlan:false-----listRules is empty ....
01-03 06:59:39.372  3144 19246 W AdaptiveDiscoveryWorker: Exiting Adaptive Discovery. Current HOTSPOT_BSSID is NULL.
01-03 06:59:39.732   911  1252 D AutomaticBrightnessController: setAmbientLux(8.527524)
01-03 06:59:39.732   911  1252 D AutomaticBrightnessController: updateAutoBrightness: value=0.2026006, mScreenAutoBrightness=100, newScreenAutoBrightness=207
01-03 06:59:39.732   911  1252 I DisplayPowerController: useProximityForceSuspend = false
01-03 06:59:39.732   911  1252 D RestartProcessManager: Screen off is false
01-03 06:59:39.736   911  1252 I DisplayPowerController: useProximityForceSuspend = false
01-03 06:59:39.737   911  1252 D RestartProcessManager: Screen off is false
01-03 06:59:39.737   911   911 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
01-03 06:59:40.659   911  1252 I DisplayPowerController: useProximityForceSuspend = false
01-03 06:59:40.659   911  1252 D RestartProcessManager: Screen off is false`

**Comment by Mygod** [comment]
Also feel free to try out 2.1.2. It might just fix your issue. :stuck_out_tongue:

**Comment by kingarawana** [comment]
So I just noticed something interesting. I don't recall if this happened on the previous version I was on, but I was just testing this right now w/ the latest version of VPNHotspot, and when I turn off wifi on my laptop and turn it back on, when it reconnects to my hotspot, https://iplocation.com/ shows my ip coming from my VPN server, but after a few seconds, it shows my ip get switched back to my current location (which I assume means my hotspot traffic is no longer being routed through my VPN).

**Comment by kingarawana** [comment]
Here's the log of when I'm on 'Temporary WiFi hotspot' and it's correctly routing through my VPN.

[vpnhotspot-1259521036448786988-temphotspot.log](https://github.com/Mygod/VPNHotspot/files/2724814/vpnhotspot-1259521036448786988-temphotspot.log)

**Comment by Mygod** [comment]
Your VPN is leaking via IPv6. Did you disable IPv6?

**Comment by kingarawana** [comment]
Goodness, you're right. When I read those instructions in the past, I read "..IPv6 tethering" and moved it to the off position thinking I was disabling it. My apologies, I should have read it more carefully!

It seems to be routing correctly now. Let me test it until the end of today. If all is well, I'll close this out.

Thanks!

**Comment by kingarawana** [comment]
It’s working every time now!

Thanks!

**Comment by kingarawana** [comment]
Btw, do you have other dontation options you prefer? I noticed the link in the app takes 30%.
