### ISSUE TITLE
[Feature] allow custom upstream network interface

### ISSUE THREAD

**Issue by simplerick-simplefun** [Mygod/VPNHotspot#561]
Currently, the app can only use upstream network interfaces that it detects. And it can only detect tun interface from android system VPN.

When using **custom tun VPN not from app but from shell**, for example running sing-box tun mode in shell as root, the app could not detect that tun interface, and thus cannot utilize such VPN.

Although currently user can input and set "Upstream network interface", the app would not use it in "Current upstreams" if that interface is not detected by the app.

Allowing user to set and enable such custom upstream network interface solves the problem. 

Alternatively, it would be difficult to implement but better for users if the app can detect such custom tun interfaces.

**Comment by Mygod** [comment]
This app supports any interface that implements Android `Network` API.
