### ISSUE TITLE
vpn hotspot cannot use

### ISSUE THREAD

**Issue by cond8r** [Mygod/VPNHotspot#565]
My phone is pixel8 pro has been successfully rooted, and installed vpn hostpod, I shared the VPN through repeater mode, my other phone iphone has successfully connected to this shared network, but only successfully connected, can't access the internet or open any webpage, the following is the log file of vpn hostpot, please help me to check - what is the problem![vpnhotspot-4663746645174784938.log](https://github.com/Mygod/VPNHotspot/files/15141126/vpnhotspot-4663746645174784938.log)

**Comment by Mygod** [comment]
Your logs seem fine. Can you export while the client is connected?

**Comment by cond8r** [comment]
> Your logs seem fine. Can you export while the client is connected?

I'll upload it later.

**Comment by merx7** [comment]
> Your logs seem fine. Can you export while the client is connected?

This worked fine for me on Lineage 20 but after updating I can no longer use with VPN only regular hotspot.![vpnhotspot-7562662874866449164 (1).log.zip](https://github.com/Mygod/VPNHotspot/files/15183901/vpnhotspot-7562662874866449164.1.log.zip)

**Comment by merx7** [comment]
I am having a similar issue. Regular Hotspot Works but when routed over VPN does not. I used VPN Hotspot this on Android 13 (LOS 20) with no issues. I waited to upgrade purposely to avoid any issues. I upgraded directly to Android 14 (LOS 14) and it doesn't work. Some how I once got it to work after trying over and over and over again. But now when attempting to use it does not. If this cannot be fixed I'll have to downgrade. Pixel 5 Device
Rooted
![vpnhotspot-7562662874866449164 (1).log.zip](https://github.com/Mygod/VPNHotspot/files/15202013/vpnhotspot-7562662874866449164.1.log.zip)

**Comment by Mygod** [comment]
@merx7 Do you have always-on VPN or VPN lockdown enabled?

**Comment by merx7** [comment]
Yes I did on Android 13. While attempting to try again I connected an iPhone first then a laptop. It worked for a bit.
I am buying another model phone to test out downgrading and transfering app data. I can help test if needed

**Comment by cond8r** [comment]
I am running vpn hostpod on android14 and even though I have rooted
pixel8p,I still can't share vpn to another phone and the other phone can't
access the internet.

Erv ***@***.***> 于2024年5月4日周六 04:38写道：

**Comment by Mygod** [comment]
I guess v2.17 does not work with VPN lockdown. I'll try to fix it.

**Comment by Mygod** [comment]
@merx7 Another thing I noticed is that you were using DSU. I have no plan for supporting DSU.

**Comment by merx7** [comment]
> @merx7 Another thing I noticed is that you were using DSU. I have no plan for supporting DSU.

Do you mean my Custom Rom?

**Comment by Mygod** [comment]
Generic system image/dynamic system update.

**Comment by cond8r** [comment]
My system is a native system image

Mygod ***@***.***> 于2024年5月5日周日 12:18写道：
