### ISSUE TITLE
Failed to launch root deamen and wifi repeater doesn't work correctly

### ISSUE THREAD

**Issue by alr86** [Mygod/VPNHotspot#567]
Everytime I open the app or click on "Tethering" tab on bottom navigation bar, app says:"Failed to launch root deamen"
When I click on Repeter option, that is will be actived but connected clients can not use internet but hotspot mode working correctly.

Debug log: 
[vpnhotspot-7245594519047352593.log](https://github.com/Mygod/VPNHotspot/files/15170231/vpnhotspot-7245594519047352593.log)

**Comment by Mygod** [comment]
Install the official apk either from GitHub or Google Play.
