### ISSUE TITLE
VPN to local proxy?

### ISSUE THREAD

**Issue by 54huige** [Mygod/VPNHotspot#57]
VPN to local proxy? is ok? please

**Comment by Mygod** [comment]
I cannot understand you.

**Comment by blackzafiqz** [comment]
@54huige you want to bind the vpn to specific port?

**Comment by 54huige** [comment]
> @ 54huige你想将vpn绑定到特定端口吗？

yes . how to do it? Now my computer has connected many vpn,i set up it and make it no global proxy ,now i need to make every vpn has Local Proxy by setting them,now i cannot to  Surf the Internet by listen to miniport（vpn）by  proxy .
