### ISSUE TITLE
Restart after reboot

### ISSUE THREAD

**Issue by nikcain** [Mygod/VPNHotspot#581]
I'm using an Ulefone Armor X11 phone with Android 13, and struggling to get vpnhotspot to restore the hotspot after a reboot. 

The phone is rooted with Magisk, and I've added vpnhotspot as a system app using a Magisk module. My VPN is wireguard, using the wireguard android client. According to logcat neither app starts unless I unlock the phone, however even a manual unlock doesn't start the hotspot. The VPN will be connected eventually (after an unlock, and a few minutes after that), but vpnhotspot doesn't start the hotspot (I would also need ap0 turned on too). I've tried rebooting with the system hotspot turned on too. 

The Ulefone doesn't have settings for auto launch apps, even for Android < 13. It uses something called Duraspeed for battery management, and I have this as off.

Ideally I'd like the phone to be able to reboot and become a VPN'd hotspot without any user interaction, but if they had to unlock the phone once that would be at least a small step forward (as long as they don't need to launch and configure vpnhotspot)

**Comment by Mygod** [comment]
No plan for this.
