### ISSUE TITLE
Join the auto-open system Ethernet sharing

### ISSUE THREAD

**Issue by SatenRuiko-Lv0** [Mygod/VPNHotspot#582]
Excuse me, can you add the following functions?
When it is detected that the Ethernet sharing in the system settings is in an openable state, the Ethernet sharing function that comes with the system is automatically turned on.

**Comment by Mygod** [comment]
I think this should be doable through tasker or something.

**Comment by SatenRuiko-Lv0** [comment]
> I think this should be doable through tasker or something.

I'm very sorry, I can't find a suitable implementation method on tasker. Excuse me, is the function of opening Ethernet sharing in your software realized by adb shell instruction?
