### ISSUE TITLE
[Help] VPNHotspot + Box for Magisk

### ISSUE THREAD

**Issue by GFlabian** [Mygod/VPNHotspot#583]
I'm using Box for Magisk to connect to proxy. Is there any way to hotspot that? Or at least adb proxy if not box.

**Comment by Mygod** [comment]
No plan for this.

**Comment by Mygod** [comment]
What is the advantage of using Box for Magisk over a normal VPN app?

**Comment by GFlabian** [comment]
Changing the proxy directly from command line. It is very useful when multiple ip changes are required
