### ISSUE TITLE
Dual Band hotspot issues

### ISSUE THREAD

**Issue by huajijam** [Mygod/VPNHotspot#584]
My device is Pixel7Pro,running  on Android 13(TQ3A.230901.001)

I met a problem when a device connected via wifi6,no network will be available

I have notice that only WLAN2(the wifi4 one) have option to enable VPNHotspot,but not WLAN3(the wifi6 one)

any idea?

![Screenshot_20240617-130503.png](https://github.com/Mygod/VPNHotspot/assets/29218242/29845c7d-b848-4565-8070-a7503a7716cb)

when no network:
![Screenshot_20240617-130715.png](https://github.com/Mygod/VPNHotspot/assets/29218242/20385711-f884-4525-ae88-4d6ff41048f5)

when network is available:
![Screenshot_20240617-131010.png](https://github.com/Mygod/VPNHotspot/assets/29218242/5ba232db-943a-47f6-b116-91781b50711d)

**Comment by Mygod** [comment]
I don't think this is an issue of this app. In the first screenshot, it looks like the device has connected to the hotspot but has not received an IP assignment yet. In the second screenshot, everything works as expected. This app does not affect system DHCP although you could try DHCP workaround in the settings.
