### ISSUE TITLE
[Feature]Keep app alive

### ISSUE THREAD

**Issue by wukan1986** [Mygod/VPNHotspot#588]
I use v2rayNG+VPN Hotspot to share the internet and only open these two app.
And make some settings

1. Battery saver -> No restrictions
2. Lock app in recent tasks

My phone is Xiaomi 8, RAM 6GB，Android 10

After using it for a period of time, v2rayNG is still alive, while VPN Hotspot has already been closed.

I also found that if I close VPN Hotspot during recent tasks, I can still access the internet,
but reopen VPN Hotspot, wlan1's status is off.

But if it is automatically shut down by the system, then the internet cannot be accessed

**Comment by wukan1986** [comment]
I found that if the IP Masquerade Mode is set to None, even if the application exits, it can still access the internet.

**Comment by Mygod** [comment]
DNS is handled by the app (among other things). Do not close the app.

**Comment by Mygod** [comment]
This app does not kill itself.

**Comment by wukan1986** [comment]
I found that App Info->Permissions allow some settings, app will not be killed
