### ISSUE TITLE
[Feature] RNDIS Reverse sharing network

### ISSUE THREAD

**Issue by huzesama** [Mygod/VPNHotspot#589]
When I used iptables to configure NAT to reverse a network share, I found some issues that prevented me from taking the next steps. My phone doesn't have a network and I want to use my PC's network via USB. I turned on USB tethering on my phone, and then configured Ethernet on Windows to allow RNDIS access. For convenience, I also want to fix the IP of the PC in RNDIS. But after that, VPNhotspot can't use it. SO I REQUEST TO ADD THE ABILITY TO REVERSE USB TETHERING IN ROOT MODE. And I was able to use a different VPN on my phone. I've searched for projects with reverse USB network sharing, but they all create a VPN.
There are similar websites for the operations I mentioned above: https://www.jianshu.com/p/3ef382f04f7a

**Comment by Mygod** [comment]
https://github.com/Genymobile/gnirehtet
