### ISSUE TITLE
ADD defult password option for repeater 

### ISSUE THREAD

**Issue by jotesoft** [Mygod/VPNHotspot#593]
I use vpn hotspot in my older samsung phone which has android 7. Vpn over hotspot only work using repetar mode. But the problem is Evey time i restart the phone the repetar starts with random password. I have to reconnect all of my device evey time with is very annoying. Please fix ability to set my network id and password. If i set my own name and password it resets every time i turn of repeater.

**Comment by Mygod** [comment]
Android 7 is no longer supported.
