### ISSUE TITLE
How did this app detected my driver country code?

### ISSUE THREAD

**Issue by Bigcheese458168** [Mygod/VPNHotspot#596]
I need to acceleration my game console and it only support Japanese wlan, but this app detected my driver country code is CN(actually true) and it do not work on 5ghz expect channel 149,153,157,161. What i need is 5ghz channel 40 or any Japanese wlan standard settings. I tried anything i can find, guise, change the language, change the time zone, reinstall by a Japanese gaccount, but it never works. My phone is pixel7 USA. Sry for my awful English.

**Comment by Mygod** [comment]
It's for display only. Your system determines the country code.
