### ISSUE TITLE
error created process is not a shell

### ISSUE THREAD

**Issue by Bumerangas** [Mygod/VPNHotspot#60]
Hello, App not working this error occur when i press button near wlan0 for tethering activation as i understand. App version 2.1.3 , android 7.1.2 LineageOS,

**Comment by Mygod** [comment]
Do you have root?

**Comment by Bumerangas** [comment]
Thank you for help, this problem really was with root on my android, by default was magisk root so checked with 4 root checker apps it was shown as rooted, but really not.

Changed rooting solution to SuperSU and solved my problem
https://forum.xda-developers.com/apps/supersu/v2-64-2-66-supersu-mode-t3286120

**Comment by Mygod** [comment]
Good to know that. I don't think this app has compatibility issues with Magisk but I suppose your Magisk root was not correctly installed. Anyway, closing this for now.
