### ISSUE TITLE
After using the software, open the system hotspot connection issue.

### ISSUE THREAD

**Issue by Renzh35** [Mygod/VPNHotspot#602]
After using the software, simply open the WIFI hotspot from the system, and the connector can connect, but cannot access the internet.![Screenshot_20240827_122013.jpg](https://github.com/user-attachments/assets/a4b3a966-be87-4d0a-bcfe-41e32d2e64c3)

As shown in the picture, the wlan2 switch needs to be turned on.

**Comment by Mygod** [comment]
Yes.

**Comment by Renzh35** [comment]
May I ask how to solve this? When I want to quickly complete the action of turning on the hotspot solely through this switch in the system.> Yes.

**Comment by Mygod** [comment]
Yes. Click the eye icon on the top right and select wlan0. Also go to settings and check "Auto start services" so that the service can auto start after reboot.

**Comment by Renzh35** [comment]
> Yes. Click the eye icon on the top right and select wlan0. Also go to settings and check "Auto start services" so that the service can auto start after reboot.

好的😊，谢谢😜
