### ISSUE TITLE
I can't share vpn

### ISSUE THREAD

**Issue by karkit7117** [Mygod/VPNHotspot#607]
I try share vpn with my computer but didn't work
![Screenshot_20240914-043509_VPN Hotspot.png](https://github.com/user-attachments/assets/3ce49d6c-7c4f-41a0-96c7-e3fc0cc0c4e3)

![Screenshot_20240914-043513_Settings.png](https://github.com/user-attachments/assets/de6341ab-5397-4380-8afc-5099a7f30080)

![Screenshot_20240914-043949_Lucifer.png](https://github.com/user-attachments/assets/5db8a350-d623-4500-96e1-92658a6b450e)

Where did I go wrong?

**Comment by Mygod** [comment]
Turn on wlan1.

**Comment by karkit7117** [comment]
It didn't work 

![IMG_20240914_174139.jpg](https://github.com/user-attachments/assets/fe29d142-8de7-49f1-a61b-8f10d22cdc7b)

![Screenshot_20240914-174206_VPN Hotspot.png](https://github.com/user-attachments/assets/1365e393-fc49-49cf-b84c-d8719db7aaf0)

**Comment by karkit7117** [comment]
I can't even transfer normal internet anymore
![Screenshot_20240914-175334_Settings.png](https://github.com/user-attachments/assets/d19c8126-c7c3-4285-9909-469861c00b4b)

![IMG_20240914_175402.jpg](https://github.com/user-attachments/assets/d0214dbb-1cff-40f7-b269-f63613f0bc84)

**Comment by karkit7117** [comment]
Thank you very much, it worked🙏🙏🙏
