### ISSUE TITLE
Does not work on  hyperOS (miui15) , Android14

### ISSUE THREAD

**Issue by httpsColon** [Mygod/VPNHotspot#616]
v2rayNG, vpn mode

**Comment by Mygod** [comment]
What does not work? Export debug information?

**Comment by httpsColon** [comment]
> What does not work? Export debug information?



> What does not work? Export debug information?

sorry, my bad; I mean the VPN network share doesn't work , but I turn off my laptop's wifi and try again, it works. thanks
