### ISSUE TITLE
Support Non-Rooting devices

### ISSUE THREAD

**Issue by IHNEL** [Mygod/VPNHotspot#62]
Hi @Mygod 
I understand that this code need to execute some commands with super-user permission and it only works on rooted devices. But I'm curious to make it work on non-rooted device too.

Is there any way to make internet sharing via Wifi Direct on non-rooted devices? Any hint are appreciated.

Cheers

**Comment by Mygod** [comment]
This app requires root to make changes to iptables and ip rule. This restriction is imposed by Linux kernel. To share Wi-Fi without root, you can try alternatives like [PdaNet+](https://play.google.com/store/apps/details?id=com.pdanet) and [NetShare-no-root-tethering](https://play.google.com/store/apps/details?id=kha.prog.mikrotik). (note: these apps are neither free nor open source)

But if you don't feel like paying for those apps, you can alternatively use this app with a proxy server, e.g. [Proxy Server](https://play.google.com/store/apps/details?id=com.icecoldapps.proxyserver) (disclaimer: I have not tried this app), and set up your clients to use your Android device as proxy.

By the way, here are some other features you should be able to get with this app without root:

* View connected devices for system tethering and monitor them;
* Create a hotspot that has only LAN connections;
* Toggle tether switches if you can't do it already;
* Play around with settings and the user interface in general. 😛

**Comment by samnet** [comment]
> This app requires root to make changes to iptables and ip rule. This restriction is imposed by Linux kernel. To share Wi-Fi without root, you can try alternatives like [PdaNet+](https://play.google.com/store/apps/details?id=com.pdanet) and [NetShare-no-root-tethering](https://play.google.com/store/apps/details?id=kha.prog.mikrotik). (note: these apps are neither free nor open source)
> 
> But if you don't feel like paying for those apps, you can alternatively use this app with a proxy server, e.g. [Proxy Server](https://play.google.com/store/apps/details?id=com.icecoldapps.proxyserver) (disclaimer: I have not tried this app), and set up your clients to use your Android device as proxy.
> 
> By the way, here are some other features you should be able to get with this app without root:
> 
> * View connected devices for system tethering and monitor them;
> * Create a hotspot that has only LAN connections;
> * Toggle tether switches if you can't do it already;
> * Play around with settings and the user interface in general. 😛

Another remark:
Using the Proxy Server way only works if you want to repeat a WiFi network on which you are connected, it seems to me. If you try while being connected on 4G, it won't work. Correct me if I am wrong :).

**Comment by Mygod** [comment]
> When you say "Toggle tether switches if you can't do it already", what do you mean?

I updated the original comment.

> The Proxy Server app works (I tried it: in conjunction with a WiFi-direct connection and some elementary client side configuration, traffic is routed to the Internet) but isn't open source. Do you know of some code that could help us build a simple proxy server?

https://lmgtfy.com/?q=linux+proxy+server

> Using the Proxy Server way only works if you want to repeat a WiFi network on which you are connected, it seems to me. If you try while being connected on 4G, it won't work. Correct me if I am wrong :).

You are wrong. :)

It's theoretically possible at least but for now I'm not interested.

**Comment by IHNEL** [comment]
@Mygod 
Could you please lets me know if we are able to support non-rooted devices by using custom iptable command?
Below is the link to another open source which use the custom iptable seems.

ref: https://github.com/staf621/ki4a/blob/3e3099ebbfa08cdad18fde064f6c5751227068ec/src/main/java/com/staf621/ki4a/ki4aService.java#L439

**Comment by Mygod** [comment]
You do not need root to run iptables binary. You need root to communicate to the kernel to modify iptables.

**Comment by IHNEL** [comment]
Does it make sense if we will modify the iptables first out side , then execute it in app?

FYI: I am investigating about the possibility of solution to route all network traffics.

**Comment by Mygod** [comment]
You either find a way to talk to kernel directly or talk to netd indirectly. Either way, I'm sure [Google will be happy to give you money if you managed to do that](https://www.google.com/about/appsecurity/android-rewards/index.html) (and probably fix it in their next security update).

**Comment by JReming85** [comment]
Anyone have luck going rootless using Shizuku?

Ordered a new Pixel 8 pro, and don't want to root this time, so looking into alternatives for root abilities without rooting to run some of my favorite apps.

**Comment by kayrus** [comment]
@Mygod I would also like to see Shizuku support. In some cases, ADB can be executed as root, thereby granting Shizuku root privileges, enabling it to modify iptables.

**Comment by JReming85** [comment]
Already checked, does not give access to use iptables.  Just gives the ability to see the filesystem

**Comment by supermansaga** [comment]
> Already checked, does not give access to use iptables.  Just gives the ability to see the filesystem
> 
> 

Meaning technically no luck, even if they are willing to look into it further?

**Comment by JReming85** [comment]
Correct, unless another rootless method is found, this isn't possible for
now.

On the bright side, i switched to using pairvpn.  It's made by the people
who created PDAnet.

It's pretty much the same concept of this just 1 extra step.

1. Start your hotspot
2. Connect the client
3. Start/Connect PairVPN

It creates a vpn tunnel from the client to the phone via the hotspot so all
traffic comes from the phone bypassing the tether counter.

Works great and is just as fast and reliable as being just in the hotspot,
and unlike 0danet or other alternatives, doesn't require config or proxys

**Comment by kayrus** [comment]
> Already checked, does not give access to use iptables.  Just gives the ability to see the filesystem

did you start shizuku in root mode through adb?

![photo_2024-03-31_22-07-04](https://github.com/Mygod/VPNHotspot/assets/4047483/3281fffe-86ab-458f-980c-77be38e67209)

**Comment by JReming85** [comment]
You would need root access for that feature.

This thread is for rootless

**Comment by kayrus** [comment]
I'm using lineageos that allows to run adb in root mode. I'm looking for the shizuku support because I don't want to install magisk.

**Comment by supermansaga** [comment]
> Correct, unless another rootless method is found, this isn't possible for now. On the bright side, i switched to using pairvpn. It's made by the people who created PDAnet. It's pretty much the same concept of this just 1 extra step. 1. Start your hotspot 2. Connect the client 3. Start/Connect PairVPN It creates a vpn tunnel from the client to the phone via the hotspot so all traffic comes from the phone bypassing the tether counter. Works great and is just as fast and reliable as being just in the hotspot, and unlike 0danet or other alternatives, doesn't require config or proxys

I need my phone to be already on VPN and share the vpn connection back to my desktop. Pairvpn doesn't seem to allow me to do it. It rather says, "This device has an active VPN connection. You need to disconnect it first before connecting PairVPN because chained VPN is not supported."

**Comment by JReming85** [comment]
> I'm using lineageos that allows to run adb in root mode. I'm looking for the shizuku support because I don't want to install magisk.

There are plenty of su managers out there that only need root like supersu.

**Comment by JReming85** [comment]
> > Correct, unless another rootless method is found, this isn't possible for now. On the bright side, i switched to using pairvpn. It's made by the people who created PDAnet. It's pretty much the same concept of this just 1 extra step. 1. Start your hotspot 2. Connect the client 3. Start/Connect PairVPN It creates a vpn tunnel from the client to the phone via the hotspot so all traffic comes from the phone bypassing the tether counter. Works great and is just as fast and reliable as being just in the hotspot, and unlike 0danet or other alternatives, doesn't require config or proxys
> 
> I need my phone to be already on VPN and share the vpn connection back to my desktop. Pairvpn doesn't seem to allow me to do it. It rather says, "This device has an active VPN connection. You need to disconnect it first before connecting PairVPN because chained VPN is not supported."

Do you need the VPN to access services or resources behind it?

If it's just to hide tether, then it's no longer needed.

If you need to access local services behind the VPN, then you can try using a proxy or wireguard.

There is software like proxifier that can tunnel all or selected apps through a proxy, or wireguard which should be able to be ran alongside the vpn

**Comment by kayrus** [comment]
> There are plenty of su managers out there that only need root like supersu.

I don't want to use su managers. I'd like to enable root access only via adb and shizuku. Don't ask why.

**Comment by JReming85** [comment]
> > There are plenty of su managers out there that only need root like supersu.
> 
> I don't want to use su managers. I'd like to enable root access only via adb and shizuku. Don't ask why.

Well shizuku i don't think it's the right tool for you then.  It only gives access to the filesystem, nothing beyond that.

Also it looks like the github repo might be dead

**Comment by BRBsoup** [comment]
What about Device Owner account/app privileges like OwnDroid (https://github.com/BinTianqi/OwnDroid) and/or Dhizuku, maybe some combination of Shizuku + ADB + OwnDroid/Dhizuku can achieve something further here?

**Comment by 7heMech** [comment]
To everyone in here, this worked for me to hotspot my WiFi: https://github.com/pyamsoft/tetherfi

**Comment by supermansaga** [comment]
> To everyone in here, this worked for me to hotspot my WiFi: https://github.com/pyamsoft/tetherfi

Thanks. But it didn't work for me. It says, "No internet. Secured."

**Comment by 7heMech** [comment]
> > To everyone in here, this worked for me to hotspot my WiFi: https://github.com/pyamsoft/tetherfi
> 
> Thanks. But it didn't work for me. It says, "No internet. Secured."

You didn't read the instructions then, you have to set proxy config on the connecting device, [find your device on this page](https://github.com/pyamsoft/tetherfi/wiki/Setup-A-Proxy#android)

**Comment by vincentng295** [comment]
I heard its possible with Shizuku as state here https://github.com/2dust/v2rayNG/pull/5903

> Android’s regular VpnService protects traffic originating from the Android device itself. Traffic forwarded by Android’s tethering stack does not normally enter that VPN, so clients connected through a hotspot or USB tethering can bypass v2rayNG entirely.
> Root-based solutions can redirect forwarded traffic with firewall and policy-routing rules, but this is not available on locked, non-rooted devices.
> This implementation uses Android’s test-network infrastructure through Shizuku to provide the tethering stack with a protected upstream network without requiring root.

**Comment by Mygod** [comment]
That's an interesting recent API addition that I missed. I can definitely look into it.

**Comment by carlelieser** [comment]
I have a [working prototype](https://github.com/carlelieser/shizzi) for non-rooted devices (requires [Shizuku](https://github.com/RikkaApps/Shizuku/releases/tag/v13.6.0)).

 It patches clients through a test TUN and effectively bypasses hotspot limits.

**Comment by Mygod** [comment]
🤔 Networking seems so much easier in golang.
