### ISSUE TITLE
Problem connecting to the Repeater point.

### ISSUE THREAD

**Issue by zaebald** [Mygod/VPNHotspot#621]
Hello, I am using VPN Hotspot on Samsung Galaxy A51. Root rights are obtained and access to the application is granted. The first time I used it everything was fine and all devices saw this Repeater hotspot. But after a month some of the devices can not connect to this network because it is not in the list of available. I think the problem was caused by an update to the app, so the Repeat settings config was overwritten and now there are several of them. This is just my guess, but I would like to get a solution to this problem or at least know where the Repeater settings config is located.

P.S. Another problem on the distribution side. Lately, when Repeater mode is enabled, the device that is giving out the Wi-Fi hotspot (in my case Samsung A51) for some unknown reason disconnects from the hotspot it is giving out. That is, the Repeater access point is visible, but without Internet access. The solution is to go into the settings and manually connect to the network again. There were no such problems before. Power saving mode is turned off. The VPN Hotspot application has been granted full access rights. Please help.

**Comment by Mygod** [comment]
You can access your repeater settings in the top right corner of the app after it is enabled.

**Comment by zaebald** [comment]
I have access to the settings, but the configuration file is in the wrong place. I would like to ask you to reread my post again, where I described all the connection difficulties. I did not find a solution to these problems in the upper right corner.

**Comment by zaebald** [comment]
In Play Market you react to a bad rating as a developer immediately and respond with a full and detailed answer, but here I asked for help and you point me to the Repeater settings. Please reread my appeal again and please try to give a correct answer.
