### ISSUE TITLE
Fixed gateway for usb0 on Android 14

### ISSUE THREAD

**Issue by structdjm79** [Mygod/VPNHotspot#623]
Could you make an option or patch to set a non randomized gateway for usb0 interface? Android has completely randomized the gateway on the usb0 interface at boot eg, 192.168.X.X, used to be 192.168.43.X which was manageable on my raspberry end for setting up a static address.... I use my Samsung Galaxy Tab A8 usb tethered to interface with my RaspberryPI via SSH and with the latest android OS 14 I can no longer set a static ip for the usb0 on RaspberryPI, so now I have to load up Termux and run arp -n | grep usb0 to get the client ip for JuiceSSH every time I boot the tablet

**Comment by Mygod** [comment]
Okay I see that you actually want static IP on clients. Why not just run DHCP?

**Comment by structdjm79** [comment]
I need to set a static ip on the raspberry so I connect to it with my android tablet ssh, which isn't possible anymore because android changed usb0 to random subnets 192.168.?.? so i`m able to predict its random gateway, in the past it was possible cause android's usb0 interface only changed last subnet of the gateway eg 192.168.43.?

**Comment by structdjm79** [comment]
> Okay I see that you actually want static IP on clients. Why not just run DHCP?

no, I meat to say server ip....

I need to set a static ip on the raspberry so I connect to it with my android tablet ssh, which isn't possible anymore because android changed usb0 to random subnets 192.168.?.? so i`m able to predict its random gateway, in the past it was possible cause android's usb0 interface only changed last subnet of the gateway eg 192.168.43.?

**Comment by Mygod** [comment]
So why not just run DHCP on your Rasp Pi?

**Comment by structdjm79** [comment]
> So why not just run DHCP on your Rasp Pi?
because I don't know the gateway of the android tablet, I would have to specify androids gateway, not sure how to set a gateway on 192.168.?.? is that even possible
