### ISSUE TITLE
[Feature] Share internet with wifi access point

### ISSUE THREAD

**Issue by UnderSampled** [Mygod/VPNHotspot#626]
I have a need to supply cellular internet to a network while also being connected to said network. This guide seems to indicate this should be possible without involving a second hotspot:

https://android.stackexchange.com/questions/236943/set-android-as-internet-gateway-to-local-router-not-mobile-hotspot#246574

This seems simple enough, but feels like it would be much better to control through VPNHotspot than as a string of scripts and automation apps.

In theory, all I'd need to do is enable it with static IP, and set the my router to use that ip as the gateway, correct?

**Comment by Mygod** [comment]
#518
