### ISSUE TITLE
Dark Mode theme issue

### ISSUE THREAD

**Issue by C00LDroid** [Mygod/VPNHotspot#63]
I was using this app since a long time with dark mode today it changed to white theme automatically and then i realise there is no option for dark mode now it seems you removed it completely check attached screenshots
![screenshot_20190122-133947](https://user-images.githubusercontent.com/38692811/51521196-db2c3a00-1e4b-11e9-96eb-b71d5e5c6148.png)
![screenshot_20190122-134004](https://user-images.githubusercontent.com/38692811/51521197-dbc4d080-1e4b-11e9-84b4-81b1cf65019f.png)

**Comment by Mygod** [comment]
There was never an option in this app. This app decides light/dark mode following your system theme.

**Comment by C00LDroid** [comment]
> There was never such option in this app. This app decides light/dark mode following your system theme.

Ohh my bad 
Just changed my device theme to dark and it worked thanks for quick response
