### ISSUE TITLE
Feature Request - Add mac vendor database

### ISSUE THREAD

**Issue by 1nikolas** [Mygod/VPNHotspot#66]
It's useful to show device vendor on connected devices based on an offline database. Thanks in advance

**Comment by Mygod** [comment]
Why?

**Comment by 1nikolas** [comment]
You can understand better who is connected. It could be online if that's the porblem

**Comment by pupyc** [comment]
You can already name clients so, don't think it will be a good addition

**Comment by Mygod** [comment]
Well, I guess we can assign a default name for each device using its vendor (if available) through an online lookup. An offline database requires much maintenance IMO and might use up some RAM for no good reasons.
