### ISSUE TITLE
[Feature] Add client isolation

### ISSUE THREAD

**Issue by pupyc** [Mygod/VPNHotspot#67]
This a security feature on most home routers I've used previously. 

It will be nice to have that here too, simply what it does is isolating clients so they can't connect to each other.

I don't know whether it's possible or not, with Android.

**Comment by Mygod** [comment]
IMO wireless isolation is the worse (if not wrong) way to do security as it breaks the basic premises of the Internet. Also this app is designed to share Internet with your own devices (or your friends), not your worst enemies.

**Comment by pupyc** [comment]
@Mygod I really need this no messing :stuck_out_tongue_winking_eye:

**Comment by Mygod** [comment]
I don't need you to claim that you need this. Explain your usage scenarios.

**Comment by pupyc** [comment]
@Mygod that does not mean I share my connection with enemies, but I have some IOT devices at home & office that I don't want them to connect to other locally connected devices just in case they were exposed and some got access to them, so I don't want all my devices ddosing random shit.

**Comment by Mygod** [comment]
Isolation doesn't stop random DDoSing, and if without isolation your device can get hijacked and you are worried about that, you should get a more secure alternative instead of that insecure shit, instead of asking the router to hack the issue away.
