### ISSUE TITLE
Did not work in global mode,but work well in pac mode in shadowsocks 全局模式异常

### ISSUE THREAD

**Issue by GainSury** [Mygod/VPNHotspot#71]
I use Xiaomi Max 2 with MIUI-9.1.24 based on Android 7.1.1。
I use shadowsocks 4.6.5 with VPN hotspot 2.1.4.
when in global mode in shadowsocks, it worked just like not opening shadowsocks. For me, in China, I cannot visit Google.com, Facebook.com. It reminded me that "ERR_SSL_PROTOCOL_ERRPR" 
But in pac mode it work well，I can visit google.com
Here log comes.
[vpnhotspot-1080967507.log](https://github.com/Mygod/VPNHotspot/files/2810781/vpnhotspot-1080967507.log)

**Comment by Mygod** [comment]
Try restarting VPN?

**Comment by GainSury** [comment]
> Try restarting VPN?

I have try 
1. restart VPN after opening VPNHotspot
2. restart VPNHostspot after opening VPN
3. start VPN, then start VPNHotspot
4. start VPNHotspot, then start VPN

Global mode 
![7852](https://user-images.githubusercontent.com/12730371/52095403-be3af800-25fd-11e9-854e-f48f52e92495.jpg)

Pac mode （bypass lan or bypass manland or other bypass mode is ok）
![7851](https://user-images.githubusercontent.com/12730371/52095400-bc713480-25fd-11e9-8b4f-e191c3564a5a.jpg)

And my VPNhotspot config is like this
![screenshot_2019-02-01-08-48-20-419_be mygod vpnhotspot](https://user-images.githubusercontent.com/12730371/52095626-add74d00-25fe-11e9-9393-b9a52fb11d41.png)
![screenshot_2019-02-01-08-48-22-767_be mygod vpnhotspot](https://user-images.githubusercontent.com/12730371/52095628-b039a700-25fe-11e9-8ef4-61eb05b4af47.png)

By the way, the WLAN Hotspot toggle button cannot work well in MIUI, it reminds that "You either need MANAGE_USERS or CREATE_USERS permission to:query user"

**Comment by Mygod** [comment]
I cannot reproduce this issue. Looking at your log, this seems to dup #52. Can you try this? https://github.com/Mygod/VPNHotspot/issues/52#issuecomment-451127131

**Comment by GainSury** [comment]
> I cannot reproduce this issue. Looking at your log, this seems to dup #52. Can you try this? [#52 (comment)](https://github.com/Mygod/VPNHotspot/issues/52#issuecomment-451127131)

you're right. The ipv6 seems not to be bridged exactly. The address of IPv4 is VPN's(America) and the address of IPv6 is spot itself(China).

**Comment by GainSury** [comment]
https://github.com/Mygod/VPNHotspot/issues/52#issuecomment-451127131
I have retried 
```
adb shell su -c 'echo 1 >/proc/sys/net/ipv6/conf/bridge0/disable_ipv6'
```
it works now.
The ipv6 is not leaked any more.
<img width="829" alt="default" src="https://user-images.githubusercontent.com/12730371/53486539-eebe6680-3ac3-11e9-8011-63eeb08cd193.png">

My MIUI version is MIUI-9.2.21

**Comment by Mygod** [comment]
Sounds like everything is fine now? Why did you reopen it?

**Comment by Mygod** [comment]
Please try v2.6.0 or newer and see if this issue is gone.

**Comment by GainSury** [comment]
> Please try v2.6.0 or newer and see if this issue is gone.

it still exists in v2.7.1
