### ISSUE TITLE
[Feature Request] Local network access from phone

### ISSUE THREAD

**Issue by knuxyl** [Mygod/VPNHotspot#72]
I cannot seem to access any pc connected to the wifi on the phone. I think I brought this up on here before and was told to get a VPN app that had some feature, but all the ones I have ever seen do not. I'm sure there is some kind of way to route all 192.168.43.X traffic to the hotspot, I'm just not familiar with how. Anyways, if this is out of the scope of what you can do sorry for wasting your time. 

I got a new phone recently and your app works 100% perfect on it, which it doesn't on any of my others, so thank you so much for all your hard work. This app is amazing.

**Comment by Mygod** [comment]
I see. As I've mentioned above, you should either fix this on your VPN app or report this to AOSP. I have no intention of fixing this as it would change other apps' behavior.
