### ISSUE TITLE
Android 6.0.1 Marshmellow compatibility

### ISSUE THREAD

**Issue by Matteljay** [Mygod/VPNHotspot#73]
Hi i'm a CAT S60 user with Android 6.0.1, no proper custom rom like LineageOS available afaik.
Love VPNHotspot because:
- compatibility with AFWall+ firewall (stock hotspot doesn't accept this)
- "run hotspot when power cable is connected" is somewhat possible with "Automate" (through terminal command line "am start ...") IF the start-on-boot service is enabled.

Seems to have stopped working for me after upgrading from some old version to 2.2.1
Even downgrading back doesn't work anymore. A connection is made from my desktop pc, VPNHotspot recognises the pc but a simple "ping 8.8.8.8" results in 100% packet drop.

- uninstalled VPNHotspot
- disabled AFWall+ completely
- disabled Automate
- purged iptables as per [link](https://serverfault.com/questions/200635/best-way-to-clear-all-iptables-rules)
- rebooted smartphone
- reinstalled VPNHotspot
Problem persists: 100% packet drop. Note the stock hotspot worked fine again, did change the hotspot name.

- deleted /data/misc/wifi/p2p_supplicant.conf as it "magically?" kept remembering the old hotspot name even after VPNHotspot was completely deleted.
After deleting the file and another installation of VPNHotspot the app generated its own hotspot name and password inside a new p2p_supplicant.conf. Tried to use it: still 100% packet loss while the stock hotspots keeps working fine. I can easily adjust the stock hotspot name & pw but VPNHotspot refuses this now and still doens't forward packets. Yes it has root rights and yes i tried every option in the settings tab.

Switching to stock hotspot for the time being, really hope a future release of VPNHotspot will get me back in the game ;)

**Comment by Mygod** [comment]
So I suppose you were on 2.1.4 previously? Have you tried downgrade AND a data wipe?

**Comment by Matteljay** [comment]
Don't know. But guess what, I tried it again with your question/suggestion: version 2.1.4
- uninstalled 2.2.2
- deleted /data/misc/wifi/p2p_supplicant.conf via adb shell & su
- rebooted phone
- installed 2.1.4
(at this point tapping the hotspot name is refused, telling me to run the Repeater first)
- went to the settings tab, tapped "Clean/reapply routing rules"
- granted root rights
- quit VPNHotspot
- restarted VPNHotspot
- ran the Repeater
- then i could change the name & pw!
& everything works again under 2.1.4
(yes i tried 2.2.2 once more but that failed again so i repeated above steps)
Thanks! Will stick to v214 for the time being.

**Comment by Mygod** [comment]
Fixed via https://github.com/Mygod/VPNHotspot/commit/fadf72b28a36e48f9d633c7e76319179b1fe2ee4. Check the next release (probably 2.2.3).
