### ISSUE TITLE
long icon press shortcut

### ISSUE THREAD

**Issue by 532910** [Mygod/VPNHotspot#77]
Please add support for icon press shortcut
https://developer.android.com/guide/topics/ui/shortcuts/

Start repeater of start tethering should be in the shortcut list.

**Comment by Mygod** [comment]
I'm pretty sure shortcuts aren't supposed to be used this way. Use QS Tiles instead.

**Comment by 532910** [comment]
Your assurance is pretty wrong. Please reopen and check https://github.com/schwabe/ics-openvpn for example.
