### ISSUE TITLE
Issues connecting to VPNHotspot network with my New Nintendo 3DS XL.

### ISSUE THREAD

**Issue by Mario0051** [Mygod/VPNHotspot#78]
I'm having issues in that the connection test on the 3DS do not complete successfully. I am using Hotspot Shield VPN as the VPN connection and using VPNHotspot to repeat the signal. I am using 1.1.1.1 DNS (1.0.0.1 Secondary) for both of the devices, with the Android device being the RCT6303W87DK. The VPNHotspot network is left as default. All the settings are at default.

**Comment by Mygod** [comment]
You need to supply much more information than that. Why don't you start by exporting debugging information?

**Comment by Mario3264** [comment]
How might I do that? I can try my best to give you that information if you can give the information on how to do it.

**Comment by Mygod** [comment]
It's at the end of the settings in this app.

**Comment by Mario3264** [comment]
I'm not sure if this is all of the data I had before I used the setting, but I sure hope it is, since that is what the setting suggests to me.: [vpnhotspot--399635134.log](https://github.com/Mygod/VPNHotspot/files/2882818/vpnhotspot--399635134.log)

**Comment by Mario3264** [comment]
Also, I have tested using my PC and it also doesn't connect.

**Comment by Mygod** [comment]
Please export debug information while the service is active.

**Comment by Mario3264** [comment]
Alright, I have connected it, and here is the resultant log file: [vpnhotspot-402531877.log](https://github.com/Mygod/VPNHotspot/files/2882913/vpnhotspot-402531877.log)

**Comment by Mygod** [comment]
What seems to be the problem? In this log, it seems like no clients are connected.

**Comment by Mario3264** [comment]
Alright, made another log, this time I made sure that it was connected under the "Clients" tab: [vpnhotspot--1664502031.log](https://github.com/Mygod/VPNHotspot/files/2887681/vpnhotspot--1664502031.log)

**Comment by Mygod** [comment]
Huh. Interesting. Can you try out [2.1.4](https://github.com/Mygod/VPNHotspot/releases/tag/2.1.4) and see if that works for you?

**Comment by Mario3264** [comment]
Tried again using 2.1.4, still didn't work (I made sure that it was connected under the "Clients" tab again): [vpnhotspot--1403080298.log](https://github.com/Mygod/VPNHotspot/files/2889688/vpnhotspot--1403080298.log)

**Comment by Mygod** [comment]
Have you tried connecting other clients to VPNHotspot? Does that work?

**Comment by Mario3264** [comment]
No, but I believe it will be the same.

**Comment by Mygod** [comment]
Closing this as per #152.
