### ISSUE TITLE
Failed in setting channels 12,13,14

### ISSUE THREAD

**Issue by chromer030** [Mygod/VPNHotspot#80]
Repeater failed in starting on 12,13,14 channels :" Failed to create P2P group (reason : internal error) "
Other channels works fine and great. 

[vpnhotspot-1544296227 log.zip](https://github.com/Mygod/VPNHotspot/files/2918635/vpnhotspot-1544296227.log.zip)

Android : 7.1.2
Device : Lenovo K3 Note
Rom : ViperOS Coral 3.1.1
VPNHotspot : 2.3.0

**Comment by Mygod** [comment]
Your Wi-Fi driver probably does not support those channels. You should report to your ROM developer instead.
