### ISSUE TITLE
IP Routing only works on initial run - wiregaurd

### ISSUE THREAD

**Issue by dragonsbloodxxx** [Mygod/VPNHotspot#83]
Howdy

Currently running wireguard using kernel mode on a oneplus 6t.

Whenever I first open VPN Hotspot cleanly, then turn on the hotspot, my tethered device is getting routed through my vpn properly. If I turn off the hotspot, then turn it back on again, I'm now routed through my mobile ISP. To be able to route through my vpn again, I have to force close VPN Hotspot, then reopen and turn on the hotspot again. I have tried Netling/Poll, both rooted and non rooted with the same results. Also, clean/reapply routing rules does not seem to change anything.

Any help would be great on this :D

**Comment by Mygod** [comment]
Debug information is always helpful for yielding insights onto this problem. It would be great if you can export them 2 times:

1. When it is working properly (for the first run);
2. When it is not.

You can find debug information in the settings.

**Comment by dragonsbloodxxx** [comment]
See attached, thanks again!

[working-wg.log](https://github.com/Mygod/VPNHotspot/files/2958020/working-wg.log)
[not-working-wg.log](https://github.com/Mygod/VPNHotspot/files/2958027/not-working-wg.log)

**Comment by Mygod** [comment]
Try v2.3.2.

**Comment by dragonsbloodxxx** [comment]
Great work, all fixed. Donation coming your way!
