### ISSUE TITLE
FC when starting Repeater on LOS 16  

### ISSUE THREAD

**Issue by ZeVince** [Mygod/VPNHotspot#86]
Hi there !

I just switched to LineageOS 16.0 on my Samsung SM-G900FD (klteduos) twrp-3.2.3-0-klteduos

Trying to start the Repeater mode hangs the application that eventually FC after a short while

Used to work perfectly with LineageOS 15.1

This is a great and very useful application, any help to make it work again would be much appreciated, thanks.

[vpnhotspot-2048141203189520374.log](https://github.com/Mygod/VPNHotspot/files/2958223/vpnhotspot-2048141203189520374.log)

**Comment by Mygod** [comment]
Vendor issue. Report to your rom developers instead.
