### ISSUE TITLE
UI changes for understanding

### ISSUE THREAD

**Issue by AWalton** [Mygod/VPNHotspot#87]
Firstly it would be useful if the password for temporary WiFi hotspots had the prefix `password:` so it's a bit clearer. 

Also `wlan0` should have something like "(enable this to route clients through the VPN also)". I was confused what this for until I checked GitHub.

**Comment by Mygod** [comment]
Contributions are welcome.

**Comment by Mygod** [comment]
Fixed in v2.4. For the second part, you should think of the indented switches as the children of "Manage system tethering" and does not do VPN tethering by itself.
