### ISSUE TITLE
Android pie problem

### ISSUE THREAD

**Issue by offferu** [Mygod/VPNHotspot#91]
VPN hotspot always has problem on Android pie. 
Repeater function works like a charm! 
However Wi-Fi hotspot function always has problem

Below are what I found
1) 1st time slide "WiFi-hotspot" to the left, although the button remain unchanged, it actually enabled, as the "wlan1" appears and hotspot symbol shows in the status bar. Then I click  "WiFi-hotspot" again, the button still no change but actually turned off hotspot.
2) click "WiFi-hotspot" again, no any response (wlan0 no longer appears), and I click "Manage system teathering...", I found "WiFi-hotspot" shows "Error"

I have tried several custom ROMs including AOSPExtended6.3, pixel experience, and AICP, all these are Android 9 and have same problem.

Logs as below
https://www.filehosting.org/file/details/789749/vpnhotspot-7253734456894481267.log

**Comment by Mygod** [comment]
This seems like an issue specific to your device. Please use system settings to switch on/off tethering instead.
