### ISSUE TITLE
Works on windows, not on ubuntu 18.04

### ISSUE THREAD

**Issue by bettdalpha** [Mygod/VPNHotspot#94]
Using windows, i can connect to the hotspot easily. But when it comes to ubuntu 18.04, it doesn't connect. It's stuck at connecting...

However, when i switch off anonytun and use normal network, Ubuntu can connect to the hotspot. 

What's the problem? Is there someway to fix it?

**Comment by Mygod** [comment]
Are you using repeater or hotspot? Are you using the same PC but with different systems? Have you tried other devices?

**Comment by bettdalpha** [comment]
I'm using hotspot. I've just tried with different operating operating systems. Doss it work on other Ubuntu systems?

**Comment by Mygod** [comment]
Works for me on Linux Mint 19.1.

**Comment by Mygod** [comment]
...which is based on Ubuntu 18.04 I believe. Have you tried DHCP workaround?

**Comment by bettdalpha** [comment]
Yeah, i tried it but it doesn't work yet.
I wonder if they're additional drivers i need to download

**Comment by cewatkins** [comment]
I busted my phone,
so how can u start from cli.
Tether in general? also i noted in the code calls to ip, is there a
scripting/notes on what gets called?

**Comment by Mygod** [comment]
@cewatkins Check out Routing.kt.

**Comment by Mygod** [comment]
As I cannot reproduce and it works for Windows, I'll assume it's somehow a bug in Ubuntu for now.

**Comment by bettdalpha** [comment]
Yes, it's an Ubuntu bug because it works on windows
