### ISSUE TITLE
Please use consistent tagging

### ISSUE THREAD

**Issue by licaon-kter** [Mygod/VPNHotspot#99]
Tags `2.2.9`, `2.3.0`, `v2.3.1` ... `v2.4.0` fdroid auto updater got confused... either use a `v` before numbers or not, but don't switch it (that often). :)

Ref: https://f-droid.org/wiki/page/be.mygod.vpnhotspot/lastbuild_122

Ref: https://gitlab.com/fdroid/fdroiddata/commit/cf569dcd17cfd91547e5999b028a1f30a8937df4

**Comment by Mygod** [comment]
Yes. I think we will stick to having a `v` prefix for tags since v2.3.1. Sorry for the inconveniences.
